Caps Scenario Builder: Main.legend.LegendItem Class Reference
Main.legend.LegendItem Class Reference
Public Member Functions
def __init__
def nextSibling
def storeAppearanceSettings
def restoreAppearanceSettings
def vectorLayerSymbology
def changeSymbologySettings
def setRendererV2
def addLayerToColoredLayers
def setPointsRuleRendererV2
def setLineColorAndWidth
def setPolygonColor
def setBaseTownsProperties
Public Attributes
legend
canvasLayer
layerName
isVect
layerId
openingScenario
child
Private Attributes
__itemIsExpanded
Detailed Description
Provide a widget to show and manage the properties of one single layer
Definition at line 48 of file legend.py.
Constructor & Destructor Documentation
def Main.legend.LegendItem.__init__ (self, parent, canvasLayer)
Definition at line 50 of file legend.py.
    def __init__(self, parent, canvasLayer):
        QtGui.QTreeWidgetItem.__init__(self)
        # debugging
        print "Main.legend.LegendItem() class"
        print 'Main.legend: The system path is', sys.path
        self.legend = parent
        self.canvasLayer = canvasLayer
        # Convert QStrings to unicode unless they are used immediately in a Qt method.
        # This ensures that we never ask Python to slice a QString, which produces a type error.
        self.layerName = unicode(self.canvasLayer.layer().name())
        self.canvasLayer.layer().setLayerName(self.legend.normalizeLayerName(self.layerName))
        self.setText(0, self.layerName)
        self.isVect = (self.canvasLayer.layer().type() == 0) # 0: Vector, 1: Raster
        self.layerId = self.canvasLayer.layer().id()
        self.openingScenario = self.legend.mainwindow.openingScenario
        '''
            This class is instantiated by the legend.Legend() class immediately after a layer is registered by QGIS.
            It creates a legend item that represents a map layer. Since this is very close to the first access we
            have to newly added layers, we set scenarioDirty here. We set the rendererV2 properties here because
            they only need to be set when a layer is loaded rather than every time a layer is changed (as in
            Main.mainwindow.activeLayerChanged()).  This is also the first chance to set layer properties,
            so we set visibility and color for all newly opened layers here.
        '''
        # Each time a layer is loaded (or removed) we set the scenarioDirty flag.
        # There is no need to set it if the scenario is already dirty.  Once a scenario
        # is dirty, the policy is it stays dirty until the user saves it.
        if not self.legend.mainwindow.scenarioDirty: self.legend.mainwindow.setScenarioDirty()
        # This method sets the renderer colors, marker types and other properties for certain vector layers.
        # Since the scenario's '.cap' file stores rendererV2 settings, we don't need to call the
        # method when opening a scenario.
        if self.isVect and not self.openingScenario:
            self.setRendererV2(self.canvasLayer.layer())
        # handle layer visibility when opening the app, "New Scenario" or "Open Scenario."
        if self.openingScenario or self.legend.mainwindow.openingOrientingLayers:
            # Make any layer in config.orientingLayersChecked visible
            if self.layerName in config.orientingLayersChecked:
                self.setCheckState(0, QtCore.Qt.Checked)
                self.canvasLayer.setVisible(True)
            else: # all other layers loaded will be hidden
                self.setCheckState(0, QtCore.Qt.Unchecked)
                self.canvasLayer.setVisible(False)
        else: # User chose "Add Vector Layer" or "Add Raster Layer" to add a single layer, so make visible.
            self.setCheckState(0, QtCore.Qt.Checked)
            self.canvasLayer.setVisible(True)
        # Get colors when opening a saved scenario and save to the coloredLayers dictionary.
        # We have to do this for all vector layers to know what layers are colored by the user
        # so we don't set default colors for them. Note that if the user later changes feature color
        # for a layer, it will be updated in the dictionary (see legend.Legend.layerSymbology())
        if self.isVect and self.openingScenario:
            self.addLayerToColoredLayers()
        # Now set colors for layers not colored in a scenario file or
        # specifically colored by the user (i.e. not in the coloredLayers dictionary).
        if self.isVect:
            if not self.legend.mainwindow.coloredLayers.get(self.layerName):
                if self.legend.currentColor == None or self.legend.currentColor == len(self.legend.mainwindow.defaultColors):
                    self.legend.currentColor = 0 # when we open the app or get to the end of the color list, we start again.
                print "Main.legend.LegendItem() class self.legend.currentColor is " + str(self.legend.currentColor)
                defColor = self.legend.mainwindow.defaultColors[self.legend.currentColor]
                self.canvasLayer.layer().rendererV2().symbols()[0].setColor(defColor)
                self.legend.currentColor += 1
        # debugging
        print "Main.legend.LegendItem() class: The coloredLayers are: "
        for k, v in self.legend.mainwindow.coloredLayers.iteritems():
            print "%s: %s" % (k, str(v.getRgb()))
        ''' Now set icons etc. for legend item '''
        pm = QtGui.QPixmap(20, 20)
        icon = QtGui.QIcon()
        if self.isVect:
            geom = self.canvasLayer.layer().geometryType() # QGis Geometry
            if geom == 0: # Point
                icon.addPixmap(QtGui.QPixmap(resources_prefix + "mIconPointLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
            elif geom == 1: # Line
                icon.addPixmap(QtGui.QPixmap(resources_prefix + "mIconLineLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
            elif geom == 2: # Polygon
                icon.addPixmap(QtGui.QPixmap(resources_prefix + "mIconPolygonLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
            else: print 'Unknown geometry: ' + unicode(geom)
            self.vectorLayerSymbology(self.canvasLayer.layer())
        else:
            self.canvasLayer.layer().thumbnailAsPixmap(pm)
            icon.addPixmap(pm)
            self.child = QtGui.QTreeWidgetItem(self)
            iconChild = QtGui.QIcon()
            iconChild.addPixmap(self.canvasLayer.layer().legendAsPixmap().scaled(15, 15, QtCore.Qt.KeepAspectRatio))
            self.child.setSizeHint (0, QtCore.QSize(15, 15))
            self.child.setIcon(0, iconChild)
        self.setIcon(0, icon)
        self.setToolTip(0, self.canvasLayer.layer().publicSource())
        layerFont = QtGui.QFont()
        layerFont.setBold(True)
        self.setFont(0, layerFont)
Member Function Documentation
def Main.legend.LegendItem.addLayerToColoredLayers (self)
Definition at line 271 of file legend.py.
References Main.legend.LegendItem.layerName, and Main.legend.LegendItem.legend.
Referenced by Main.legend.LegendItem.setBaseTownsProperties(), Main.legend.LegendItem.setLineColorAndWidth(), Main.legend.LegendItem.setPointsRuleRendererV2(), and Main.legend.LegendItem.setPolygonColor().
    def addLayerToColoredLayers(self):
        # debugging
        print "Main.legend.LegendItem.addLayerToColoredLayers()"
        color = self.canvasLayer.layer().rendererV2().symbols()[0].color()
        self.legend.mainwindow.coloredLayers[self.layerName] = color
def Main.legend.LegendItem.changeSymbologySettings (self, theMapLayer, pixmap)
Update the symbology settings on loading or changing layer color
Definition at line 182 of file legend.py.
References Main.legend.LegendItem.child.
Referenced by Main.legend.LegendItem.vectorLayerSymbology().
    def changeSymbologySettings(self, theMapLayer, pixmap):
        ''' Update the symbology settings on loading or changing layer color '''
        if not theMapLayer: return
        # Remove previous symbology items
        self.takeChildren()
        self.child = QtGui.QTreeWidgetItem(self)
        iconChild = QtGui.QIcon()
        iconChild.addPixmap(pixmap)
        self.child.setIcon(0, iconChild)
        childFont = QtGui.QFont()
        childFont.setPointSize(9)
        self.child.setFont(0, childFont)
def Main.legend.LegendItem.nextSibling (self)
Return the next layer item
Definition at line 158 of file legend.py.
    def nextSibling(self):
        """ Return the next layer item """
        return self.legend.nextSibling(self)
def Main.legend.LegendItem.restoreAppearanceSettings (self)
Restore the appearance of the layer item
Definition at line 166 of file legend.py.
References Main.legend.LegendItem.__itemIsExpanded.
    def restoreAppearanceSettings(self):
        """ Restore the appearance of the layer item """
        self.setExpanded(self.__itemIsExpanded)
def Main.legend.LegendItem.setBaseTownsProperties (self, vlayer)
Definition at line 451 of file legend.py.
References Main.legend.LegendItem.addLayerToColoredLayers().
Referenced by Main.legend.LegendItem.setRendererV2().
    def setBaseTownsProperties(self, vlayer):
        # debugging
        print "Main.legend.LegendItem.setBaseTownsProperties()"
        # Set the base_towns layer fill color to none
        rendererV2 = vlayer.rendererV2()
        symbol = rendererV2.symbols()[0]
        symbolMap = {"color": "255, 255, 255, 255", "style": "no",
                          "color_border": "DEFAULT_SIMPLEFILL_BORDERCOLOR",
                          "style_border": "DEFAULT_SIMPLEFILL_BORDERSTYLE",
                          "width_border": "0.3" }
        simpleSymbol = symbol.createSimple(symbolMap)
        rendererV2.setSymbol(simpleSymbol)
        self.addLayerToColoredLayers()
        vlayer.triggerRepaint()
def Main.legend.LegendItem.setLineColorAndWidth (self, vlayer, red, vlayerName)
Definition at line 404 of file legend.py.
References Main.legend.LegendItem.addLayerToColoredLayers().
Referenced by Main.legend.LegendItem.setRendererV2().
    def setLineColorAndWidth(self, vlayer, red, vlayerName):
        # debugging
        print "Main.legend.LegendItem.setLineColorAndWidth()"
        # this is a QgsLineSymbolLayerV2()
        symbolLayer = vlayer.rendererV2().symbols()[0].symbolLayer(0)
        # This dictionary (coloredLayers) is set when a saved scenario is opened, when an editing layer is created
        # (in dlgscenarioedittypes) or in Tools.shared.updateExtents() when reopening the editing layer after editing.
        # If the user had set a color other than the default,we reset it here.
        retval = self.legend.mainwindow.coloredLayers.get(vlayerName)
        if retval and retval != red: # being opened by updateExtents or copyScenario and user set color
            print "Main.legend.LegendItem.setRendererV2(): THERE IS A LINE COLOR"
            symbolLayer.setColor(retval)
        # being opened by updateExtents or copyScenario with some unknown QGIS color so we reset to red here
        elif retval and retval == red:
            symbolLayer.setColor(retval)
        # newly opened layer (not in coloredLayers) so default to red if the layer is being opened for the first time
        elif not retval:
            symbolLayer.setColor(red)
            self.addLayerToColoredLayers()
        else: print "Main.legend.LegendItem.setRendererVretvalThere is a 'retval' error"
        symbolLayer.setWidth(0.4)
        vlayer.triggerRepaint()
def Main.legend.LegendItem.setPointsRuleRendererV2 (self, vlayer, red, vlayerName)
Definition at line 278 of file legend.py.
References Main.legend.LegendItem.addLayerToColoredLayers().
Referenced by Main.legend.LegendItem.setRendererV2().
    def setPointsRuleRendererV2(self, vlayer, red, vlayerName):
        # debugging
        print "Main.legend.LegendItem.setPointsRuleRenderer()"
        ''' Create the rule based renderer. '''
        # This returns a QgsSymbolV2(). In particular a QgsMarkerSymbolV2().
        # This also returns a QgsMarkerSymbolLayerV2() layer. In particular a QgsSimpleMarkerSymbolLayerV2().
        symbol = QgsSymbolV2.defaultSymbol(QGis.Point)
        # renderer only needs a symbol to be instantiated
        rendererV2 = QgsRuleBasedRendererV2(symbol)
        # get the symbols list and symbol (usually only one symbol)
        symbol = rendererV2.symbols()[0]
        symbolLayer = symbol.symbolLayer(0)
        symbolLayer.setSize(2.0)
        symbolLayer.setColor(red)
        '''
            Now we set the rules for rendering different scenario edits, so that the user can
            easily determine what features represent.
            Choices for symbols are: circle, rectangle, diamond, pentagon, cross, cross2, triangle,
            equilateral_triangle, star, regular_star, arrow.
        '''
        newSymbol = QgsSymbolV2.defaultSymbol(QGis.Point)
        # dams
        map1 = {"name": "rectangle", "color": "255,0,0,255", "offset": "0,0",
               "color_border": "0,0,0,255", "size": "2.0", "angle": "DEFAULT_SIMPLEMARKER_ANGLE"}
        damSymbol = newSymbol.createSimple(map1)
        damLayer = damSymbol.symbolLayer(0)
        # terrestrial crossing
        map2 = {"name": "pentagon", "color": "255,0,0,255", "offset": "0,0",
               "color_border": "0,0,0,255", "size": "3.0", "angle": "DEFAULT_SIMPLEMARKER_ANGLE"}
        terrSymbol = newSymbol.createSimple(map2)
        terrLayer = terrSymbol.symbolLayer(0)
        # tidal restriction
        map3 = {"name": "regular_star", "color": "255,0,0,255", "offset": "0,0",
               "color_border": "0,0,0,255", "size": "4.0", "angle": "DEFAULT_SIMPLEMARKER_ANGLE"}
        tidalSymbol = newSymbol.createSimple(map3)
        tidalLayer = tidalSymbol.symbolLayer(0)
        # create a new symbol layer for the delete symbol (i.e. a red cross)
        map4 = {"name": "cross", "color": "255,0,0,255", "offset": "0,0",
               "color_border": "255,0,0,255", "size": "7.0", "angle": "45.0"}
        deleteSymbol = newSymbol.createSimple(map4)
        deleteLayer = deleteSymbol.symbolLayer(0)
        # create a new symbol layer for the altered symbol (i.e. a red triangle)
        map5 = {"name": "equilateral_triangle", "color": "0,0,0,0", "offset": "0,0",
               "color_border": "255,0,0,255", "size": "7.0", "angle": "DEFAULT_SIMPLEMARKER_ANGLE"}
        alteredSymbol = newSymbol.createSimple(map5)
        alteredLayer = alteredSymbol.symbolLayer(0)
        # rule that makes dam symbol a rectangle
        rule1 = rendererV2.Rule(damSymbol, 0, 0, "dam_id!=''")
        rendererV2.addRule(rule1)
        # rule that makes terrestrial crossing structures a diamond
        rule2 = rendererV2.Rule(terrSymbol, 0, 0, "wildlf_id!=''")
        rendererV2.addRule(rule2)
        # rule that makes tidal restrictions a star
        rule3 = rendererV2.Rule(tidalSymbol, 0, 0, "restr_id!=''")
        rendererV2.addRule(rule3)
        # make the rule, using the delete symbol, and add it
        rule4 = rendererV2.Rule(deleteSymbol, 0, 0,
            "c_deleted='y' or d_deleted='y' or w_deleted='y' or r_deleted='y'")
        rendererV2.addRule(rule4)
        # rule for altered symbol
        rule5 = rendererV2.Rule(alteredSymbol, 0, 0,
            "c_altered = 'y' or d_altered = 'y' or w_altered = 'y' or r_altered = 'y'")
        rendererV2.addRule(rule5)
        # associate the new renderer with the activeVLayer
        vlayer.setRendererV2(rendererV2)
        # The coloredLayers dictionary is set when a saved scenario is opened, in Tools.shared.updateExtents()
        # when reopening the editing layer after editing, in which case the rule renderer not set.
        # If the user had set a color other than the default color red, we reset it here.
        retval = self.legend.mainwindow.coloredLayers.get(vlayerName)
        # color set by user (either in scenario file or in this session) and being opened by updateExtents() or copyScenario
        if retval and retval != red:
            symbols = rendererV2.symbols()
            print  "Main.legend.LegendItem.setRendererV2(): There is a layer color" + str(retval.getRgb())
            symbols[0].setColor(retval)
            symbols[1].setColor(retval)
            symbols[2].setColor(retval)
            symbols[3].setColor(retval)
        # This is the case where updateExtents or copyScenario is opening editing layers that are in coloredLayers with default red
        # color. The layer was opened with a some unknown QGIS color but we reset the layer's color to red above, so pass.
        elif retval and retval == red: # for code clarity
            pass # color set above as default color
        # layer newly created with default colors so add the layer to the coloredLayers dictionary
        elif not retval: self.addLayerToColoredLayers()
        else: print "Main.legend.LegendItem.setRendererV2(): There is a 'retval' error"
        # color the preview icon
        #self.legend.currentItem().vectorLayerSymbology(vlayer)
        vlayer.triggerRepaint()
        # debugging
        #print "The delete layers name is: " + deleteLayer.name()
        print "Main.legend.LegendItem.setRendererV2(): The number of symbols is: " + str(len(rendererV2.symbols()))
        print "Main.legend.LegendItem.setRendererV2(): The number of rules is: " + str(rendererV2.ruleCount())
        print "Main.legend.LegendItem.setRendererV2(): The symbolLayer properties are: "
        for k, v in symbolLayer.properties().iteritems():
            print "%s: %s" % (k, v)
        print "Main.legend.LegendItem.setRendererV2(): The damLayer properties are: "
        for k, v in damLayer.properties().iteritems():
            print "%s: %s" % (k, v)
        print "Main.legend.LegendItem.setRendererV2(): The terrLayer properties are: "
        for k, v in terrLayer.properties().iteritems():
            print "%s: %s" % (k, v)
        print "Main.legend.LegendItem.setRendererV2(): The tidalLayer properties are: "
        for k, v in tidalLayer.properties().iteritems():
            print "%s: %s" % (k, v)
        print "Main.legend.LegendItem.setRendererV2(): The deleteLayer properties are: "
        for k, v in deleteLayer.properties().iteritems():
            print "%s: %s" % (k, v)
        print "Main.legend.LegendItem.setRendererV2(): The alteredLayer properties are: "
        for k, v in alteredLayer.properties().iteritems():
            print "%s: %s" % (k, v)
        print "Main.legend.LegendItem.setRendererV2(): The damLayer properties are: "
        for k, v in damLayer.properties().iteritems():
            print "%s: %s" % (k, v)
def Main.legend.LegendItem.setPolygonColor (self, vlayer, red, vlayerName)
Definition at line 430 of file legend.py.
References Main.legend.LegendItem.addLayerToColoredLayers().
Referenced by Main.legend.LegendItem.setRendererV2().
    def setPolygonColor(self, vlayer, red, vlayerName):
        # debugging
        print "Main.legend.LegendItem.setPolygonColor()"
        # This dictionary (coloredLayers) is set when a saved scenario is opened, when an editing layer is created
        # (in dlgscenarioedittypes) or in Tools.shared.updateExtents() when reopening the editing layer after editing.
        # If the user had set a color other than the default,we reset it here.
        symbolLayer = vlayer.rendererV2().symbols()[0].symbolLayer(0)
        retval = self.legend.mainwindow.coloredLayers.get(vlayerName)
        if retval and retval != red: # being opened by updateExtents or copyScenario and user has set color
            print "Main.legend.LegendItem.setRendererV2(): THERE IS A POLYGON COLOR"
            symbolLayer.setColor(retval)
            return
        # being opened by updateExtents or copyScenario with some unknown QGIS color so we reset to red here
        elif retval and retval == red: # being opened by copyScenario
            symbolLayer.setColor(retval)
        else: # if the layer being loaded into the scenario for the first time default to red
            symbolLayer.setColor(red)
            self.addLayerToColoredLayers()
        vlayer.triggerRepaint()
def Main.legend.LegendItem.setRendererV2 (self, vlayer)
Definition at line 197 of file legend.py.
References Main.legend.LegendItem.setBaseTownsProperties(), Main.legend.LegendItem.setLineColorAndWidth(), Main.legend.LegendItem.setPointsRuleRendererV2(), and Main.legend.LegendItem.setPolygonColor().
    def setRendererV2(self, vlayer):
        # debugging
        print "Main.legend.LegendItem.setRendererV2()"
        print "Main.legend.LegendItem.setRendererV2(): vlayer geometry is :" + str(vlayer.geometryType())
        red = QtGui.QColor(255, 0, 0, 255)
        vlayerName = unicode(vlayer.name())
        if vlayerName == config.editLayersBaseNames[0]: # edit_scenario(points) layer
            print "Main.legend.LegendItem.setRendererV2(): Setting Rule Based Renderer for 'edit_scenario(points).shp"
            '''
                We are opening 'edit_scenario(points)' for the first time.  Either it has been reopened by
                Tools.shared.updateExtents(), Main.mainwindow.copyScenario() or it has been newly written by
                Main.mainwindow.dlgscenarioedittypes.
            '''
            self.setPointsRuleRendererV2(vlayer, red, vlayerName) # sets up the rule renderer for edit_scenario(points)
        elif vlayerName == config.editLayersBaseNames[1]: # edit_scenario(lines).shp
            print "Main.legend.LegendItem.setRendererV2(): Setting color and line width for edit_scenario(lines).shp"
            '''
                We are opening 'edit_scenario(lines)' for the first time.  Either it has been reopened by
                Tools.shared.updateExtents(), Main.mainwindow.copyScenario() or it has been newly written by
                Main.mainwindow.dlgscenarioedittypes.
            '''
            self.setLineColorAndWidth(vlayer, red, vlayerName) # sets color and width for edit_scenario(lines)
        elif vlayerName == config.editLayersBaseNames[2]: # edit_scenario(polygons).shp
            print "Main.legend.LegendItem.setRendererV2(): Setting color for edit_scenario(polygons).shp"
            '''
                We are opening 'edit_scenario(polygons)' for the first time.  Either it has been reopened by
                Tools.shared.updateExtents(), Main.mainwindow.copyScenario() or it has been newly written by
                Main.mainwindow.dlgscenarioedittypes.
            '''
            self.setPolygonColor(vlayer, red, vlayerName) # sets color for edit_scenario Polygons
        elif vlayerName == config.orientingLayersChecked[0]: # the base_towns layer
            print "Main.legend.LegendItem.setRendererV2(): This is the base_towns layer"
            # The user could be opening this layer with 'Add Vector' or the app could be opening orienting layers
            self.setBaseTownsProperties(vlayer) # sets this layer to transparent with black borders
        elif vlayer.geometryType() == 1: # set line width for all line layers
            # debugging
            print "Main.legend.LegendItem.setRendererV2(): geometry = 1"
            symbolLayer = vlayer.rendererV2().symbols()[0].symbolLayer(0)
            print "Main.legend.LegendItem.setRendererV2(): The line width before setting is: " + str(symbolLayer.width())
            symbolLayer.setWidth(0.4)
            print "Main.legend.LegendItem.setRendererV2(): The line width after setting is: " + str(symbolLayer.width())
            vlayer.triggerRepaint()
        # debugging
        if vlayer.isUsingRendererV2():
            rendererV2 = vlayer.rendererV2()
            symbols = rendererV2.symbols()
            # only 1 symbol in symbols and only one layer
            symbol = symbols[0]
            symbolLayer = symbol.symbolLayer(0)
            print "Main.legend.LegendItem.setRendererV2(): rendererV2.dump is:" + rendererV2.dump()
            print "Main.legend.LegendItem.setRendererV2(): The layer properties are: "
            for k, v in symbolLayer.properties().iteritems():
                print "%s: %s" % (k, v)
            print "Main.legend.LegendItem.setRendererV2(): The number of symbols is: " + str(len(symbols))
            print "Main.legend.LegendItem.setRendererV2(): The number of layers in symbols[0] is: " + str(symbol.symbolLayerCount())
            print "Main.legend.LegendItem.setRendererV2(): The layer type is: " + str(symbolLayer.layerType())
def Main.legend.LegendItem.storeAppearanceSettings (self)
Store the appearance of the layer item
Definition at line 162 of file legend.py.
References Main.legend.LegendItem.__itemIsExpanded.
    def storeAppearanceSettings(self):
        """ Store the appearance of the layer item """
        self.__itemIsExpanded = self.isExpanded()
def Main.legend.LegendItem.vectorLayerSymbology (self, vlayer)
Set the child icon that shows layer color
Definition at line 170 of file legend.py.
References Main.legend.LegendItem.changeSymbologySettings().
    def vectorLayerSymbology(self, vlayer):
        ''' Set the child icon that shows layer color '''
        rendererV2 = vlayer.rendererV2()
        symbol = rendererV2.symbols()[0]
        # a QImage object
        image = symbol.bigSymbolPreviewImage()
        pixmap = QtGui.QPixmap(100, 100)
        pixmap = pixmap.fromImage(image)
        self.changeSymbologySettings(vlayer, pixmap)
Member Data Documentation
Main::legend.LegendItem::__itemIsExpanded [private]
Definition at line 162 of file legend.py.
Referenced by Main.legend.LegendItem::restoreAppearanceSettings(), and Main.legend.LegendItem::storeAppearanceSettings().
Main::legend.LegendItem::canvasLayer
Definition at line 50 of file legend.py.
Main::legend.LegendItem::child
Definition at line 58 of file legend.py.
Referenced by Main.legend.LegendItem.changeSymbologySettings().
Main::legend.LegendItem::isVect
Definition at line 50 of file legend.py.
Main::legend.LegendItem::layerId
Definition at line 50 of file legend.py.
Main::legend.LegendItem::layerName
Definition at line 50 of file legend.py.
Referenced by Main.legend.LegendItem.addLayerToColoredLayers().
Main::legend.LegendItem::legend
Definition at line 50 of file legend.py.
Referenced by Main.legend.LegendItem::addLayerToColoredLayers(), Main.mainwindow.MainWindow::arrangeOrientingLayers(), and Main.mainwindow.MainWindow::copyScenario().
Main::legend.LegendItem::openingScenario
Definition at line 50 of file legend.py.
Referenced by Main.mainwindow.MainWindow.openScenario(), and Main.mainwindow.MainWindow.setInitialAppState().
The documentation for this class was generated from the following file:
C:/egit_repositories/CAPS-Scenario-Builder/CAPS_Scenario_Builder/src/Main/legend.py