Caps Scenario Builder: Main.mainwindow.MainWindow Class Reference
Main.mainwindow.MainWindow Class Reference
Public Member Functions
def __init__
def activeLayerChanged
def addLines
def addPoints
def addPolygons
def addRasterLayer
def addVectorLayer
def appStateChanged
def arrangeOrientingLayers
def checkBaseLayerMatch
def checkEditFeatureMatch
def checkEditsState
def checkFieldNameMatch
def checkForDeletions
def checkLayerLoadError
def checkPastedFeatureConstraints
def checkScenarioDirectoryPath
def checkScenarioState
def closeEvent
def copyFeatures
def copyFeaturesShared
def copyScenario
def deleteExportScenarioFile
def deleteFeatures
def deleteOldCsvShapefile
def deleteTempShapefile
def deselectFeatures
def disableEditActions
def disableSelectActions
def displayCopiedFeatInfo
def editScenario
def enablePointsOrLinesOrPolygons
def enableSelectSubActions
def exportScenario
def getAttsForPastedOrModifiedFeats
def getCurrentLayers
def getCurrentLayersCount
def getCurrentLayersNames
def getEditFields
def getEditLayerToExport
def getGeometryName
def getLayerFromName
def getOriginalScenarioLayers
def getOriginalScenarioLayersNames
def identifyFeatures
def isAlteredFeature
def listScenarioEditFiles
def makeScenarioDirectory
def manageProjects
def modifyEditLayerFeatures
def modifyFeatures
def newScenario
def openHiddenVectorLayer
def openModifyInfoWindow
def openOrientingLayers
def openRasterCategoryTable
def openRasterLayer
def openScenario
def openVectorAttributeTable
def openVectorLayer
def pan
def pasteBaseLayerDeletions
def pasteEmptyFeatures
def pasteFeatures
def pasteModifiedBaseLayerFeats
def printFeatures
def printFields
def retranslateUi
def roundGeometryValues
def saveEdits
def saveScenario
def saveScenarioAs
def selectFeatures
def setBaseLayerActive
def setExtents
def setInitialAppState
def setPasteModifyDone
def setPasteModifySuccess
def setPastingExtent
def setScenarioDirty
def setScenarioSaved
def setSelectionColor
def setupUi
def sftpProperties
def writeCsvExportFile
def writeCsvShapefile
def zoomIn
def zoomOut
def zoomToMapExtent
Public Attributes
activeRLayer
activeVLayer
attrTable
browserRaster
canvas
centralwidget
coloredLayers
copiedFeatCount
copiedFeatGeom
copiedFeats
copyFlag
copyLayer
crs
currentLayers
currentLayersCount
defaultColors
dlgAddAtts
dlgDisplayIdentify
dlgManageProjects
dlgScenarioEditTypes
dlgSftpProperties
dwAttrTable
dwRasterTable
editDirty
editLayerName
editMode
editTypeLabel
geom
gridlayout
layerColor
layerType
legend
legendDock
mapcoords
mapRenderer
mapToolGroup
menubar
menuEdit
menuLayer
menuProject
menuScenario
menuView
modifyFlag
mpActionAddLines
mpActionAddPoints
mpActionAddPolygons
mpActionAddRasterLayer
mpActionAddVectorLayer
mpActionAppExit
mpActionCopyFeatures
mpActionDeleteFeatures
mpActionDeselectFeatures
mpActionEditScenario
mpActionExportScenario
mpActionIdentifyFeatures
mpActionManageProjects
mpActionModifyPoints
mpActionNewScenario
mpActionOpenRasterCategoryTable
mpActionOpenScenario
mpActionOpenVectorAttributeTable
mpActionPan
mpActionPasteFeatures
mpActionSaveEdits
mpActionSaveScenario
mpActionSaveScenarioAs
mpActionSelectFeatures
mpActionSftpProperties
mpActionZoomIn
mpActionZoomOut
mpActionZoomtoMapExtent
msgFlag
openingOrientingLayers
openingScenario
originalEditLayerFeats
originalScenarioLayers
originalScenarioLayersNames
origScenarioLyrsLoaded
provider
rectExtentMA
reply
scenarioDirty
scenarioEditType
scenarioFileName
scenarioFilePath
scenarioInfo
sftpHost
sftpPassword
sftpPath
sftpUser
splash
statusBar
tempOriginalEditFeats
textBrowserModifyInfo
toolAddLinesPolygons
toolAddPoints
toolBar
toolIdentify
toolPan
toolSelect
toolZoomIn
toolZoomOut
windModifyInfo
Detailed Description
Display the main window and manage all user actions
Definition at line 62 of file mainwindow.py.
Constructor & Destructor Documentation
def Main.mainwindow.MainWindow.__init__ (self, splash)
Definition at line 64 of file mainwindow.py.
    def __init__(self, splash):
        QtGui.QMainWindow.__init__(self)
        # add the Qt4 designer code elements to the MainWindow
        self.setupUi(self)
        # get the splash screen
        self.splash = splash
        ''' Set instance variables '''
        # LISTS AND DICTIONARIES
        self.originalScenarioLayers = []
        self.currentLayers = []
        self.copiedFeats = []
        self.originalEditLayerFeats = []
        self.originalScenarioLayersNames = []
        self.coloredLayers = {}
        self.defaultColors = config.setDefaultColors() # a list of QColors
        # FLAGS
        self.scenarioDirty = False
        self.origScenarioLyrsLoaded = False
        self.copyFlag = False # True if selections copied
        self.editDirty = False # True if edits unsaved, false if no unsaved edits
        self.editMode = False # True if "Toggle Edits" is activated
        self.openingOrientingLayers = False
        self.openingScenario = False
        # OBJECTS
        self.attrTable = None
        self.dwAttrTable = None
        self.dwRasterTable = None
        self.scenarioInfo = None
        self.dlgDisplayIdentify = None
        self.dlgScenarioEditTypes = None
        self.windModifyInfo = None
        # MA State Plane coordinate system used by MassGIS (a QgsCoordinateReferenceSystem())
        self.crs = config.setCrs()
        # The rough extents of Massachusetts (a QgsRectangle)
        self.rectExtentMA = config.setExtentMA()
        # this variable is updated by self.activeLayerChanged
        self.activeVLayer = None
        self.activeRLayer = None
        self.provider = None
        #set tool variables
        self.toolSelect = None
        self.toolAddPoints = None
        self.toolAddLinesPolygons = None
        self.editTypeLabel = None
        # VALUES
        self.scenarioFilePath = None
        self.scenarioFileName = None
        self.scenarioEditType = None
        self.currentLayersCount = None
        self.layerType = None
        # geometry of the activeVLayer
        self.geom = None #0 point, 1 line, 2 polygon
        # This saves an editing layer's color so that it gets refreshed
        # when the layer loads after updating extents (see shared.updateExtents
        self.layerColor = None
        self.editLayerName = None
        ''' Store persistent application settings. '''
        settings = QtCore.QSettings()
        self.sftpHost = unicode(settings.value("sftpHost", "jamba.provost.ads.umass.edu").toString())
        self.sftpUser = unicode(settings.value("sftpUser",  "provost\\ambystoma").toString())
        self.sftpPassword = unicode(settings.value("sftpPassword", '').toString())
        self.sftpPath = unicode(settings.value("sftpPath", "/public/csb/").toString())
        print "Main.mainwindow self.sftpHost is: ", self.sftpHost
        ''' Begin construction of main window '''
        # create the map canvas
        self.canvas = QgsMapCanvas()
        self.canvas.setCanvasColor(QtGui.QColor(255,255,255))
        self.canvas.enableAntiAliasing(True)
        self.canvas.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridlayout.addWidget(self.canvas)
        self.mapRenderer = self.canvas.mapRenderer()
        # False disables "on the fly" projections; True enables them
        self.mapRenderer.setProjectionsEnabled(False)
        # sets the project crs
        self.mapRenderer.setDestinationCrs(self.crs)
        # set the QDockWidget that holds the legend
        self.legendDock = QtGui.QDockWidget("Layers", self)
        self.legendDock.setObjectName("legend")
        self.legendDock.setStyleSheet("background-color: white")
        # without "NoDockWidgetFeatures, the user could close the legend with no way to reopen it
        self.legendDock.setFeatures(self.legendDock.NoDockWidgetFeatures)
        self.legendDock.setContentsMargins (1, 1, 1, 1)
        # create the legend from legend.py
        self.legend = Legend(self)
        self.legend.setObjectName("theMapLegend")
        # add the legend to the dock widget
        self.legendDock.setWidget(self.legend)
        # add the dock widget to the main window and show it
        self.addDockWidget(QtCore.Qt.LeftDockWidgetArea, self.legendDock)
        self.legendDock.show()
        # now that we have self.legend, get active layer changed signal
        # connect the Python 'short circuit' signal from legend.py to the handler slot
        self.connect( self.legend, QtCore.SIGNAL("activeLayerChanged"), self.activeLayerChanged)
        # Create the actions and link to their behaviors.
        # pasted from mainwindow_ui.py and then change MainWindow.* to self.*
        QtCore.QObject.connect(self.mpActionNewScenario, QtCore.SIGNAL("triggered()"), self.newScenario)
        QtCore.QObject.connect(self.mpActionSaveScenario, QtCore.SIGNAL("triggered()"), self.saveScenario)
        QtCore.QObject.connect(self.mpActionOpenScenario, QtCore.SIGNAL("triggered()"), self.openScenario)
        QtCore.QObject.connect(self.mpActionSaveScenarioAs, QtCore.SIGNAL("triggered()"), self.saveScenarioAs)
        QtCore.QObject.connect(self.mpActionExportScenario, QtCore.SIGNAL("triggered()"), self.exportScenario)
        QtCore.QObject.connect(self.mpActionSelectFeatures, QtCore.SIGNAL("toggled(bool)"), self.selectFeatures)
        QtCore.QObject.connect(self.mpActionDeselectFeatures, QtCore.SIGNAL("triggered()"), self.deselectFeatures)
        QtCore.QObject.connect(self.mpActionCopyFeatures, QtCore.SIGNAL("triggered()"), self.copyFeatures)
        QtCore.QObject.connect(self.mpActionDeleteFeatures, QtCore.SIGNAL("triggered()"), self.deleteFeatures)
        QtCore.QObject.connect(self.mpActionPasteFeatures, QtCore.SIGNAL("triggered()"), self.pasteFeatures)
        QtCore.QObject.connect(self.mpActionAddPoints, QtCore.SIGNAL("toggled(bool)"), self.addPoints)
        QtCore.QObject.connect(self.mpActionAddLines, QtCore.SIGNAL("toggled(bool)"), self.addLines)
        QtCore.QObject.connect(self.mpActionAddPolygons, QtCore.SIGNAL("toggled(bool)"), self.addPolygons)
        QtCore.QObject.connect(self.mpActionZoomIn, QtCore.SIGNAL("toggled(bool)"), self.zoomIn)
        QtCore.QObject.connect(self.mpActionZoomOut, QtCore.SIGNAL("toggled(bool)"), self.zoomOut)
        QtCore.QObject.connect(self.mpActionZoomtoMapExtent, QtCore.SIGNAL("triggered()"), self.zoomToMapExtent)
        QtCore.QObject.connect(self.mpActionAddVectorLayer, QtCore.SIGNAL("triggered()"), self.addVectorLayer)
        QtCore.QObject.connect(self.mpActionAddRasterLayer, QtCore.SIGNAL("triggered()"), self.addRasterLayer)
        QtCore.QObject.connect(self.mpActionOpenRasterCategoryTable, QtCore.SIGNAL("triggered()"), self.openRasterCategoryTable)
        QtCore.QObject.connect(self.mpActionOpenVectorAttributeTable, QtCore.SIGNAL("triggered()"), self.openVectorAttributeTable)
        QtCore.QObject.connect(self.mpActionEditScenario, QtCore.SIGNAL("toggled(bool)"), self.editScenario)
        QtCore.QObject.connect(self.mpActionSaveEdits, QtCore.SIGNAL("triggered()"), self.saveEdits)
        QtCore.QObject.connect(self.mpActionPan, QtCore.SIGNAL("toggled(bool)"), self.pan)
        QtCore.QObject.connect(self.mpActionAppExit, QtCore.SIGNAL("triggered()"), self.close)
        QtCore.QObject.connect(self.mpActionIdentifyFeatures, QtCore.SIGNAL("toggled(bool)"), self.identifyFeatures)
        QtCore.QObject.connect(QgsProject.instance(), QtCore.SIGNAL("layerLoaded(int, int)"), self.getOriginalScenarioLayers)
        QtCore.QObject.connect(self.mpActionModifyPoints, QtCore.SIGNAL("triggered()"), self.modifyFeatures)
        QtCore.QObject.connect(self.mpActionManageProjects, QtCore.SIGNAL("triggered()"), self.manageProjects)
        QtCore.QObject.connect(self.mpActionSftpProperties, QtCore.SIGNAL("triggered()"), self.sftpProperties)
        # Instantiate all tools.  They are written so their variables update from
        # the main window, so there is no need to repeat the instantiation process
        # when layers or other variables change.
        self.toolPan = QgsMapToolPan(self.canvas)
        self.toolZoomIn = QgsMapToolZoom(self.canvas, False) # false = in
        self.toolZoomOut = QgsMapToolZoom(self.canvas, True) # true = out
        self.toolIdentify = Identify(self)
        self.toolSelect = SelectTool(self)
        self.toolAddPoints = AddPoints(self)
        self.toolAddLinesPolygons = AddLinesPolygons(self)
        # Create a QActionGroup to manage map tool actions states.
        # If an action is set as "checkable" in mainwindow_ui.py and
        # the action is in a tool group, only one action in the
        # group can be active at a time. All other buttons
        # are deactivated.  A toolGroup also makes it possible to
        # easily set all actions in the group as enabled or disabled.
        self.mapToolGroup = QtGui.QActionGroup(self) # 8 actions of 26 total
        # The four actions below are usually disabled
        self.mapToolGroup.addAction(self.mpActionSelectFeatures)
        self.mapToolGroup.addAction(self.mpActionAddPoints)
        self.mapToolGroup.addAction(self.mpActionAddLines)
        self.mapToolGroup.addAction(self.mpActionAddPolygons)
        # The four actions below are always enabled when a layer is loaded
        self.mapToolGroup.addAction(self.mpActionIdentifyFeatures)
        self.mapToolGroup.addAction(self.mpActionPan)
        self.mapToolGroup.addAction(self.mpActionZoomIn)
        self.mapToolGroup.addAction(self.mpActionZoomOut)
        # The following actions are usually disabled (8 actions of 26 total)
        self.mpActionDeselectFeatures.setDisabled(True)
        self.mpActionModifyPoints.setDisabled(True)
        self.mpActionDeleteFeatures.setDisabled(True)
        self.mpActionCopyFeatures.setDisabled(True)
        self.mpActionPasteFeatures.setDisabled(True)
        self.mpActionSaveEdits.setDisabled(True)
        self.mpActionExportScenario.setDisabled(True)
        self.mpActionOpenVectorAttributeTable.setDisabled(True)
        # Set initial action states; all disabled except ten actions are always enabled (by default).
        # New Scenario, Open Scenario, Save Scenario, Save Scenario As, Edit Scenario
        # Add Vector, Add Raster and Open Raster Category Table, Exit and Zoom to Map Extent are on
        self.mapToolGroup.setDisabled(True)
        # close splash screen
        time.sleep(2)
        self.splash.hide()
        '''# make sure the mainwindow paints properly
        self.menubar.show()
        self.toolBar.show()
        self.statusBar.show()
        self.setVisible(True)
        self.update()
        self.activateWindow()'''
        # if the mainwindow is not maximized on opening we get painting problems
        # on all versions of MS Windows
        self.showMaximized()
        # set the map coordinates display in the status bar
        self.mapcoords = MapCoords(self)
        # load the orienting layers
        self.openOrientingLayers()
        # The V2 renderers get the selection color from the old renderer.
        # This sets the selection color once, when the app starts
        self.setSelectionColor()
Member Function Documentation
def Main.mainwindow.MainWindow.activeLayerChanged (self, layerType)
    A controller for handling app state changes originating from the legend.
    This method is called whenever the "current item" in the legend has changed,
    and its major task is to enable or disable actions in the GUI.
Debugging Code
Definition at line 2449 of file mainwindow.py.
References Main.mainwindow.MainWindow.activeRLayer, Main.mainwindow.MainWindow.activeVLayer, Main.mainwindow.MainWindow.attrTable, Main.mainwindow.MainWindow.copyFlag, Main.mainwindow.MainWindow.crs, Main.mainwindow.MainWindow.disableEditActions(), Main.mainwindow.MainWindow.disableSelectActions(), Main.mainwindow.MainWindow.editDirty, Main.mainwindow.MainWindow.editMode, Main.mainwindow.MainWindow.enablePointsOrLinesOrPolygons(), Main.mainwindow.MainWindow.enableSelectSubActions(), Main.mainwindow.MainWindow.geom, Main.mainwindow.MainWindow.getCurrentLayers(), snippets.layer, Main.mainwindow.MainWindow.layerType, Main.mainwindow.MainWindow.openingOrientingLayers, Main.mainwindow.MainWindow.openVectorAttributeTable(), Main.mainwindow.MainWindow.originalScenarioLayers, Main.mainwindow.MainWindow.provider, Main.mainwindow.MainWindow.scenarioDirty, Main.mainwindow.MainWindow.scenarioEditType, Main.mainwindow.MainWindow.scenarioFilePath, and Main.mainwindow.MainWindow.setExtents().
    def activeLayerChanged(self, layerType):
        '''
            A controller for handling app state changes originating from the legend.
            This method is called whenever the "current item" in the legend has changed,
            and its major task is to enable or disable actions in the GUI.
        '''
        #**************************************************************************
        ''' Debugging Code '''
        print "MAIN.MAINWINDOW.ALC() STARTING"
        print "alc layer type is " + str(layerType)
        if not self.activeVLayer: print "alc no active vlayer"
        else: print "alc old active vlayer " + self.activeVLayer.name()
        if self.activeRLayer == None: print "alc no active rlayer"
        else: print "alc old active rlayer " + self.activeRLayer.name()
        print "alc self.editMode is " + str(self.editMode)
        print "alc self.editDirty is " + str(self.editDirty)
        print "alc self.scenarioDirty is " + str(self.scenarioDirty)
        print "alc Crs Transform is enabled? " + str(self.canvas.hasCrsTransformEnabled())
        print "alc The destination crs description is " + str(self.canvas.mapRenderer().destinationCrs().description())
        print "alc The destination authority identifier is " + str(self.canvas.mapRenderer().destinationCrs().authid())
        print "alc self.openingOrientingLayers is " + str(self.openingOrientingLayers)
        #**************************************************************************
        # keep track of the active layer type for use in other methods
        # LayerType can be none if all layers are removed from the legend.
        self.layerType = layerType # 0 = vector; 1 = raster
        # Set active layer variables to none because we will either configure
        # a new active layer, or there are no layers open in the legend.
        self.activeVLayer = None
        self.activeRLayer = None
        ''' Set app state for the new active layer '''
        # layerType is the QgsMapLayer type
        if layerType == 1: # raster
            # set active raster layer
            self.activeRLayer = self.legend.activeLayer().layer()
            # debugging
            print "alc The layer's authority id is " + str(self.activeRLayer.crs().authid())
            print "alc The description of the layer crs is " + str(self.activeRLayer.crs().description())
            print "ALC THE ACTIVE RLAYER NAME IS " + self.activeRLayer.name()
            # For some reason, the USGS.sid will not render unless we include this line of code.
            # The USGS.sid layer reports that it is in geographic coordinates WGS 84.
            self.activeRLayer.setCrs(self.crs)
            # set extents
            self.setExtents()
            # set the layer geometry
            self.geom = None
            self.provider = None
            '''
                A new raster layer has been selected or opened so set action states.
            '''
            # Since we are loading a layer, enable the navigation map tools
            self.mapToolGroup.setDisabled(False)
            # Disable (gray out) select tool actions if raster layer loaded.
            # Note that this tool is disabled in mainwindow.init() but enabled
            # whenever a vector layer is loaded while editing a scenario.
            self.mpActionSelectFeatures.setDisabled(True)
            # This disables 4 usuallyDisabledToolGroup actions that may have been enabled
            # when a vector layer was active while editing a scenario.
            self.disableSelectActions()
            # can't paste features to a raster so disable paste action
            self.mpActionPasteFeatures.setDisabled(True)
            # disable edit actions since we can't edit a raster
            self.disableEditActions()
            # if self.editsDirty enable save edits
            if self.editDirty: self.mpActionSaveEdits.setDisabled(False)
            # Disable the vector attribute table action, which may have been
            # enabled by loading a vector layer.
            self.mpActionOpenVectorAttributeTable.setDisabled(True)
            # There could be something to export if a scenario is open so enable Export Scenario
            # A user could open a scenario that has edits to editing layers and export it.
            if self.scenarioFilePath:
                self.mpActionExportScenario.setDisabled(False)
            # debugging
            print "alc self.scenarioDirty end is " + str(self.scenarioDirty)
            print "alc originalScenarioLayers are "
            for layer in self.originalScenarioLayers: print layer.name()
            print "alc currentLayers are "
            for layer in self.getCurrentLayers().values(): print layer.name()
        elif layerType == 0: #vector
            # debugging
            print "alc Setting app state for vector layer"
            print "alc copyFlag is " + str(self.copyFlag)
            # set the active vector layer instance variable
            self.activeVLayer = self.legend.activeLayer().layer()
            # set the data provider
            self.provider = self.activeVLayer.dataProvider()
            # set the geometry of the layer
            self.geom = self.activeVLayer.geometryType() #0 point, 1 line, 2 polygon
            # set extents if not within MA state extents
            self.setExtents()
            # debugging
            print "ALC THE ACTIVE VLAYER NAME IS " + self.activeVLayer.name()
            print "alc The layers authid is " + str(self.activeVLayer.crs().authid())
            print "alc The description of the srs is " + str(self.activeVLayer.crs().description())
            print "alc The activeVLayer is using renderer V2: " + str(self.activeVLayer.isUsingRendererV2())
            print "alc The activeVLayer renderer type is " + self.activeVLayer.rendererV2().type()
            # refresh attribute table if open
            if self.attrTable != None and self.attrTable.isVisible():
                self.openVectorAttributeTable()
            '''
            A New Vector layer has been selected or opened, so set action states.
            '''
            # Enable map navigation tools
            self.mapToolGroup.setDisabled(False) # map tools can't be enabled if the group is off
            # We are changing the activeVLayer, so we need to handle editMode
            if self.editMode: # handle select actions first
                self.mpActionSelectFeatures.setDisabled(False) # select always enabled in edit mode
                if self.mpActionSelectFeatures.isChecked():
                    # The user has checked Select Features, so leave select features activated.
                    # Also activate the select sub actions.
                    # Note that "Modify Selected" will only be enabled if the active layer
                    # is one of the point base layers
                    self.enableSelectSubActions() # enable deselect, modify, delete and copy features
                elif len(self.activeVLayer.selectedFeatures()) != 0:
                    # We have selected features, so enable all the selected features actions
                    # Note that "Modify Selected" will only be enabled if the active layer
                    # is an editable point base layer or an editing layer.
                    self.mpActionSelectFeatures.setChecked(True)
                    self.enableSelectSubActions()
            else:
                # Select tool only enabled if in editMode
                self.mpActionSelectFeatures.setDisabled(True)
                self.disableSelectActions()
            # This could be combined with the above, but for clarity, keep separate.
            if self.editMode: # now handle enabling add points, lines or polygons
                # loading a new active layer so enable the proper edit action if an editing layer
                if unicode(self.activeVLayer.name()) in config.editLayersBaseNames: # so is an editing layer
                    # But is the editing layer the correct layer for the scenario edit type?
                    currentLayerName = unicode(self.activeVLayer.name())
                    if shared.checkSelectedLayer(self, self.scenarioEditType, currentLayerName, False):
                        # So the editing tool will ONLY be enabled if the editing layer is the correct
                        # layer for the current scenario edit type.
                        self.enablePointsOrLinesOrPolygons()
                    else: # so is an editing layer but not the right one for the scenario edit type
                        self.disableEditActions() # disable add points, lines, polygons
                else: # we are in edit mode and a non-editing vector layer has been selected
                    self.disableEditActions()
            else: # not in edit mode
                # to be safe, but this should have already been called by the editScenario action
                self.disableEditActions()
            # handle the paste action
            if self.copyFlag and self.editMode:
                self.mpActionPasteFeatures.setDisabled(False)
            else: self.mpActionPasteFeatures.setDisabled(True)
            # if self.editDirty is False, the save edits action should be disabled
            if self.editDirty:
                self.mpActionSaveEdits.setDisabled(False)
            else:
                self.mpActionSaveEdits.setDisabled(True)
            # enable the  "Open Vector Attribute Table" action
            self.mpActionOpenVectorAttributeTable.setDisabled(False)
            # There could be something to export if a scenario is open so enable Export Scenario
            # A user could open a scenario that has edits to editing layers and export it.
            if  self.scenarioFilePath:
                self.mpActionExportScenario.setDisabled(False)
            # debugging
            print "alc self.scenarioDirty end is " + str(self.scenarioDirty)
            print "alc originalScenarioLayers are "
            for layer in self.originalScenarioLayers: print layer.name()
            print "alc currentLayers are "
            for layer in self.getCurrentLayers().values(): print layer.name()
        # debugging
        else: print "alc Geometry type unknown"
def Main.mainwindow.MainWindow.addLines (self, state)
Edit menu SLOT that activates/deactivates the add lines tool
Definition at line 1520 of file mainwindow.py.
References Main.mainwindow.MainWindow.toolAddLinesPolygons.
Referenced by Main.mainwindow.MainWindow.addPolygons().
    def addLines(self, state):
        ''' Edit menu SLOT that activates/deactivates the add lines tool'''
        # debugging
        print "Main.mainwindow.addLines()"
        if state: self.canvas.setMapTool(self.toolAddLinesPolygons)
        else:  self.canvas.unsetMapTool(self.toolAddLinesPolygons)
def Main.mainwindow.MainWindow.addPoints (self, state)
Edit menu SLOT that activates/deactivates the add points tool
Definition at line 1512 of file mainwindow.py.
References Main.mainwindow.MainWindow.toolAddPoints.
    def addPoints(self, state):
        ''' Edit menu SLOT that activates/deactivates the add points tool'''
        # debugging
        print "Main.mainwindow.addPoints() " + str(state)
        if state: self.canvas.setMapTool(self.toolAddPoints)
        else: self.canvas.unsetMapTool(self.toolAddPoints)
def Main.mainwindow.MainWindow.addPolygons (self, state)
Edit menu SLOT that activates/deactivates the add polygons tool
Definition at line 1527 of file mainwindow.py.
References Main.mainwindow.MainWindow.addLines().
    def addPolygons(self, state):
        ''' Edit menu SLOT that activates/deactivates the add polygons tool'''
        # debugging
        print "Main.mainwindow.addPolygons()"
        self.addLines(state)
def Main.mainwindow.MainWindow.addRasterLayer (self)
Layer menu SLOT to handle adding raster layers to the map canvas
Definition at line 2298 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.openRasterLayer().
    def addRasterLayer(self):
        ''' Layer menu SLOT to handle adding raster layers to the map canvas '''
        # debugging
        print "Main.mainwindow.addRasterLayer()"
        # Need this to handle if the user tries to addRaster while making line or polygon edits
        # check app state and handle user cancel
        if self.appStateChanged("addRaster") == "Cancel": return
        # open file dialog
        qd = QtGui.QFileDialog()
        filterString = "All Files(*)\nMrSID(*.sid *.SID)\nGeoTIFF\
(*.tif *.tiff *.TIF *.TIFF)\nArc/Info Binary Grid(*.adf *.ADF)\n\
JPEG(*.jpg *.jpeg *.JPG *.JPEG)"
        # get the path to the directory containing the opened file using Python
        directory = config.baseLayersPath
        # change QString to unicode so Python can slice it for the directory name
        rfilePath = unicode(qd.getOpenFileName(self, "Add Raster Layer",
                                    directory, filterString))
        # Check for cancel
        if len(rfilePath) == 0: return
        #create the layer
        self.openRasterLayer(rfilePath)
def Main.mainwindow.MainWindow.addVectorLayer (self)
Layer menu SLOT to handle adding vector layers to the map canvas
Definition at line 2272 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.openVectorLayer().
    def addVectorLayer(self):
        ''' Layer menu SLOT to handle adding vector layers to the map canvas '''
        # debugging
        print "Main.mainwindow.addVectorLayer()"
        # Need this to handle if user tries to addVector while adding a line or polygon
        # check app state and handle user cancel
        if self.appStateChanged("addVector") == "Cancel":
            return
        # open the file dialog
        qd = QtGui.QFileDialog()
        filterString = "ESRI Shapefile(*.shp *.SHP)\nComma Separated Value\
(*.csv *.CSV)\nGeography Markup Language(*.gml *.GML)\nGPX(*.gpx *.GPX)\nKML(*.kml *.KML)\
SQLite(*.sqlite *.SQLITE)\nArc\\Info ASCII Coverage(*.e00 *.E00)\nAll Files(*)"
        # get the path to the directory containing the opened file using Python
        directory = config.baseLayersPath
        # change the QString to unicode so that Python can slice it for the directory name
        vfilePath = unicode(qd.getOpenFileName(self, "Add Vector Layer",
                                            directory, filterString))
        # Check for cancel
        if len(vfilePath) == 0: return
        self.openVectorLayer(vfilePath)
def Main.mainwindow.MainWindow.appStateChanged (self, callingAction)
    Manage the application state changes from user actions.
    Actions that call this method are: newScenario, openScenario, saveScenario, saveScenarioAs,
    exportScenario, appClosing, selectFeatures, stoppingEditing, zoomIn, zoomOut, pan,
    zoomToMapExtent, identifyFeatures, addVector, addRaster, openVectorAttributeTable,
    openRasterCategoryTable, legendMousePress, manageProjects.
Definition at line 2647 of file mainwindow.py.
References Main.mainwindow.MainWindow.activeRLayer, Main.mainwindow.MainWindow.activeVLayer, Main.mainwindow.MainWindow.checkEditsState(), Main.mainwindow.MainWindow.checkScenarioState(), Main.mainwindow.MainWindow.editDirty, Main.mainwindow.MainWindow.editMode, Main.mainwindow.MainWindow.layerType, Main.mainwindow.MainWindow.scenarioDirty, Main.mainwindow.MainWindow.scenarioFilePath, and Main.mainwindow.MainWindow.toolAddLinesPolygons.
Referenced by Main.mainwindow.MainWindow.addRasterLayer(), Main.mainwindow.MainWindow.addVectorLayer(), Main.mainwindow.MainWindow.closeEvent(), Main.mainwindow.MainWindow.editScenario(), Main.mainwindow.MainWindow.exportScenario(), Main.mainwindow.MainWindow.identifyFeatures(), Main.mainwindow.MainWindow.manageProjects(), Main.mainwindow.MainWindow.modifyFeatures(), Main.mainwindow.MainWindow.newScenario(), Main.mainwindow.MainWindow.openRasterCategoryTable(), Main.mainwindow.MainWindow.openScenario(), Main.mainwindow.MainWindow.openVectorAttributeTable(), Main.mainwindow.MainWindow.pan(), Main.mainwindow.MainWindow.saveScenario(), Main.mainwindow.MainWindow.saveScenarioAs(), Main.mainwindow.MainWindow.selectFeatures(), Main.mainwindow.MainWindow.zoomIn(), Main.mainwindow.MainWindow.zoomOut(), and Main.mainwindow.MainWindow.zoomToMapExtent().
    def appStateChanged(self, callingAction):
        '''
            Manage the application state changes from user actions.
            Actions that call this method are: newScenario, openScenario, saveScenario, saveScenarioAs,
            exportScenario, appClosing, selectFeatures, stoppingEditing, zoomIn, zoomOut, pan,
            zoomToMapExtent, identifyFeatures, addVector, addRaster, openVectorAttributeTable,
            openRasterCategoryTable, legendMousePress, manageProjects.
        '''
        # If no layer is loaded then user is loading first layer after app start (num layers = 0),
        # or loading first layer after deleting the only layer in the legend (num layers = 0).
        # If there are no layers in the scenario, no need to save the scenario or edits.
        if len(self.legend.getLayerIDs()) == 0:  return
        # If user in the middle of a line or polygon edit, warn when they choose another action.
        if self.toolAddLinesPolygons and self.toolAddLinesPolygons.started:
            QtGui.QMessageBox.warning(self, "Editing Error", "Please complete your edit \
before taking another action!")
            # reset the correct action
            if self.toolAddLinesPolygons.geom:
                self.mpActionAddPolygons.setChecked(True)
            else:
                self.mpActionAddLines.setChecked(True)
            return "Cancel"
        #**********************************************************
        ''' Debugging code '''
        print "MAIN.MAINWINDOW.APP_STATE_CHANGED() STARTING: callingAction is " + callingAction
        if self.activeVLayer == None: print "asc no active vlayer"
        else: print "asc current active " + self.activeVLayer.name()
        if self.activeRLayer == None: print "asc no active rlayer"
        else: print "asc current active rlayer " + self.activeRLayer.name()
        print "asc num layers " + str(len(self.legend.getLayerIDs()))
        print "asc registry count " + str(QgsMapLayerRegistry.instance().count())
        print "asc the layer type is " + str(self.layerType)
        print "asc self.editDirty is " + str(self.editDirty)
        print "asc self.editMode is " + str(self.editMode)
        print "asc self.scenarioDirty is " + str(self.scenarioDirty)
        print "asc scenarioFilePath " + str(self.scenarioFilePath)
        #******************************************************************
        '''
        On any other user action, check for unsaved edits and unsaved scenarios.
        '''
        # We should check for unsaved edits when stopping editing,
        # on all scenario menu actions, when managing projects or on closing the app.
        callingList = ["newScenario", "openScenario", "saveScenario", "saveScenarioAs", "exportScenario",
                       "appClosing", "modifyingEdits", "stoppingEditing", "manageProjects"] # "startingEditing",,
        if self.editDirty:
            if callingAction in callingList:
                if self.checkEditsState(callingAction) == "Cancel": return "Cancel"
        # We only want to check for a dirty scenario when:
        # creating a new scenario, opening a scenario, saving a scenario as exporting a scenario, managing projects or closing the app.
        # (note that if we don't check "Save Scenario As," for a dirty scenario, the scenario we are renaming may have editing layers
        # open that have not been saved.  The user must either save or discard to properly handle the open editing layers or
        # they may not appear in the legend when the scenario is reopened yet they will appear in exported scenarios!!!
        #
        callingList = ["newScenario", "openScenario", "saveScenarioAs", "exportScenario", "manageProjects", "appClosing"]
        if self.scenarioDirty:
            if callingAction in callingList:
                if self.checkScenarioState(callingAction) == "Cancel": return "Cancel"
        # debugging
        print "Main.mainwindow.appStateChanged() has returned nothing"
def Main.mainwindow.MainWindow.arrangeOrientingLayers (self)
The QgsProject instance does not set layer position in our layer panel,
    so we set it here, but only for orienting layers.
Definition at line 3066 of file mainwindow.py.
References Main.legend.LegendItem.legend, Main.mainwindow.MainWindow.legend, and Main.mainwindow.MainWindow.originalScenarioLayersNames.
Referenced by Main.mainwindow.MainWindow.openScenario().
    def arrangeOrientingLayers(self):
        ''' The QgsProject instance does not set layer position in our layer panel,
            so we set it here, but only for orienting layers.
        '''
        # debugging
        print "Main.mainwindow.arrangeOrientingLayers()"
        names = self.originalScenarioLayersNames
        legend = self.legend
        legendLayers = legend.getLayerIDs()
        numLegendLayers = len(legendLayers)
        oRLayers = config.orientingRasterLayers
        oVLayers = config.orientingVectorLayers
        # Get the names of orententing layers open in this scenario
        oRLayersCurrent = [name for name in oRLayers if name[0:-4] in names]
        oVLayersCurrent = [name for name in oVLayers if name[0:-4] in names]
        # If the number of names in this scenario is less than the total number of orienting layers
        # then the user has deleted some orienting layers, so we'll just leave the layers as is.
        # Note that the code below this will not work properly if the number of orienting layers is not equal
        # (some layers don't show because they are inserted at non-existent indexes).
        if (len(oRLayersCurrent) + len(oVLayersCurrent)) != (len(oRLayers) + len(oVLayers)):
            return
        # debugging
        # Note that the index of the legend layers starts with zero.
        # For a legend having 10 layers the indexes run from 0 to 9.
        # If you try to insert a layer  into the QTreeWidget at an index
        # that doesn't exist, the layer will not be inserted and will not appear.
        print "Main.mainwindow.arrangeOrientingLayers(): numLegendLayers is " + str(numLegendLayers)
        # First load the raster layers
        for orientingLayer in oRLayers:
            info = QtCore.QFileInfo(orientingLayer)
            orientingLayerName = info.completeBaseName()
            print "Main.mainwindow.arrangeOrientingLayers(): orientingLayerName is " + orientingLayerName
            item = legend.findItems(orientingLayerName, QtCore.Qt.MatchFixedString, 0)
            print "Main.mainwindow.arrangeOrientingLayers(): length of item list is " + str(len(item))
            if len(item) != 0:
                itemToMove = item[0]
                print "Main.mainwindow.arrangeOrientingLayers(): is this a legendLayer? " + str(legend.isLegendLayer(itemToMove))
                print "Main.mainwindow.arrangeOrientingLayers(): item to move is " + itemToMove.text(0)
                position = numLegendLayers - (oRLayers.index(orientingLayer) + 1) # itemToMove is the base layer
                print "Main.mainwindow.arrangeOrientingLayers(): r position is " + str(position)
                itemToMove.storeAppearanceSettings() # Store settings
                legend.takeTopLevelItem(legend.indexOfTopLevelItem(itemToMove))
                legend.insertTopLevelItem(position, itemToMove)
                legend.insertTopLevelItem(1, itemToMove)
                itemToMove.restoreAppearanceSettings()
        # then load the vector layers
        for orientingLayer in oVLayers:
            info = QtCore.QFileInfo(orientingLayer)
            orientingLayerName = info.completeBaseName()
            print "Main.mainwindow.arrangeOrientingLayers(): orientingLayerName is " + orientingLayerName
            item = legend.findItems(orientingLayerName,
                                          QtCore.Qt.MatchFixedString, 0)
            print "Main.mainwindow.arrangeOrientingLayers(): length of item list is " + str(len(item))
            if len(item) != 0:
                itemToMove = item[0]
                print "Main.mainwindow.arrangeOrientingLayers(): is this a legendLayer? " + str(legend.isLegendLayer(itemToMove))
                print "Main.mainwindow.arrangeOrientingLayers(): item to move is " + itemToMove.text(0)
                position = (numLegendLayers - (oVLayers.index(orientingLayer)
                                                           + (len(oRLayers) + 1)))
                print "Main.mainwindow.arrangeOrientingLayers(): v position is " + str(position)
                itemToMove.storeAppearanceSettings() # Store settings
                legend.takeTopLevelItem(legend.indexOfTopLevelItem(itemToMove))
                legend.insertTopLevelItem(position, itemToMove)
                itemToMove.restoreAppearanceSettings()
        # now update the layer set to ensure proper rendering by QGIS
        self.legend.updateLayerSet()
def Main.mainwindow.MainWindow.checkBaseLayerMatch (self, title, text)
Checks whether the base layer selected matches the current scenario edit type
Definition at line 3210 of file mainwindow.py.
References Main.mainwindow.MainWindow.scenarioEditType.
Referenced by Main.mainwindow.MainWindow.deleteFeatures(), and Main.mainwindow.MainWindow.modifyFeatures().
    def checkBaseLayerMatch(self, title, text):
        ''' Checks whether the base layer selected matches the current scenario edit type '''
        # debugging
        print 'Main.mainwindow.checkBaseLayerMatch()'
        name = unicode(self.activeVLayer.name())
        editType = self.scenarioEditType
        if ((editType == config.scenarioEditTypesList[0] and name != config.pointBaseLayersBaseNames[0]) or
             (editType == config.scenarioEditTypesList[1] and name != config.pointBaseLayersBaseNames[1]) or
             (editType == config.scenarioEditTypesList[2] and name != config.pointBaseLayersBaseNames[2]) or
             (editType == config.scenarioEditTypesList[3] and name != config.pointBaseLayersBaseNames[3]) or
             editType == config.scenarioEditTypesList[4] or editType == config.scenarioEditTypesList[5] or
             editType == config.scenarioEditTypesList[6]):
            QtGui.QMessageBox.warning(self, title, "The point base layer which \
you are trying to " + text + " does not match the scenario edit type you have chosen. \
For example. If you have chosen to edit 'dams,' then you can only " + text + " the layer \
'base_dams'")
            return False
        else: return True
def Main.mainwindow.MainWindow.checkEditFeatureMatch (self, editLayer, features)
    This edit method checks whether editing layer features that the user wishes to modify
    match the current scenario edit type.
Definition at line 2093 of file mainwindow.py.
References Main.mainwindow.MainWindow.checkFieldNameMatch(), and prepareforsetupexe.name.
Referenced by Main.mainwindow.MainWindow.modifyFeatures().
    def checkEditFeatureMatch(self, editLayer, features):
        '''
            This edit method checks whether editing layer features that the user wishes to modify
            match the current scenario edit type.
        '''
        # debugging
        print "Main.mainwindow.checkEditFeatureMatch()"
        editLayerProvider = editLayer.dataProvider()
        for feat in features:
            attrs = feat.attributeMap()
            for key, value in attrs.iteritems():
                print "Main.mainwindow.checkEditFeatureMatch(): The key is " + str(key)
                print "Main.mainwindow.checkEditFeatureMatch(): The value is " + value.toString()
                if unicode(value.toString()) == "": continue
                else:
                    fieldMap = editLayerProvider.fields()
                    fieldName = unicode(fieldMap[key].name())
                    print "Main.mainwindow.checkEditFeatureMatch(): The fieldName is " +  fieldName
                    if not self.checkFieldNameMatch(fieldName):
                        QtGui.QMessageBox.warning(self, "Modify Edits Error", "At least one of the features that you selected \
was not created by using the current scenario edit type.  After choosing a particular scenario edit type, you can only \
modify edits created using that scenario edit type. Please use the 'Identify Features' tool to \
find what scenario edit type was used to create the features you wish to modify and then choose the matching \
scenario edit type to modify them.  Your modifications were not made. Please try again.")
                        return False
                    else: break
        else: return True
def Main.mainwindow.MainWindow.checkEditsState (self, callingAction)
Prompt the user about unsaved edits
Definition at line 2717 of file mainwindow.py.
References Main.mainwindow.MainWindow.attrTable, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.editMode, Main.mainwindow.MainWindow.openVectorAttributeTable(), Main.mainwindow.MainWindow.originalEditLayerFeats, and Main.mainwindow.MainWindow.saveEdits().
Referenced by Main.mainwindow.MainWindow.appStateChanged().
    def checkEditsState(self, callingAction):
        ''' Prompt the user about unsaved edits '''
        # debugging
        print "Main.mainwindow.checkEditsState()"
        # Prompt the user about clearing selections/edits
        # and deactivate the action if necessary.
        title = "Save Edits"
        text = "Do you want to save your edits to " + self.editLayerName + "?"
        # Once in edit mode, it is impossible to exit edit mode, or do anything else, without
        # either saving or discarding changes. So, this dialog is only called when in edit mode.
        callingList = ["saveScenario", "saveScenarioAs", "exportScenario"]
        reply = QtGui.QMessageBox.question(self, title, text,
                QtGui.QMessageBox.Cancel|QtGui.QMessageBox.Save|QtGui.QMessageBox.Discard )
        if reply == QtGui.QMessageBox.Save: # so save edits
            # debugging
            print "Main.mainwindow.checkEditsState(): msgBoxSaveDiscardCancel = Save"
            # There is no need to handle editing state or app state here.
            # App state should be handled by the calling action on return and at the
            # last possible moment before the action takes effect.
            self.saveEdits()
        elif reply == QtGui.QMessageBox.Discard: # so handle as above but discard edits
            # debugging
            print "Main.mainwindow.checkEditsState(): msgBoxYesDiscardCancel = Discard"
            # Under these situations just discard edits and leave editing state as is
            # but update the attribute table if open.
            if callingAction in callingList:
                shared.deleteEdits(self, self.editLayerName, self.originalEditLayerFeats)
                if self.attrTable != None and self.attrTable.isVisible():
                    self.openVectorAttributeTable()
            elif callingAction == "modifyingEdits":
                # Warn the user that they must save edits to modify them and return "cancel."
                QtGui.QMessageBox.information(self, "Modify Features Information", "You must save all edits before \
you can modify any of them. Please click OK and try again if you still wish to modify edits.")
                return "Cancel"
            # If opening new scenario, opening a saved scenario, closing the app or stopping editing.
            # discard the edits. The calling method will handle editing state or app state on return.
            else:
                shared.deleteEdits(self, self.editLayerName, self.originalEditLayerFeats)
        elif reply == QtGui.QMessageBox.Cancel:
            if callingAction == "stoppingEditing" and self.editMode:
                    self.mpActionEditScenario.blockSignals(True)
                    self.mpActionEditScenario.setChecked(True)
                    self.mpActionEditScenario.blockSignals(False)
            print "Main.mainwindow.checkEditsState(): returning 'cancel'"
            return "Cancel"
def Main.mainwindow.MainWindow.checkFieldNameMatch (self, fieldName)
An edit method that checks whether the name of a field matches the current scenario edit type
Definition at line 2123 of file mainwindow.py.
References Main.mainwindow.MainWindow.scenarioEditType.
Referenced by Main.mainwindow.MainWindow.checkEditFeatureMatch().
    def checkFieldNameMatch(self, fieldName):
        ''' An edit method that checks whether the name of a field matches the current scenario edit type '''
        # debugging
        print "Main.mainwindow.checkFieldNameMatch()"
        editType = self.scenarioEditType
        if fieldName == 'cross_id' and editType == config.scenarioEditTypesList[0]: return True
        elif fieldName == 'dam_id' and editType == config.scenarioEditTypesList[1]: return True
        elif fieldName == 'wildlf_id' and editType == config.scenarioEditTypesList[2]: return True
        elif fieldName == 'restr_id' and editType == config.scenarioEditTypesList[3]: return True
        elif fieldName == 'newrd_id' and editType == config.scenarioEditTypesList[4]: return True
        elif fieldName == 'modrd_id' and editType == config.scenarioEditTypesList[5]: return True
        elif fieldName == 'ldcvr_id' and editType == config.scenarioEditTypesList[6]: return True
        else: return False
def Main.mainwindow.MainWindow.checkForDeletions (self, editLayer, features)
This edit method checks if a user is attempting to modify deletions on an editing layer
Definition at line 2168 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.modifyFeatures().
    def checkForDeletions(self, editLayer, features):
        ''' This edit method checks if a user is attempting to modify deletions on an editing layer '''
        # debugging
        print "Main.mainwindow.checkForDeletions()"
        for feat in features:
            attrs = feat.attributeMap()
            subcount = None
            for key, value in attrs.iteritems():
                print "Main.mainwindow.checkForDeletions(): key = " + str(key)
                print "Main.mainwindow.checkForDeletions(): The subcount is " + str(subcount)
                print "Main.mainwindow.checkForDeletions(): The value is " + value.toString()
                if unicode(value.toString()) == "": continue
                elif subcount == None:
                    subcount = key
                    print "Main.mainwindow.checkForDeletions(): subcount first set at " + str(subcount)
                    continue
                if key == subcount + 2:
                    if unicode(value.toString()) == "y":
                        QtGui.QMessageBox.warning(self, "Modify Edits Error", "You cannont modify deleted features. \
If you wish to remove a deleted feature from an editing layer then select it and choose 'Delete Selected.'")
                        return False
                    else: break
        else: return True # if no features are deleted edit layer features
def Main.mainwindow.MainWindow.checkLayerLoadError (self, layer)
Definition at line 3201 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.openHiddenVectorLayer(), Main.mainwindow.MainWindow.openRasterLayer(), and Main.mainwindow.MainWindow.openVectorLayer().
    def checkLayerLoadError(self, layer):
        # debugging
        print "Main.mainwindow.checkLayerLoadError()"
        # check for error
        if not layer.isValid():
            QtGui.QMessageBox.warning(self, "File Error", "Layer failed to load!")
            return False
        else: return True
def Main.mainwindow.MainWindow.checkPastedFeatureConstraints (self)
Utility method to check constraints for pasted features
Definition at line 3279 of file mainwindow.py.
References Main.mainwindow.MainWindow.copiedFeats, Main.mainwindow.MainWindow.copyFlag, Main.mainwindow.MainWindow.geom, and Main.mainwindow.MainWindow.scenarioEditType.
Referenced by Main.mainwindow.MainWindow.pasteFeatures().
    def checkPastedFeatureConstraints(self):
        ''' Utility method to check constraints for pasted features '''
        # debugging
        print "Main.mainwindow.checkPastedFeatureConstraints()"
        #xform = self.canvas.getCoordinateTransform() # returns the QgsMapToPixel() class for the map canvas
        qPoint = None
        if self.geom == 0:
            for feat in self.copiedFeats:
                qgsPoint = feat.geometry().asPoint()
                # xform.transform(qgsPoint) # QgsMapToPixel.transform() changes map coords to device coords
                featId = feat.id()
                print "Main.mainwindow.checkPastedFeatureConstraints(): The point is " + str(qgsPoint)
                if not shared.checkConstraints(self, qgsPoint, qPoint, featId):
                    # check constraints failed so undo the copy and disable the paste action
                    self.copiedFeats = None
                    self.copyFlag = False
                    self.mpActionPasteFeatures.setDisabled(True)
                    return False
            else: return True
        elif self.geom == 1:
            for feat in self.copiedFeats:
                featId = feat.id()
                line = feat.geometry().asPolyline()
                endCount = len(line)
                for count, point in enumerate(line): # get the first point and last point of the line
                    if count == 0:
                        firstPoint = point
                        print "Main.mainwindow.checkPastedFeatureConstraints(): firstPoint is (" + str(point.x()) + ", " + str(point.y()) + ")"
                    elif count == endCount-1:
                        lastPoint = point
                        print "Main.mainwindow.checkPastedFeatureConstraints(): lastPoint is (" + str(point.x()) + ", " + str(point.y()) + ")"
                for count, qgsPoint in enumerate([firstPoint, lastPoint]):
                    #qPoint = None #xform.transform(qgsPoint) # QgsMapToPixel.transform() changes map coords to device coords
                    if shared.checkRoadConstraints(self, config.baseLayersPath, qgsPoint, qPoint, self.scenarioEditType, featId):
                        break # feat meets constraints, so go to next feat
                    elif count == 0: continue
                    else:
                        QtGui.QMessageBox.warning(self, "Constraints Error:", "All pasted features must fall \
on a road in the 'base_traffic' layer. The feature in row " + str(featId+1) + " in the attribute table of \
the layer you copied from does not meet this constraint.  Please check all your points carefully and try again.")
                        return False
            else: return True
        else: return True
#**************************************************************
def Main.mainwindow.MainWindow.checkScenarioDirectoryPath (self, defaultDir, scenarioFilePath)
A scenario method to check if the user is saving scenario's to the proper directory
Definition at line 1010 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.saveScenarioAs().
    def checkScenarioDirectoryPath(self, defaultDir, scenarioFilePath):
        ''' A scenario method to check if the user is saving scenario's to the proper directory '''
        # debugging
        print "Main.mainwindow.checkScenarioDirectoryPath()"
        dirInfo = QtCore.QFileInfo(defaultDir)
        defaultScenarioDirectoryPath = unicode(dirInfo.absoluteFilePath())
        print "Main.mainwindow.checkScenarioDirectoryPath(): defaultScenarioDirectoryPath is " + defaultScenarioDirectoryPath # Python can concatenate QStrings
        scenarioFileInfo = QtCore.QFileInfo(scenarioFilePath)
        scenarioDirectoryPath = unicode(scenarioFileInfo.absolutePath())
        fileName = unicode(scenarioFileInfo.fileName()) # change to unicode for Python string operations
        print "Main.mainwindow.checkScenarioDirectoryPath(): The scenarioDirectoryPath is " + scenarioDirectoryPath
        print "Main.mainwindow.checkScenarioDirectoryPath(): The fileName is " + fileName
        if (scenarioDirectoryPath != defaultScenarioDirectoryPath  and
            scenarioDirectoryPath != defaultScenarioDirectoryPath[:-1]): # not fileName.endswith(".cap")
            QtGui.QMessageBox.warning(self, "File Save Error:", "Scenarios must be saved in the 'Scenarios' directory, \
which the 'Save Scenario as...' dialog opens by default.  Also, the file name must end with the extension \
'.cap'. If you save a scenario name without adding an extension, the file dialog will add the '.cap' extension for you. \n\n\
Your scenario was not saved.  Please try again.")
            return False
        else: return True
def Main.mainwindow.MainWindow.checkScenarioState (self, callingAction)
Prompt the user about unsaved scenario changes
Definition at line 2764 of file mainwindow.py.
References Main.mainwindow.MainWindow.getCurrentLayersNames(), Main.mainwindow.MainWindow.getLayerFromName(), Main.mainwindow.MainWindow.originalScenarioLayersNames, Main.mainwindow.MainWindow.saveScenario(), Main.mainwindow.MainWindow.saveScenarioAs(), and Main.mainwindow.MainWindow.scenarioFilePath.
Referenced by Main.mainwindow.MainWindow.appStateChanged().
    def checkScenarioState(self, callingAction):
        ''' Prompt the user about unsaved scenario changes '''
        # debugging
        print "Main.mainwindow.checkScenarioState()"
        # We need to check when the calling action is 'saveScenarioAs', and the scenario has been saved because
        # we either need to save the dirty scenario or we need to delete any editing layers added since the last
        # save if the user chooses to discard changes. However, if the scenario has not been saved,
        #  then we just want to save it, so simply return.
        if callingAction == "saveScenarioAs" and not self.scenarioFilePath:
            return
        # Prompt the user about a dirty scenario.
        title = "Save Scenario"
        text = "Do you want to save the current scenario?"
        reply = QtGui.QMessageBox.question(self, title, text,
                QtGui.QMessageBox.Cancel|QtGui.QMessageBox.Save|QtGui.QMessageBox.Discard )
        if reply == QtGui.QMessageBox.Save: # user chose to save scenario
            # debugging
            print "Main.mainwindow.checkScenarioState(): msgBoxSaveDiscardCancel = Save"
            if self.scenarioFilePath: self.saveScenario()
            elif self.saveScenarioAs() == "Cancel": return "Cancel"
        elif reply == QtGui.QMessageBox.Discard:
            # debugging
            print "Main.mainwindow.checkScenarioState(): msgBoxYesDiscardCancel = Discard"
            if callingAction == "exportScenario":
                QtGui.QMessageBox.information(self, "Export Scenario Information", "You must save the scenario before \
you can export it. Please click OK and try again if you still wish to export the scenario.")
                return "Cancel"
            # If the user wants to close a scenario without saving it, we need to check
            # for editing layers that were not part of the last save for this scenario
            # and delete them. If an editing layer is open but has not been saved with the scenario,
            # and the user doesn't choose to save the scenario, then that editing layer will not appear
            # if the scenario is reopened. However, it would remain in the scenario's folder
            # where it will be read and included in an export.  This would certainly  lead to
            # erroneous scenario exports!!
            # Self.currentLayersNames() returns a list of names of open layers.
            # We check this for differences with the names of layers included when the the scenario.
            # was last saved.
            differences = [name for name in self.getCurrentLayersNames() if name not in
                                                            self.originalScenarioLayersNames]
            # debugging
            print "Main.mainwindow.checkScenarioState(): These are the originalScenarioLayersNames"
            for name in self.originalScenarioLayersNames: print name
            print "Main.mainwindow.checkScenarioState(): These are the CurrentLayersNames()"
            for name in self.getCurrentLayersNames(): print name
            print "Main.mainwindow.checkScenarioState(): These are the differences:"
            for name in differences: print name
            for name in differences:
                # get the layer object from the name
                layer = self.getLayerFromName(name)
                editFilePath = layer.source()
                print "Main.mainwindow.checkScenarioState() path to remove is: " + editFilePath
                layerId = layer.id()
                # need to remove layer from registry before delete.
                self.legend.removeLayerFromRegistry(layer, layerId)
                # If the layer is an editing layer, we have to delete it from the scenario's directory
                # so it won't be included in future scenario export files.
                if name in config.editLayersBaseNames:
                    if not self.legend.deleteEditingLayer(editFilePath):
                        # Warn and return
                        QtGui.QMessageBox.warning(self, "Deletion Error:", "Caps Scenario Builder \
    could not delete an editing layer that you have chosen not to save with your scenario.  This \
    editing layer will not appear when you reopen this scenario, but it could be mistakenly included if you \
    choose 'Export Scenario' for this scenario in the future.")
                        return "Cancel"
                self.mpActionSaveEdits.setDisabled(False)
        elif reply == QtGui.QMessageBox.Cancel:
            print "Main.mainwindow.checkScenarioState() returning 'cancel'"
            return "Cancel"
def Main.mainwindow.MainWindow.closeEvent (self, event)
Slot to handle signal emitted when user exits app
Definition at line 2638 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged().
    def closeEvent(self, event):
        ''' Slot to handle signal emitted when user exits app '''
        if self.appStateChanged("appClosing") == "Cancel": event.ignore()
def Main.mainwindow.MainWindow.copyFeatures (self)
Edit menu SLOT to handle copying features
Definition at line 1181 of file mainwindow.py.
References Main.mainwindow.MainWindow.copiedFeatCount, Main.mainwindow.MainWindow.copyFeaturesShared(), and Main.mainwindow.MainWindow.copyFlag.
    def copyFeatures(self):
        ''' Edit menu SLOT to handle copying features '''
        # debugging
        print "Main.mainwindow.copyFeatures()"
        self.copyFlag = False
        # store the feature geometry and count as an instance variable
        # for use in pasteFeatures()
        self.copiedFeatCount = self.activeVLayer.selectedFeatureCount()
        # check if there are any features to copy
        if self.copiedFeatCount == 0:
            title = "Copy Features"
            text = "You must select at least one feature to copy."
            QtGui.QMessageBox.information(self, title, text, QtGui.QMessageBox.Ok)
        else: # so we have features to copy
            # This method copies the features, but the same method is used in deleteFeatures
            self.copyFeaturesShared()
        # we have copied features so enable the paste action
        self.mpActionPasteFeatures.setDisabled(False)
def Main.mainwindow.MainWindow.copyFeaturesShared (self)
    This edit method copies features and is used by Main.mainwindow.copyFeatures(),
    Main.mainwindow. modifyFeatures, mainwindow.deleteFeatures()
    (when deleting from config.pointBaseLayersBaseNames)
Definition at line 1767 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.copyFeatures(), Main.mainwindow.MainWindow.deleteFeatures(), and Main.mainwindow.MainWindow.modifyFeatures().
    def copyFeaturesShared(self):
        '''
            This edit method copies features and is used by Main.mainwindow.copyFeatures(),
            Main.mainwindow. modifyFeatures, mainwindow.deleteFeatures()
            (when deleting from config.pointBaseLayersBaseNames)
        '''
        # get the id of the layer we are copying from for use in paste features
        self.copyLayer = self.activeVLayer
        # make copy as instance variable so we can paste features into another layer
        # "selectedFeatures" is a QgsFeatureList (a Python list of QgsFeature objects)
        self.copiedFeats = self.activeVLayer.selectedFeatures()
        self.copiedFeatCount = self.activeVLayer.selectedFeatureCount()
        self.copiedFeatGeom = self.activeVLayer.geometryType()
        self.copyFlag = True
        # remove the selection from the activeVLayer and reset the select tool
        self.activeVLayer.removeSelection(False) # false means no signal emitted
        print "mainwindow.copyFeaturesShared() removed selection and selected features count is " + str(self.activeVLayer.selectedFeatureCount())
        self.activeVLayer.triggerRepaint()
        self.canvas.unsetMapTool(self.toolSelect)
        self.mpActionSelectFeatures.setChecked(False)
def Main.mainwindow.MainWindow.copyScenario (self, oldScenarioInfo, scenarioDirectoryName, editLayerLegendItems)
A scenario method to copy all the files of an existing scenario.
Definition at line 1033 of file mainwindow.py.
References Main.mainwindow.MainWindow.crs, Main.mainwindow.MainWindow.dlgScenarioEditTypes, Main.legend.LegendItem.legend, Main.mainwindow.MainWindow.legend, Main.mainwindow.MainWindow.makeScenarioDirectory(), Main.mainwindow.MainWindow.openVectorLayer(), Main.mainwindow.MainWindow.originalScenarioLayers, Main.mainwindow.MainWindow.scenarioInfo, and Main.dlgscenarioedittypes.DlgScenarioEditTypes.scenarioInfo.
Referenced by Main.mainwindow.MainWindow.saveScenarioAs().
    def copyScenario(self, oldScenarioInfo, scenarioDirectoryName, editLayerLegendItems):
        ''' A scenario method to copy all the files of an existing scenario. '''
        # debugging
        print "Main.mainwindow.copyScenario()"
        # So we have editing files open so create the new scenario directory to write them to.
        # This method deletes any old directory and any old "Scenario Export" files having the
        # same name as the new scenario name.  So if we are overwriting an old scenario, we
        # start fresh.
        self.makeScenarioDirectory()
        # Now copy any existing "Export Scenario" file
        oldScenarioDirectoryName = unicode(oldScenarioInfo.completeBaseName())
        oldExportFileName = oldScenarioDirectoryName + ".csv" # Python elevates to unicode
        oldExportPath = config.scenarioExportsPath + oldExportFileName # so unicode too
        newExportFileName = scenarioDirectoryName + ".csv" # unicode
        newExportFilePath = config.scenarioExportsPath + newExportFileName # unicode
        oldExportFile = QtCore.QFile(oldExportPath)
        error = None
        if oldExportFile.exists():
            try:
                oldExportFile.copy(newExportFilePath)
            except (IOError, OSError), e:
                error = unicode(e)
            if error:
                print error
                QtGui.QMessageBox.warning(self, 'Deletion Error:', 'The previously saved scenario export file'\
+ oldExportFileName + ' could not be renamed.  Please try again.')
        # While the editing layers are open, copy them to the new scenario directory
        # and record the paths to open them later.
        scenarioDirectoryPath = unicode(config.scenariosPath + scenarioDirectoryName)
        copyPaths = []
        editLayerIds = []
        for item in editLayerLegendItems:
            vlayerId = item.layerId
            editLayerIds.append(vlayerId)
            vlayer = QgsMapLayerRegistry.instance().mapLayer(vlayerId)
            vlayerName = vlayer.name() + ".shp"
            copyPath = scenarioDirectoryPath + "/" + vlayerName
            copyPaths.append(copyPath)
            print "Main.mainwindow.copyScenario(): copyPath is " + copyPath
            error = QgsVectorFileWriter.writeAsVectorFormat(vlayer, copyPath , "utf-8",
                                                                self.crs, "ESRI Shapefile")
            if error != QgsVectorFileWriter.NoError:
                QtGui.QMessageBox.warning(self, "Write Error:", "The file " + vlayerName + " \
was not written.  Please check that a file with the same name is not open in another program.")
                return
            else: print "Main.mainwindow.copyScenario(): Success, editing layers copied!"
        # debugging
        print "Main.mainwindow.copyScenario(): copyPaths are:"
        print copyPaths
        # Now we can close the editing layers associated with the old scenario path
        # and then open the ones we wrote to the new directory.  This will allow us
        # to save a new scenario file (i.e. '.cap' file) that contains the correct
        # paths to the copied editing shapefiles. No need for emitting signals here.
        self.legend.blockSignals(True)
        self.legend.removeLayers(editLayerIds) # this method also removes the files from the registry
        self.legend.blockSignals(False)
        print "Main.mainwindow.copyScenario(): CLOSED OLD EDIT SHAPEFILES"
        # The old activeVLayer may have been deleted so set all associated variables to "None"
        #  or we would get runtime errors due to the underlying C++ object being deleted.
        # The activeVLayer will be reset when we load the layers below.
        self.legend.setActiveLayerVariables()
        self.originalScenarioLayers = []
        # Open the copied editing shapefiles (they will open at the top of the layer panel)
        # The last one opened will become the new activeVLayer
        for path in copyPaths:
            # return on error, openVectorLayer() provides the error message box
            if not self.openVectorLayer(path): return
        # if we have opened a scenario edit type
        if self.dlgScenarioEditTypes:
            # We opened new editing layers, so color the text of the editing and base layers.
            # The below works because the instance variable remains active
            self.dlgScenarioEditTypes.colorEditBaseConstraintLayers(self.legend)
            # Now we position the editing layer and any base layer or constraints layer that exists
            # for the current scenario edit type.
            self.dlgScenarioEditTypes.moveLayer(self.legend, self.dlgScenarioEditTypes.editLayerBaseName, 0)
            if (self.dlgScenarioEditTypes.baseLayerBaseName and
                            self.dlgScenarioEditTypes.baseLayerBaseName != config.polygonBaseLayersBaseNames[1]):
                self.dlgScenarioEditTypes.moveLayer(self.legend, self.dlgScenarioEditTypes.baseLayerBaseName, 1)
            if self.dlgScenarioEditTypes.constraintLayerBaseName:
                if self.dlgScenarioEditTypes.baseLayerBaseName: position = 2
                else: position = 1
                self.dlgScenarioEditTypes.moveLayer(self.legend, self.dlgScenarioEditTypes.constraintLayerBaseName, position)
        # Finally, write the project information to a scenario file using QgsProject
        scenario = QgsProject.instance()
        scenario.write(self.scenarioInfo)
        # check for write error
        if scenario.error():
            QtGui.QMessageBox.warning(self, "Failed to save:", "Please check \
if this scenario file is open in another program.")
            # QgsProject has no "close()" method, so, if error, close the project instance
            scenario = None
            return
        scenario = None # if no error close the QgsProject.instance()
def Main.mainwindow.MainWindow.deleteExportScenarioFile (self)
Delete the scenario's export file.  Used by mainwindow.exportScenario()
    and legend.Legend.deleteEditingLayer()
Definition at line 3175 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def deleteExportScenarioFile(self):
        ''' Delete the scenario's export file.  Used by mainwindow.exportScenario()
            and legend.Legend.deleteEditingLayer()
        '''
        # debugging
        print "Main.mainwindow.deleteExportScenarioFile()"
        scenarioDirectoryName = unicode(self.scenarioInfo.completeBaseName())
        exportFileName = scenarioDirectoryName + ".csv"
        exportPath = config.scenarioExportsPath + exportFileName
        # if the scenario export file exists
        exportFile = QtCore.QFile(exportPath)
        error = None
        if exportFile.exists():
            try:
                exportFile.remove()
            except (IOError, OSError), e:
                error = unicode(e)
            if error:
                print error
                QtGui.QMessageBox.warning(self, 'Export Scenario Error:', 'The previously saved scenario '\
+ exportFileName + ' could not be deleted.  Please try again.')
                return False
        return True
def Main.mainwindow.MainWindow.deleteFeatures (self)
    Edit menu SLOT to delete selected features. This method handles deleting (i.e. undoing)
    edits made to editing layers, deleting features from base layers (i.e. pasting them into
    an editing layer), and a user deleting features from a layer belonging to the user.
Definition at line 1267 of file mainwindow.py.
References Main.mainwindow.MainWindow.activeVLayer, Main.mainwindow.MainWindow.attrTable, Main.mainwindow.MainWindow.canvas, Main.legend.Legend.canvas, Main.mainwindow.MainWindow.checkBaseLayerMatch(), Main.mainwindow.MainWindow.copyFeaturesShared(), Main.mainwindow.MainWindow.disableSelectActions(), Main.mainwindow.MainWindow.editDirty, Main.mainwindow.MainWindow.geom, Main.mainwindow.MainWindow.openVectorAttributeTable(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), and Main.mainwindow.MainWindow.provider.
    def deleteFeatures(self):
        '''
            Edit menu SLOT to delete selected features. This method handles deleting (i.e. undoing)
            edits made to editing layers, deleting features from base layers (i.e. pasting them into
            an editing layer), and a user deleting features from a layer belonging to the user.
         '''
        # debugging
        print "Main.mainwindow.deleteFeatures(): activeVLayer.name() is " + self.activeVLayer.name()
        # selectedFeatures() returns the selected features as a QgsFeatureList
        selectedFeats = self.activeVLayer.selectedFeatures()
        count = self.activeVLayer.selectedFeatureCount()
        # check if there are any features to delete
        if count == 0:
            title = "Delete Selected Features"
            text = "You must select at least one feature before you can delete."
            # pop up message box to inform user that nothing is selected
            QtGui.QMessageBox.information(self, title, text, QtGui.QMessageBox.Ok)
            return
        vfileName = unicode(self.activeVLayer.name())
        # Check what the user is deleting and set appropriate message
        if vfileName in config.editLayersBaseNames:
            title = "Delete Scenario Edits:"
            text = "Do you want to delete, that is undo, "  + unicode(count) + \
" scenario edit(s)?  Please note that no changes will be made to any base layer."
        elif vfileName in config.pointBaseLayersBaseNames: # deleting points from a base layer
            title = "Delete Selected Features:"
            text = "Delete " + unicode(count) + " feature(s)? Please note that no \
changes will be made to the base layer."
            if not self.checkBaseLayerMatch("Deletion Error:", "delete from"): return
        else: # deleting points from a user's layer
            title = "Delete Selected Features"
            text = "Permanently delete " + unicode(count) + " feature(s)?"
        # Now check with the user about deleting the features
        reply = QtGui.QMessageBox.question(self, title, text, QtGui.QMessageBox.Cancel|QtGui.QMessageBox.Ok)
        if reply == QtGui.QMessageBox.Ok: # if yes, then do the deletion
            if vfileName in config.pointBaseLayersBaseNames: # deleting base layer features
                # This method checks if the base layer matches the scenario edit type. The method warns the user and
                # returns false on error (title = "Deletion Error:" # (title = "Deletion Error:" text = "delete from")
                #if not self.checkBaseLayerMatch("Deletion Error:", "delete from"): return
                #else:
                # We do not allow deleting features from a base layer.  Rather, we copy
                # the features the user wants to delete, and paste them into an editing shapefile.
                self.copyFeaturesShared()
                baseLayerName = vfileName # just for code readability
                self.pasteBaseLayerDeletions(baseLayerName)
                return
            else: # handles the cases where we are deleting editing layer features or features on a user's layer
                pyList = [] # make a Python list of features to delete
                feat = QgsFeature()
                for feat in selectedFeats:
                    print "Main.mainwindow.deleteFeatures(): starting ids of deleted features " + str(feat.id())
                    pyList.append(feat.id())
                # provider.deleteFeatures only works with a Python list as a parameter.
                # Note that the spaces between the list brackets and parentheses
                # are necessary or it doesn't work!! We delete and check for error
                # in the same if statement
                if not self.provider.deleteFeatures( pyList ): # returns false on failed deletion
                    QtGui.QMessageBox.warning(self, "Failed to delete features", "Please check if " + vfileName +
                                                                    " is open in another program and then try again.")
                    return # delete failed so return
                ''' Features successfully deleted '''
                # if this is an editing layer, reset the id numbers for the layer
                if vfileName in config.editLayersBaseNames:
                    shared.resetIdNumbers(self.provider, self.geom)
                    self.editDirty = True
                # empty the selections cache when done or it stays at 'count'
                self.activeVLayer.removeSelection(False) # false indicates whether to emit a signal
                # reset the select tool
                self.disableSelectActions()
                # update all the extents for the user's layer (will close and reopen editing layer to set extents)
                shared.updateExtents(self, self.activeVLayer, self.canvas)
                # update Vector Attribute Table if open
                if self.attrTable != None and self.attrTable.isVisible():
                    self.openVectorAttributeTable()
        else: return # user has cancelled in the dialog
def Main.mainwindow.MainWindow.deleteOldCsvShapefile (self, csvPath, csvFileName)
Scenario method to delete previously written CSV shapefiles so new ones can be written
Definition at line 688 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def deleteOldCsvShapefile(self, csvPath, csvFileName):
        ''' Scenario method to delete previously written CSV shapefiles so new ones can be written '''
        # debugging
        print "Main.mainwindow.deleteOldCsvShapefile()"
        error = None
        currentCsvFile = QtCore.QFile(csvPath)
        if currentCsvFile.exists():
            print "Main.mainwindow.delteOldCSVShapefile(): currentCsvFile exists"
            try:
                currentCsvFile.remove()
            except (IOError, OSError), e:
                error = unicode(e)
            if error:
                print error
                QtGui.QMessageBox.warning(self, "Export Scenario Error:", "An old editing layer \
csv file '" + csvFileName + " could not be deleted.  Please check if the file is open in \
another program and then try again.")
                return False
        return True
def Main.mainwindow.MainWindow.deleteTempShapefile (self, path)
Removes an editing shapefile.
Definition at line 709 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def deleteTempShapefile(self, path):
        ''' Removes an editing shapefile. '''
        # debugging
        print "Main.mainwindow.deleteTempShapefile()"
        print "Main.mainwindow.deleteTempShapefile(): path is " + path
        tempFile = QtCore.QFile(path)
        if tempFile.exists():
            print "Main.mainwindow.deleteTempShapefile(): tempFile exists is True"
            writer = QgsVectorFileWriter.deleteShapeFile(path)
            if not writer: # writer returns true if delete successful
                QtGui.QMessageBox.warning(self, "File Error", "A temporary shapefile could not be deleted. \
Please try to export your scenario again.")
                return False
        return True
def Main.mainwindow.MainWindow.deselectFeatures (self)
Edit menu SLOT to clear the selected features without deleting them
Definition at line 1162 of file mainwindow.py.
    def deselectFeatures(self):
        ''' Edit menu SLOT to clear the selected features without deleting them '''
        # debugging
        print "Main.mainwindow.deselectFeatures()"
        # selectedFeatures() returns a QgsFeatureList
        count = self.activeVLayer.selectedFeatureCount()
        # check if there are any features to deselect
        if count == 0:
            title = "Deselect Features"
            text = "You must select at least one feature \
before you can deselect."
            QtGui.QMessageBox.information(self, title, text, QtGui.QMessageBox.Ok)
        else:
            # The boolean parameter "False" is whether to emit a signal or not
            self.activeVLayer.removeSelection(False)
            self.canvas.refresh()
def Main.mainwindow.MainWindow.disableEditActions (self)
Edit method to set action states
Definition at line 1736 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), and Main.mainwindow.MainWindow.editScenario().
    def disableEditActions(self):
        ''' Edit method to set action states '''
        # debugging
        print "Main.mainwindow.disableEditActions()"
        self.mpActionAddPoints.setChecked(False)
        self.mpActionAddPoints.setDisabled(True)
        self.mpActionAddLines.setChecked(False)
        self.mpActionAddLines.setDisabled(True)
        self.mpActionAddPolygons.setChecked(False)
        self.mpActionAddPolygons.setDisabled(True)
        #self.mpActionSaveEdits.setDisabled(True)
def Main.mainwindow.MainWindow.disableSelectActions (self)
Edit method to set action states
Definition at line 1749 of file mainwindow.py.
References Main.mainwindow.MainWindow.toolSelect.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.deleteFeatures(), Main.mainwindow.MainWindow.editScenario(), and Main.mainwindow.MainWindow.selectFeatures().
    def disableSelectActions(self):
        ''' Edit method to set action states '''
        # debugging
        print "Main.mainwindow.disableSelectActions()"
        self.canvas.unsetMapTool(self.toolSelect)
        # Apparently mpActionSelectFeatures--a toggled action that is part of a QActionGroup--
        # does not emit a signal if the action's state has not changed.
        self.mpActionSelectFeatures.setChecked(False)
        self.mpActionDeselectFeatures.setDisabled(True)
        self.mpActionDeselectFeatures.setChecked(False)
        self.mpActionModifyPoints.setDisabled(True)
        self.mpActionModifyPoints.setChecked(False)
        self.mpActionDeleteFeatures.setDisabled(True)
        self.mpActionDeleteFeatures.setChecked(False)
        self.mpActionCopyFeatures.setDisabled(True)
        self.mpActionCopyFeatures.setChecked(False)
def Main.mainwindow.MainWindow.displayCopiedFeatInfo (self, copyLayerProvider, allCopyAttrs, count)
An edit method that opens a dialog to display informatio about features being pasted or modified
Definition at line 1954 of file mainwindow.py.
References Main.mainwindow.MainWindow.copiedFeats, prepareforsetupexe.name, and Main.mainwindow.MainWindow.openModifyInfoWindow().
    def displayCopiedFeatInfo(self, copyLayerProvider, allCopyAttrs, count):
        ''' An edit method that opens a dialog to display informatio about features being pasted or modified '''
        # debugging
        print "Main.mainwindow.displayCopiedFeatInfo()"
        # get the data for the current feature
        copiedFeatId = self.copiedFeats[count].id()
        copiedFeat = QgsFeature()
        copyLayerProvider.featureAtId(copiedFeatId, copiedFeat, True, allCopyAttrs)
        # A QgsAttributeMap is a Python dictionary (key = field id : value =
        # the field's value as a QtCore.QVariant()object
        attrs = copiedFeat.attributeMap()
        print "Main.mainwindow.displayCopiedFeatInfo(): length of attrs is " + str(len(attrs))
        # return the features geometry as coordinates
        featGeom = copiedFeat.geometry()
        # create the text for the geometry in display window
        text = "Feature ID %d: %s\n" % (copiedFeat.id()+1, featGeom.exportToWkt())
        print "Main.mainwindow.displayCopiedFeatInfo(): The Feat ID and Wkt is " + text
        # get the field name and attribute data for each attribue and add to the text
        # fields() returns a dictionary with the field key and the name of the field
        fieldNamesDict = copyLayerProvider.fields()
        print "Main.mainwindow.displayCopiedFeatInfo(): The field names dict is "
        print fieldNamesDict
        for (key, attr) in attrs.iteritems():
            print "Main.mainwindow.displayCopiedFeatInfo(): key is: " + str(key)
            text += "%s: %s\n" % (fieldNamesDict.get(key).name(), attr.toString())
        # set the title for the display window
        title = "Unmodified Feature's Geometry and Attribute Information"
        self.openModifyInfoWindow(title, text)
def Main.mainwindow.MainWindow.editScenario (self, state)
Edit menu SLOT that handles starting and stopping editing mode
Definition at line 1438 of file mainwindow.py.
References Main.mainwindow.MainWindow.activeVLayer, Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.copyFlag, Main.mainwindow.MainWindow.disableEditActions(), Main.mainwindow.MainWindow.disableSelectActions(), Main.mainwindow.MainWindow.dlgScenarioEditTypes, Main.mainwindow.MainWindow.editDirty, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.editMode, Main.mainwindow.MainWindow.editTypeLabel, Main.mainwindow.MainWindow.scenarioEditType, Main.mainwindow.MainWindow.scenarioFileName, and Main.mainwindow_ui.Ui_MainWindow.statusBar.
    def editScenario(self, state):
        ''' Edit menu SLOT that handles starting and stopping editing mode '''
        # debugging
        print "Main.mainwindow.editScenario() " + str(state)
        if state: # True if action activated
            '''# handle user cancel
            if self.appStateChanged("startingEditing") == "Cancel":
                self.mpActionEditScenario.blockSignals(True)
                self.mpActionEditScenario.setChecked(False)
                self.mpActionEditScenario.blockSignals(False)
                return'''
            # We cannot make edits unless there is a named
            # scenario open.  Check for open scenario here.
            if not self.scenarioFileName:
                QtGui.QMessageBox.warning(self, "Scenario Editing Error", "The scenario must have a name \
before you can make edits.  Please save the current scenario or open an existing scenario.")
                self.mpActionEditScenario.blockSignals(True)
                self.mpActionEditScenario.setChecked(False)
                self.mpActionEditScenario.blockSignals(False)
                return
            # open the dialog to get the scenario edit type
            self.dlgScenarioEditTypes = DlgScenarioEditTypes(self)
            if not self.dlgScenarioEditTypes.exec_():
                print "Main.mainwindow.editScenario(): user cancelled DlgScenarioEditTypes"
                # If the user cancels, or there is an error opening the editing file then
                # uncheck the Edit Scenario button and  return
                self.mpActionEditScenario.blockSignals(True)
                self.mpActionEditScenario.setChecked(False)
                self.mpActionEditScenario.blockSignals(False)
                return
            # set the paste action
            if self.copyFlag: self.mpActionPasteFeatures.setDisabled(False)
            # add scenarioEditType to statusbar
            if self.editTypeLabel: # for insurance
                self.statusBar.removeWidget(self.editTypeLabel)
            self.editTypeLabel = QtGui.QLabel(self.statusBar)
            captureString = "Scenario edit type:  '" + self.scenarioEditType + "'"
            self.editTypeLabel.setText(captureString)
            self.statusBar.insertPermanentWidget(0, self.editTypeLabel)
        else: #False action deactivated
            # check for unsaved edits when deselecting "Edit Scenario"
            # return mpActionEditScenario to previous state on cancel
            if self.appStateChanged("stoppingEditing") == "Cancel":
                self.mpActionEditScenario.blockSignals(True)
                self.mpActionEditScenario.setChecked(True)
                self.mpActionEditScenario.blockSignals(False)
                return
            self.editMode = False
            self.editLayerName = None
            # unset the select tool
            self.mpActionSelectFeatures.setDisabled(True)
            # remo ve any selections
            if self.activeVLayer: self.activeVLayer.removeSelection(False)
            self.disableSelectActions()
            # unset the paste action (only active  in edit mode)
            self.mpActionPasteFeatures.setDisabled(True)
            # unset edit tool actions
            self.disableEditActions()
            print "Main.mainwindow.editScenario(): setDisabled = True"
            self.editDirty = False
            # remove the 'editTypeLabel' permanent message from the statusBar
            self.statusBar.removeWidget(self.editTypeLabel)
            self.editTypeLabel = None
def Main.mainwindow.MainWindow.enablePointsOrLinesOrPolygons (self)
Edit method to set action states
Definition at line 1711 of file mainwindow.py.
References Main.mainwindow.MainWindow.geom.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged().
    def enablePointsOrLinesOrPolygons(self):
        ''' Edit method to set action states '''
        if "base" in unicode(self.activeVLayer.name()): return
        if self.geom == 0:  #0 point, 1 line, 2 polygon
            self.mpActionAddPoints.setDisabled(False)
            print "Main.mainwindow.enablePointsOrLinesOrPolygons(): geom 0"
        elif self.geom == 1:
            self.mpActionAddLines.setDisabled(False)
            print "Main.mainwindow.enablePointsOrLinesOrPolygons(): geom 1"
        elif self.geom == 2:
            self.mpActionAddPolygons.setDisabled(False)
            print "Main.mainwindow.enablePointsOrLinesOrPolygons(): geom 2"
def Main.mainwindow.MainWindow.enableSelectSubActions (self)
Edit method to set action states
Definition at line 1724 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), and Main.mainwindow.MainWindow.selectFeatures().
    def enableSelectSubActions(self):
        ''' Edit method to set action states '''
        # debugging
        print "Main.mainwindow.enableSelectSubActions()"
        if unicode(self.activeVLayer.name()) in (config.pointBaseLayersBaseNames + config.editLayersBaseNames):
            self.mpActionModifyPoints.setDisabled(False)
            # cannot copy features from a base layer or edit layer, can only select and delete or modify
            self.mpActionCopyFeatures.setDisabled(True)
        else: self.mpActionCopyFeatures.setDisabled(False)
        self.mpActionDeselectFeatures.setDisabled(False)
        self.mpActionDeleteFeatures.setDisabled(False)
def Main.mainwindow.MainWindow.exportScenario (self)
Scenario menu SLOT to export scenario edits as a CSV file
Definition at line 539 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.deleteExportScenarioFile(), Main.mainwindow.MainWindow.deleteOldCsvShapefile(), Main.mainwindow.MainWindow.deleteTempShapefile(), Main.mainwindow.MainWindow.getEditLayerToExport(), Main.mainwindow.MainWindow.listScenarioEditFiles(), Main.mainwindow.MainWindow.openHiddenVectorLayer(), Main.mainwindow.MainWindow.roundGeometryValues(), Main.mainwindow.MainWindow.writeCsvExportFile(), and Main.mainwindow.MainWindow.writeCsvShapefile().
    def exportScenario(self):
        ''' Scenario menu SLOT to export scenario edits as a CSV file '''
        # debugging
        print "Main.mainwindow.exportScenario()"
        # check the app state for unsaved edits and scenario changes
        if self.appStateChanged("exportScenario") == "Cancel":
            # debugging
            print "Main.mainwindow.exportScenario(): canceling exportScenario()"
            return
        # The exportScenario() method action is only enabled if a scenario is open
        # set some needed variables
        scenarioDirectoryName = unicode(self.scenarioInfo.completeBaseName())
        scenarioDirectoryPath = config.scenariosPath + scenarioDirectoryName
        exportFileName = scenarioDirectoryName + ".csv"
        exportPath = config.scenarioExportsPath + exportFileName
        # List the edit files in the scenario's edit file directory.  Returns False if the
        # directory does not exist or is empty.  The method warns the user on errors.
        scenarioEditFileList = self.listScenarioEditFiles(scenarioDirectoryPath)
        if not scenarioEditFileList: return
        # Delete any old export files before writing a new one. This method warns the user on errors
        # and returns true if the file does not exist or has been successfully deleted.
        if not self.deleteExportScenarioFile(): return
        # Get a count of the number of editing shapefiles for use below.
        shapefileCount = 0
        for fileName in scenarioEditFileList:
            if not ".shp" in fileName: continue # only looking for the .shp files
            shapefileCount += 1
        # Iterate through the editing shapefiles in the current scenario's edit file
        # directory and write them as a CSV format shapefile.
        # Finally, append the editing CSV shapefile file to the scenario CSV export file,
        # which will consist of all edits to the current scenario in CSV format.
        exportFileWritten = False
        loopCount = 0
        for fileName in scenarioEditFileList: # a list of all files in the scenario's directory
            if not ".shp" in fileName: continue # only looking for the .shp files
            loopCount += 1
            print "Main.mainwindow.exportScenario(): The loopCount begin is " + str(loopCount)
            # get the path to write the csv file to
            csvInfo = QtCore.QFileInfo(fileName)
            csvBaseName = unicode(csvInfo.completeBaseName()) # csvBaseName = editing shapefile BaseName
            csvFileName = csvBaseName + ".csv"
            csvPath = scenarioDirectoryPath + "/" + csvFileName
            # debugging
            print "Main.mainwindow.exportScenario(): current csvBaseName is: " + csvBaseName
            print "Main.mainwindow.exportScenario(): current csvFileName is: " + csvFileName
            print "Main.mainwindow.exportScenario(): current csvPath is: " + csvPath
            print "Main.mainwindow.exportScenario(): current exportPath is: " + exportPath
            # get a handle to the editing file (returns a maplayer) so it can be converted to CSV format
            # If the layer exists in the scenario's directory but is not open in the
            # legend, the user is prompted with a warning, and the return value = False.
            vlayer = self.getEditLayerToExport(csvBaseName, scenarioDirectoryPath, fileName)
            if not vlayer: return
            # Check if there are any features in the layer because the QgsVectorFileWriter fails to
            # write the csv file if there are no features and does NOT return an error!!
            print "Main.mainwindow.chkEditLayerFeatureCount: The vlayer feature count is " + str(vlayer.featureCount())
            if vlayer.featureCount() == 0:
                # keep trying until the last layer in the scenarioEditFileList
                print "Main.mainwindow.chkEditLayerFeatureCount:: the shapefileCount is " + str(shapefileCount)
                print "Main.mainwindow.chkEditLayerFeatureCount:: the loopCount is " + str(loopCount)
                if loopCount < shapefileCount:
                    continue
                elif exportFileWritten: # loopCount = shapefileCount and something exported
                    break
                elif not exportFileWritten: # loopCount = shapefileCount and nothing exported
                    QtGui.QMessageBox.warning(self, "Export Scenario Error:", "There are no features to export.  Please \
make some edits to your scenario and try again.")
                    return
            # Delete previously written CSV shapefiles so current ones can take their place.
            # The QgsVectorFileWriter will not overwrite existing files.
            # Return if deletion fails (deleteOldCsvSapefile() warns on error)
            if not self.deleteOldCsvShapefile(csvPath, csvFileName): return
            # Delete any old temporary shapefiles that may exist.  This is a double check against a deletion error below.
            writePath = config.scenarioExportsPath + 'tempVlayer'
            deletePath = writePath + '.shp'
            if not self.deleteTempShapefile(deletePath): return
            # create a temporary copy of the vlayer to avoid rounding values in the permanent editing layer.
            error = QgsVectorFileWriter.writeAsVectorFormat(vlayer, writePath, "utf-8", None, "ESRI Shapefile" )
            if error != QgsVectorFileWriter.NoError:
                QtGui.QMessageBox.warning(self, "File write error", "A needed temporary file could \
not be written. Please try again.")
                return
            readPath = writePath + '.shp'
            tempVlayer = self.openHiddenVectorLayer(readPath)
            if not tempVlayer: return
            # round values to shorten csv file output (roundGeometryValues() warns on error)
            tempVlayer = self.roundGeometryValues(tempVlayer)
            if not tempVlayer: return
            ''' Convert the editing shapefiles to CSV format '''
            # Returns False if the write operation failed and writeCsvShapefile warns on error
            if not self.writeCsvShapefile(tempVlayer, csvPath, csvFileName): return
            # Close the temporary shapefile so that it can be deleted
            tempVlayer = None
            # Delete the temporary shapefile
            self.deleteTempShapefile(deletePath)
            ''' Now append the CSV shapefile text to the CSV file to be exported to UMass (use Python) '''
            # writeCsvExportFile returns True if successful False if not and warns user on error
            exportFileWritten = self.writeCsvExportFile(exportPath, csvPath, exportFileName)
            if not exportFileWritten: return
        # We have exited the for loop, so let the user know things worked.
        exportFileInfo = QtCore.QFileInfo(exportPath)
        findExportPath = exportFileInfo.absolutePath()
        QtGui.QMessageBox.information(self, 'Export Scenario Succeeded:', "The export file is named "\
def Main.mainwindow.MainWindow.getAttsForPastedOrModifiedFeats (self, pastedFeatureIds, editLayer, tempOriginalEditFeats, msgFlag, modifyFlag)
    This is the core edit method for the modify/paste features functionality of the application.
    This method gets and writes attributes for features that the user is pasting from their own layer.
    It also gets and writes attributes for base layer features that are being modified.
    Finally, this method will get and write attributes for editing layer features that the user wants to modify.
    This method also calls methods that provide the user with information about features being modified.
Definition at line 1561 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.modifyEditLayerFeatures(), Main.mainwindow.MainWindow.pasteFeatures(), and Main.mainwindow.MainWindow.pasteModifiedBaseLayerFeats().
    def getAttsForPastedOrModifiedFeats(self, pastedFeatureIds, editLayer, tempOriginalEditFeats, msgFlag, modifyFlag):
        '''
            This is the core edit method for the modify/paste features functionality of the application.
            This method gets and writes attributes for features that the user is pasting from their own layer.
            It also gets and writes attributes for base layer features that are being modified.
            Finally, this method will get and write attributes for editing layer features that the user wants to modify.
            This method also calls methods that provide the user with information about features being modified.
        '''
        # debugging
        print "Main.mainwindow.getAttsForPastedOrModifiedFeats()"
        self.msgFlag = msgFlag # msgFlag can be "baselayer", "userlayer" or  "editlayer"
        self.tempOriginalEditFeats = tempOriginalEditFeats
        self.modifyFlag = modifyFlag # Currently true or false
        # set some variables based on recording the id of the layer features were copied from
        # The id was recorded in Main.mainwindow.copyFeaturesShared().
        editLayerProvider = editLayer.dataProvider()
        copyLayer = self.copyLayer
        copyLayerName = unicode(copyLayer.name())
        #self.copyLayerName = unicode(copyLayer.name())
        # this is the same as the editLayerProvider if edit layer features are being modified
        copyLayerProvider = copyLayer.dataProvider()
        allCopyAttrs = copyLayerProvider.attributeIndexes()
        self.reply = None
        # pastedFeatureIds are actually selected feature ids when modifying edit layer features
        for count, featId in enumerate(pastedFeatureIds):
            print "Main.mainwindow.getAttsForPastedOrModifiedFeats(): feat.id is " + str(featId)
            # select the feature
            editLayer.setSelectedFeatures( [featId] )
            self.canvas.zoomToSelected(self.activeVLayer)
            # set the extent so that the user can see some surrounding features
            self.setPastingExtent()
            # open the Add Attributes dialog
            self.dlgAddAtts = DlgAddAttributes(self)
            self.dlgAddAtts.setGeometry(0, 500, 200, 200)
            # display information about the copied feature for reference when adding new attributes
            self.displayCopiedFeatInfo(copyLayerProvider, allCopyAttrs, count)
            # This dialog's "reject()" method is overridden to warn the user about aborting the paste or
            # modify operation.  If the user choses NOT to abort the method returns to the dialog and the
            # user can continue where they left off.  If the user chooses to abort,
            #  the reject() method closes the dialog and returns False.
            if self.dlgAddAtts.exec_(): # open DlgAddAttributes and then if user clicks OK it returns true
                # if this is an editing layer modification, we need to get the type of edit so that we can
                # mark it correctly in the attribute table.
                if msgFlag == "editlayer" and self.copiedFeatGeom == 0: # points edit layer
                    modifyFlag = self.isAlteredFeature(editLayer, featId) # returns True if altered, otherwise False
                # if "modified" the points are new pasted base layer modifications or edit layer points that were modifications
                if modifyFlag:
                    # if user is modifying a point, set the altered field to 'y' by passing 'True' flag
                    attributes = self.dlgAddAtts.getNewAttributes(True)
                else: attributes = self.dlgAddAtts.getNewAttributes() # flag False for pasting user feats, modifying edits
                changedAttributes = {featId : attributes} # create a "QgsChangedAttributesMap"
                try:
                    editLayerProvider.changeAttributeValues(changedAttributes) # here is the "write" operation
                except (IOError, OSError), e:
                    error = unicode(e)
                    print "Main.mainwindow.getAttsForPastedOrModifiedFeats(): error is " + error
                    title = "Failed to modify attributes:"
                    editLayerName = editLayer.name()
                    QtGui.QMessageBox.warning(self, title, "Please check if "
                                + editLayerName + " is open in another program and then start again.")
                    # Make sure we delete any features that may have been added to the editing layer and clean up.
                    # In the case of modifying editing layer features, the tempOriginalEditFeats are the same as
                    # the current features on the editing layer so nothing will be deleted.
                    shared.deleteEdits(self, editLayerName, tempOriginalEditFeats)
                    if msgFlag == "editlayer": self.setPasteModifySuccess(True) # some features may have been modified
                    else: self.setPasteModifyDone() # all pastes have been deleted
                    self.windModifyInfo.close()
                    # reset the active layer to the base layer being modified
                    if modifyFlag: self.setBaseLayerActive(copyLayerName)
                    return False
                self.activeVLayer.removeSelection(False) # false means do not emit signal
                self.canvas.refresh()
                if self.windModifyInfo and count == len(pastedFeatureIds) - 1:
                    self.windModifyInfo.close()
                continue
            else : # dlgAddAtts.reject() returns False (user chose to discard changes)
                # reverse the edits
                editLayerName = editLayer.name()
                # Make sure we delete any features that may have been added to the editing layer and clean up.
                # In the case of modifying editing layer features, the tempOriginalEditFeats are the same as
                # the current features on the editing layer so nothing will be deleted.
                shared.deleteEdits(self, editLayerName, tempOriginalEditFeats)
                if msgFlag == "editlayer": self.setPasteModifySuccess(True) # some features have been modified
                else: self.setPasteModifyDone() # all pastes have been deleted
                #self.mpActionModifyPoints.setDisabled(True)
                self.windModifyInfo.close()
                # reset the active layer to the base layer being modified
                if modifyFlag: self.setBaseLayerActive(copyLayerName)
                return False
                #else: continue # if reply is no, self.dlgAddAtts remains active and the loop continues
        # loop ended successfully so
        return True
def Main.mainwindow.MainWindow.getCurrentLayers (self)
Get the layers currently registered in the QgsMapLayerRegistry
Definition at line 2919 of file mainwindow.py.
References Main.mainwindow.MainWindow.currentLayers.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.getCurrentLayersNames(), Main.mainwindow.MainWindow.getLayerFromName(), Main.mainwindow.MainWindow.getOriginalScenarioLayers(), and Main.mainwindow.MainWindow.setScenarioSaved().
    def getCurrentLayers(self):
        ''' Get the layers currently registered in the QgsMapLayerRegistry '''
        # debugging
        print "Main.mainwindow.getCurrentLayers()"
        self.currentLayers = {}
        # note: returns a dictionary of QgsMapLayers
        self.currentLayers = QgsMapLayerRegistry.instance().mapLayers()
        return self.currentLayers
def Main.mainwindow.MainWindow.getCurrentLayersCount (self)
Definition at line 2900 of file mainwindow.py.
References Main.mainwindow.MainWindow.currentLayersCount.
Referenced by Main.mainwindow.MainWindow.setScenarioDirty().
    def getCurrentLayersCount(self):
        # debugging
        print "Main.mainwindow.getCurrentLayersCount()"
        self.currentLayersCount = None
        self.currentLayersCount = QgsMapLayerRegistry.instance().count()
        return self.currentLayersCount
def Main.mainwindow.MainWindow.getCurrentLayersNames (self)
Definition at line 2929 of file mainwindow.py.
References Main.mainwindow.MainWindow.getCurrentLayers().
Referenced by Main.mainwindow.MainWindow.checkScenarioState(), and Main.mainwindow.MainWindow.setScenarioDirty().
    def getCurrentLayersNames(self):
        # debugging
        print "Main.mainwindow.getCurrentLayersNames()"
        currentLayersNames = []
        for layer in self.getCurrentLayers().values():
            currentLayersNames.append(layer.name())
        return currentLayersNames
def Main.mainwindow.MainWindow.getEditFields (self, geom)
Definition at line 2950 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), and Main.mainwindow.MainWindow.pasteEmptyFeatures().
    def getEditFields(self, geom):
        # debugging
        print "Main.mainwindow.getEditFields()"
        # 0 point, 1 line, 2 polygon
        if geom == 0: editFields = config.editPointsFields
        elif geom == 1: editFields = config.editLinesFields
        elif geom == 2: editFields = config.editPolygonsFields
        return editFields
def Main.mainwindow.MainWindow.getEditLayerToExport (self, csvBaseName, scenarioDirectoryPath, fileName)
Scenario method to get the layer id of an editing layer to convert to CSV format
Definition at line 667 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def getEditLayerToExport(self, csvBaseName, scenarioDirectoryPath, fileName):
        '''Scenario method to get the layer id of an editing layer to convert to CSV format '''
        # debugging
        print "Main.mainwindow.getEditLayerToExport"
        items = self.legend.findItems(csvBaseName, QtCore.Qt.MatchFixedString, 0)
        print "Main.mainwindow.exportScenario(): length of items list is " + str(len(items))
        if len(items) == 0:
            # This should never happen.  If an editing layer exists in the scenario's directory
            # then it should be open because removing an editing layer from the legend deletes
            # it from the file system. This would be some sort of user error, if it happened.
            QtGui.QMessageBox.warning(self, 'Export Scenario Error:', "An editing shapefile named " \
+ fileName + " exists in " + scenarioDirectoryPath + " , but is not open in the layer list panel. \
You must either delete this editing layer, or open it if it contains features you wish to be part \
of your scenario export file.")
            return None
        else:
            vlayerId = items[0].layerId
            vlayer = QgsMapLayerRegistry.instance().mapLayer(vlayerId)
            return vlayer
def Main.mainwindow.MainWindow.getGeometryName (self, layerGeom)
Definition at line 2908 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.pasteFeatures().
    def getGeometryName(self, layerGeom):
        # debugging
        print "Main.mainwindow.getGeometryName()"
        geometry = "No Geometry"
        if layerGeom != None: # None if raster loaded
            if layerGeom == 0: geometry = "point(s)"
            elif layerGeom == 1: geometry = "line(s)"
            elif layerGeom == 2: geometry = "polygon(s)"
            else: geometry = "Unknown Geometry"
            return geometry
def Main.mainwindow.MainWindow.getLayerFromName (self, layerName)
Definition at line 2939 of file mainwindow.py.
References Main.mainwindow.MainWindow.getCurrentLayers().
Referenced by Main.mainwindow.MainWindow.checkScenarioState(), Main.mainwindow.MainWindow.modifyEditLayerFeatures(), Main.mainwindow.MainWindow.modifyFeatures(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), Main.mainwindow.MainWindow.pasteEmptyFeatures(), Main.mainwindow.MainWindow.pasteFeatures(), Main.mainwindow.MainWindow.pasteModifiedBaseLayerFeats(), and Main.mainwindow.MainWindow.setPasteModifySuccess().
    def getLayerFromName(self, layerName):
        # debugging
        print "Main.mainwindow.getLayerFromName()"
        for layer in self.getCurrentLayers().values():
            if layerName == layer.name(): return layer
        else:
            QtGui.QMessageBox.warning(self, "Get Layer Error:", "The layer "
                                                    + layerName + " is not open in the layer list panel.")
            return False
def Main.mainwindow.MainWindow.getOriginalScenarioLayers (self, i, count)
This scenario method is called when a scenario is opened.  The call
    originates each time QgsProject emits a "layerLoaded" signal
Definition at line 806 of file mainwindow.py.
References Main.mainwindow.MainWindow.getCurrentLayers(), Main.mainwindow.MainWindow.getOriginalScenarioLayersNames(), Main.mainwindow.MainWindow.originalScenarioLayers, and Main.mainwindow.MainWindow.origScenarioLyrsLoaded.
    def getOriginalScenarioLayers(self, i, count):
        ''' This scenario method is called when a scenario is opened.  The call
            originates each time QgsProject emits a "layerLoaded" signal
        '''
        # debugging
        print "Main.mainwindow.getOriginalScenarioLayers()"
        print "Main.mainwindow.getOriginalScenarioLayers(): int begin " + str(i)
        print "Main.mainwindow.getOriginalScenarioLayers(): count " + str(count)
        # QgsProject SIGNAL starts with i = 0, and no layer has been loaded yet.
        # The SIGNAL emits a count of the number of layers to be loaded (say = 3)
        # on the first signal.  After that we get 1,3; 2,3; and 3,3 for parameters
        # for a 3 layer scenario file.  In the end self.originalScenarioLayers has 3 values.
        if i == count:
            self.originalScenarioLayers = []
            # The line below fails when layers are hidden in the layer list panel
            #self.originalScenarioLayers = self.canvas.layers()
            # self.getCurrentLayers() returns a dictionary of QgsMapLayers
            # self.originalScenarioLayers is a list of QgsMapLayer objects
            self.originalScenarioLayers = self.getCurrentLayers().values()
            # This method sets the instance variable self.getOriginalScenarioLayersNames
            self.getOriginalScenarioLayersNames()
            self.origScenarioLyrsLoaded = True
            # inform user of missing layers
            if len(self.originalScenarioLayers) < count:
                QtGui.QMessageBox.warning(self, "File Error", "Some layers in the scenario have \
failed to load. Either the file name or the location of the file has probably changed. You may reload \
missing files by using the 'Add Vector Layer' or 'Add Raster Layer buttons.'")
        # debugging
        print "Main.mainwindow.getOriginalScenarioLayers(): originalScenarioLayers are "
        for layer in self.originalScenarioLayers: print layer.name()
        print "Main.mainwindow.getOriginalScenarioLayers() currentLayers are "
        if i > 0:
            for layer in self.getCurrentLayers().values(): print layer.name()
def Main.mainwindow.MainWindow.getOriginalScenarioLayersNames (self)
Definition at line 797 of file mainwindow.py.
References Main.mainwindow.MainWindow.originalScenarioLayers, and Main.mainwindow.MainWindow.originalScenarioLayersNames.
Referenced by Main.mainwindow.MainWindow.getOriginalScenarioLayers(), and Main.mainwindow.MainWindow.setScenarioSaved().
    def getOriginalScenarioLayersNames(self):
        # debugging
        print "Main.mainwindow.getOriginalScenarioLayersNames()"
        self.originalScenarioLayersNames = []
        for layer in self.originalScenarioLayers:
            self.originalScenarioLayersNames.append(unicode(layer.name())) # change QString to unicode
        return self.originalScenarioLayersNames
def Main.mainwindow.MainWindow.identifyFeatures (self, state)
View menu SLOT to handle the identify features tool
Definition at line 2251 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.toolIdentify.
    def identifyFeatures(self, state):
        ''' View menu SLOT to handle the identify features tool'''
        # debugging
        print "Main.mainwindow.identifyFeatures()"
        if state: # for action selected state = True
            print "Main.mainwindow.identifyFeatures() state is True"
            # Need this to handle if user tries to addVector while adding a line or polygon
            # check app state and handle user cancel
            if self.appStateChanged("identifyFeatures") == "Cancel":
                return
            # identifyFeatures action is selected so enable this tool
            self.canvas.setMapTool(self.toolIdentify)
        else: # action deselected (state = False)
            print "Main.mainwindow.identifyFeatures() state is false"
            self.canvas.unsetMapTool(self.toolIdentify)
def Main.mainwindow.MainWindow.isAlteredFeature (self, editLayer, featId)
    This edit method checks whether editing layer features that the user wishes to modify
    match the current scenario edit type.
Definition at line 2138 of file mainwindow.py.
    def isAlteredFeature(self, editLayer, featId):
        '''
            This edit method checks whether editing layer features that the user wishes to modify
            match the current scenario edit type.
        '''
        # debugging
        print "Main.mainwindow.isAlteredFeature()"
        editLayerProvider = editLayer.dataProvider()
        allAttrs = editLayerProvider.attributeIndexes()
        feat = QgsFeature()
        if not editLayerProvider.featureAtId(featId, feat, False, allAttrs):
            QtGui.QMessageBox.warning(self, "Modify Edits Error", "This feature could not be found. Please deselect \
these features and try again.")
        attrs = feat.attributeMap()
        subcount = None
        for key, value in attrs.iteritems():
            print "Main.mainwindow.isAlteredFeature(): key = " + str(key)
            print "Main.mainwindow.isAlteredFeature(): subcount = " + str(subcount)
            print "Main.mainwindow.isAlteredFeature(): The value is " + value.toString()
            if unicode(value.toString()) == "": continue
            elif subcount == None:
                subcount = key
                print "Main.mainwindow.isAlteredFeature(): subcount first set at " + str(subcount)
                continue
            if key == subcount + 1 and unicode(value.toString()) == "y":
                return True
            else: return False
def Main.mainwindow.MainWindow.listScenarioEditFiles (self, scenarioDirectoryPath)
A scenario method to list the files in the scenario's edit file directory
Definition at line 769 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def listScenarioEditFiles(self, scenarioDirectoryPath):
        ''' A scenario method to list the files in the scenario's edit file directory '''
        #debugging
        print "Main.mainwindow.listScenarioEditFiles()"
        error = None
        try: # trap error if directory is missing for some reason
            scenarioDirectoryList = os.listdir(scenarioDirectoryPath) # use Python os module here
        except (IOError, OSError), e:
            error = e
            if error:
                print error
                QtGui.QMessageBox.warning(self, "Export Scenario Error:", "The files in this \
scenario's directory could not be listed.  Please save the scenario and try again")
                return False
        # We only want editing shapefiles not any existing csv shapefiles
        scenarioEditFileList = []
        for afile in scenarioDirectoryList:
            if afile.endswith('.shp'):
                scenarioEditFileList.append(afile)
        if scenarioEditFileList == []:
            QtGui.QMessageBox.warning(self, "Export Scenario Error:", "You have not made any scenario edits to export. \
Please choose 'Edit Scenario' from the Edit menu, make some edits, and then try again.")
            return False
        else: return scenarioEditFileList
def Main.mainwindow.MainWindow.makeScenarioDirectory (self)
Scenario method to create a directory to store a scenario's editing files
Definition at line 968 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.copyScenario(), Main.mainwindow.MainWindow.saveScenario(), and Main.mainwindow.MainWindow.saveScenarioAs().
    def makeScenarioDirectory(self):
        ''' Scenario method to create a directory to store a scenario's editing files '''
        # debugging
        print "Main.mainwindow.makeScenarioDirectory()"
        # We are creating a new scenario, so remove any old edit files directory
        # (and files), or exported scenarios with same name.
        scenarioDirectoryName = self.scenarioInfo.completeBaseName()
        dirPath = unicode(self.scenarioInfo.path() + "/" + scenarioDirectoryName)
        exportFileName = unicode(scenarioDirectoryName + ".csv")
        exportPath = unicode(config.scenarioExportsPath + exportFileName)
        # debugging
        print "Main.mainwindow.makeScenarioDirectory(): scenarioDirectoryName is " + str(scenarioDirectoryName)
        print "Main.mainwindow.makeScenarioDirectory(): directoryPath is " + str(dirPath)
        error = None
        if QtCore.QDir(config.scenariosPath + scenarioDirectoryName).exists():
            try:
                if os.path.exists(exportPath):
                    os.remove(exportPath) # use Python here
                shutil.rmtree(dirPath)
                # Give the os some time to delete files before trying to create new directory
                # with the same name
                time.sleep(1)
            except (IOError, OSError), e:
                error = unicode(e)
            if error:
                print e
                QtGui.QMessageBox.warning(self, "Deletion error:", "The scenario editing \
file directory or export files could not be completely removed. Please check if one of the \
files in the scenario is open in another program and then try again.")
                return "Error"
        # now make the new directory
        if QtCore.QDir().mkdir(config.scenariosPath + scenarioDirectoryName):
                print "Main.mainwindow.makeScenarioDirectory(): directory made"
        else:
            QtGui.QMessageBox.warning(self, "Failed to create directory:", "The scenario \
editing file directory could not be created. Please try to save the project again, or save it with a \
different name.")
            return "Error"
def Main.mainwindow.MainWindow.manageProjects (self)
Project menu SLOT
Definition at line 278 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.dlgManageProjects.
    def manageProjects(self):
        ''' Project menu SLOT '''
        # debugging
        print "Main.mainwindow.manageProjects()"
        # check for unsaved edits and scenario changes
        if self.appStateChanged("manageProjects") == "Cancel":
            # debugging
            print "canceling Main.mainwindow.manageProjects()"
            return
        self.dlgManageProjects = DlgManageProjects(self)
        self.dlgManageProjects.exec_()
def Main.mainwindow.MainWindow.modifyEditLayerFeatures (self)
This edit method provides the ability to modify features on editing layers of all geometry types.
Definition at line 2067 of file mainwindow.py.
References Main.mainwindow.MainWindow.copiedFeats, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.getAttsForPastedOrModifiedFeats(), Main.mainwindow.MainWindow.getLayerFromName(), Main.mainwindow.MainWindow.originalEditLayerFeats, and Main.mainwindow.MainWindow.setPasteModifySuccess().
Referenced by Main.mainwindow.MainWindow.modifyFeatures().
    def modifyEditLayerFeatures(self):
        ''' This edit method provides the ability to modify features on editing layers of all geometry types. '''
        # debugging
        print "Main.mainwindow.modifyEditLayerFeatures()"
        # So we have some edit layer features copied and the user wants to modify them.
        # first get  a list of the copied feature ids so they can be selected
        copiedFeatIds = []
        for feat in self.copiedFeats: copiedFeatIds.append(feat.id())
        print "Main.mainwindow.modifyEditLayerFeatures(): copiedFeatIds are "
        print copiedFeatIds
        # next get the editLayer
        editLayer = self.getLayerFromName(self.editLayerName)
        # Now call this method, which gives the user info about the features they are modifying,
        # and also opens the Add Attributes dialog, which allows them to input the attribute changes.
        # Setting the self.originalEditLayerFeats parameter, which is the current state of editing layer features,
        # ensures that no features will be deleted if the user chooses "cancel" when modifying attributes.
        # This method warns the user and returns False on error
        if not self.getAttsForPastedOrModifiedFeats(copiedFeatIds, editLayer, self.originalEditLayerFeats, "editlayer", False):
            return
        # now clean up and renumber the features
        self.setPasteModifySuccess(True)
def Main.mainwindow.MainWindow.modifyFeatures (self)
Edit menu SLOT to allow the user to modify points on base layers and features on any editing layer
Definition at line 1201 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.checkBaseLayerMatch(), Main.mainwindow.MainWindow.checkEditFeatureMatch(), Main.mainwindow.MainWindow.checkForDeletions(), Main.mainwindow.MainWindow.copyFeaturesShared(), Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.getLayerFromName(), Main.mainwindow.MainWindow.modifyEditLayerFeatures(), Main.mainwindow.MainWindow.pasteModifiedBaseLayerFeats(), and Main.mainwindow.MainWindow.scenarioEditType.
    def modifyFeatures(self):
        ''' Edit menu SLOT to allow the user to modify points on base layers and features on any editing layer'''
        # debugging
        print "Main.mainwindow.modifyFeatures()"
        # check if there are any features selected to modify
        count = self.activeVLayer.selectedFeatureCount()
        if count == 0:
            title = "Modify Selected Features"
            text = "You must select at least one feature on the points base layer or \
or an editing layer for the current scenario edit type before you can modify it. \
If you have correctly selected points and you get this message then you need to make \
sure that the layer you want to modify is the currently active layer."
            # pop up message box to inform user that nothing is selected
            QtGui.QMessageBox.information(self, title, text, QtGui.QMessageBox.Ok)
            return
        # Note that the "Modify Features" action only becomes enabled when a
        # base layer or editing layer is active.
        # Check whether we are modifying base layer or editing layer features.
        name = unicode(self.activeVLayer.name())
        if name in config.pointBaseLayersBaseNames:
            # Now check if the base layer  matches the scenario edit type.  If it does not, we get
            # incorrect entries in the editing shapefile attribute table! The method warns on error.
            title = "Modify Point Error:"
            text = "modify"
            if not self.checkBaseLayerMatch(title, text): return
            # We have features selected from the correct base layer, so copy them
            self.copyFeaturesShared()
            # Warn if "edit_scenario(points).shp if it is not open. If open, make it the activeLayer
            items = self.legend.findItems(config.editLayersBaseNames[0], QtCore.Qt.MatchFixedString, 0)
            if len(items) == 0:
                QtGui.QMessageBox.warning(self, "Modify Selected Error", "The 'edit_scenario(points)' layer \
must be open for you to modify point features.  Please click the 'Edit Scenario' button twice, choose the \
scenario edit type that has the features you wish to modify, and then try again.")
                return
            else:
                # **  could the user have moved the edit points layer?? Should I move to the top?? **
                self.legend.setCurrentItem(items[0])
                self.legend.currentItem().setCheckState(0, QtCore.Qt.Checked)
                self.pasteModifiedBaseLayerFeats()
        elif name in config.editLayersBaseNames:
            # Force the user to save or discard unsaved edits before we bother to modify them.
            if self.appStateChanged("modifyingEdits") == "Cancel":
                    return
            # check if editing layer chosen is correct for the current scenario edit type
            # (this method warns the user and returns false if no match)
            if not shared.checkSelectedLayer(self, self.scenarioEditType, name):
                return
            # So we have the edit layer for the current scenario edit type but do the selected features
            # all match the current scenario edit type?
            editLayer = self.getLayerFromName(self.editLayerName) # use the instance variable as a double check
            features = editLayer.selectedFeatures()
            print "Main.mainwindow.modifyFeatures(): The selected feature count is " + str(editLayer.selectedFeatureCount())
            # This method checks if the attribute values for all the selected features match the
            # current scenario edit type. The method warns and returns false if one or more do not match.
            if not self.checkEditFeatureMatch(editLayer, features):
                return
            # Now check for a user attempting to delete "deletions" on a point editing layer
            if editLayer.geometryType() == 0:
                if not self.checkForDeletions(editLayer, features):
                    return
            # so we have proper features of the current scenario edit type to modify
            self.copyFeaturesShared()
            self.modifyEditLayerFeatures()
def Main.mainwindow.MainWindow.newScenario (self)
Scenario menu SLOT
Definition at line 304 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.scenarioDirty, and Main.mainwindow.MainWindow.setInitialAppState().
    def newScenario(self):
        ''' Scenario menu SLOT '''
        # debugging
        print "Main.mainwindow.newScenario()"
        print "Main.mainwindow.newScenario() start dirty? " + str(self.scenarioDirty)
        # check for unsaved edits and scenario changes
        if self.appStateChanged("newScenario") == "Cancel":
            # debugging
            print "canceling Main.mainwindow.newScenario()"
            return
        # new scenario so remove layers from the legend and the canvas layer set
        self.legend.removeAll()
        # remove all layers from the QgsMapLayerRegistry
        QgsMapLayerRegistry.instance().removeAllMapLayers()
        # go back to app opening state
        self.setInitialAppState()
        # debugging
        print "Main.mainwindow.newScenario() end dirty? " + str(self.scenarioDirty)
def Main.mainwindow.MainWindow.openHiddenVectorLayer (self, vfilePath)
Definition at line 2985 of file mainwindow.py.
References Main.mainwindow.MainWindow.checkLayerLoadError().
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def openHiddenVectorLayer(self, vfilePath):
        # debugging
        print "Main.mainwindow.openHiddenVectorLayer()"
        # create the file info object to get info about the vfile
        info = QtCore.QFileInfo(vfilePath)
        #create the layer
        #QFileInfo.completeBaseName() returns just the filename
        try:
            vlayer = QgsVectorLayer(vfilePath, info.completeBaseName(), "ogr")
        except (IOError, OSError), e:
            error = unicode(e)
            print error
            QtGui.QMessageBox.warning(self, 'File error:', 'A needed vector layer could not be opened. \
Please try to export your scenario again.')
            return False
        # double check for error using qgis methods
        if not self.checkLayerLoadError(vlayer): return False
        else: return vlayer
def Main.mainwindow.MainWindow.openModifyInfoWindow (self, title, text)
An edit method to create the window to display information about a vector or raster layer
Definition at line 1984 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.displayCopiedFeatInfo().
    def openModifyInfoWindow(self, title, text):
        ''' An edit method to create the window to display information about a vector or raster layer '''
        # debugging
        print "Main.mainwindow.identify.displayInformation()"
        # See Main.mainwindow.openRasterCategoryTable() for a description of the following code:
        self.windModifyInfo = QtGui.QDockWidget(title, self.dlgAddAtts)
        self.windModifyInfo.setFloating(True)
        self.windModifyInfo.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.windModifyInfo.setMinimumSize(QtCore.QSize(450, 300))
        self.windModifyInfo.show()
        self.textBrowserModifyInfo = QtGui.QTextBrowser()
        self.textBrowserModifyInfo.setWordWrapMode(QtGui.QTextOption.NoWrap)
        self.textBrowserModifyInfo.setFontPointSize(9.0)
        self.textBrowserModifyInfo.setText(text)
        self.windModifyInfo.setWidget(self.textBrowserModifyInfo)
def Main.mainwindow.MainWindow.openOrientingLayers (self)
Open orienting layers when the app is started
Definition at line 3024 of file mainwindow.py.
References Main.mainwindow.MainWindow.openingOrientingLayers, Main.mainwindow.MainWindow.openRasterLayer(), and Main.mainwindow.MainWindow.openVectorLayer().
Referenced by Main.mainwindow.MainWindow.setInitialAppState().
    def openOrientingLayers(self):
        ''' Open orienting layers when the app is started '''
        path = config.baseLayersPath
        # debugging
        info = QtCore.QFileInfo(path)
        path2 = info.absolutePath()
        path3 = info.absoluteFilePath()
        path4 = info.canonicalFilePath()
        print "Main.mainwindow.openOrientingLayers(): The config path is " + path
        print "Main.mainwindow.openOrientingLayers(): The absolutePath of config is " + path2
        print "Main.mainwindow.openOrientingLayers(): The absoluteFilePath of config is " + path3
        print "Main.mainwindow.openOrientingLayers(): The canonicalFilePath of config is " + path4
        vlayers = config.orientingVectorLayers
        rlayers = config.orientingRasterLayers
        # layers opened first will be on the bottom of the layer list panel
        for rlayer in rlayers:
            tempPath = None
            tempPath = path + rlayer
            # QGIS 1.73 was not interpreting ./ correctly.  When the tempPath = ./base_layers/someraster.tif
            # QGIS writes ./base_layers/someraster.tif to the scenario file (i.e. the '.cap' file).  When QGIS opens the
            # project file, it interprets ./ to be the "Scenarios" directory where the .cap file is located rather than the
            # program directory where the base_files are located. This is corrected when the raster files are opened using
            # absolute file path.  In that case, QGIS writes '../' to the scenario file and layers open properly.  The two
            # lies below convert the relative paths to absolute paths so that config.baseLayersPath can remain "./base_layers/"
            # If there are problems with the Windows installer, I could convert all paths to absolute paths to solve the problem.
            print "Main.mainwindow.openOrientingLayers(): The tempPath is " + tempPath
            #print "The absolute file path is " + info.absoluteFilePath()
            self.openingOrientingLayers = True
            self.openRasterLayer(tempPath)
        for vlayer in vlayers:
            tempPath = None
            tempPath = path + vlayer
            print "Main.mainwindow.openOrientingLayers(): The tempPath is " + tempPath
            self.openingOrientingLayers = True
            self.openVectorLayer(tempPath)
        # all orienting layers opened so set flag
        self.openingOrientingLayers = False
def Main.mainwindow.MainWindow.openRasterCategoryTable (self)
Layer menu SLOT to handle opening the raster category table
Definition at line 2324 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.browserRaster, and Main.mainwindow.MainWindow.dwRasterTable.
    def openRasterCategoryTable(self):
        ''' Layer menu SLOT to handle opening the raster category table '''
        # debugging
        print "Main.mainwindow.openRasterCategoryTable()"
        # Need this to handle if user tries to addVector while adding a line or polygon
        # check app state and handle user cancel
        if self.appStateChanged("openRasterCategoryTable") == "Cancel":
            return
        # Raster Categories file kept in the Base_layers folder
        fname = "./RasterCategoryTable.htm"
        # use a QDockWidget to create floating window
        # with the MainWindow as parent
        self.dwRasterTable = QtGui.QDockWidget("Raster Category Tables", self)
        self.dwRasterTable.setFloating(True)
        # The line below prevents the dock widget from distorting the window when dragged.
        self.dwRasterTable.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dwRasterTable.setMinimumSize(QtCore.QSize(800, 600))
        # Show the QDockWidget and make it a separate floating window
        self.dwRasterTable.show()
        # create a QTextBrowser to display the file
        # *Note: using QTextBrowser alone
        # results in an orphaned window that the app does not close
        self.browserRaster = QtGui.QTextBrowser()
        # Open the file and create a text stream to read
        fh = QtCore.QFile(fname)
        if not fh.open(QtCore.QIODevice.ReadOnly): raise IOError, unicode(fh.errorString())
        stream = QtCore.QTextStream(fh)
        # add the QTextBrowser to the QDockWidget
        self.dwRasterTable.setWidget(self.browserRaster)
        # display the html file in the browser
        self.browserRaster.setHtml(stream.readAll())
        self.browserRaster.setFontPointSize(20.0)
        #self.browser.setSizePolicy()
def Main.mainwindow.MainWindow.openRasterLayer (self, rfilePath)
Open a raster layer
Definition at line 3005 of file mainwindow.py.
References Main.mainwindow.MainWindow.checkLayerLoadError().
Referenced by Main.mainwindow.MainWindow.addRasterLayer(), and Main.mainwindow.MainWindow.openOrientingLayers().
    def openRasterLayer(self, rfilePath):
        ''' Open a raster layer '''
        # debugging
        print 'Main.mainwindow.MainWindow.openRasterLayer()'
        info = QtCore.QFileInfo(rfilePath)
        try:
            rlayer = QgsRasterLayer(info.filePath(), info.completeBaseName())
        except (IOError, OSError), e:
            error = unicode(e)
            print error
        # double check for error using qgis methods
        if not self.checkLayerLoadError(rlayer): return False
        # add layer to layer registry and set extent
        reg = QgsMapLayerRegistry.instance()
        reg.addMapLayer(rlayer)
def Main.mainwindow.MainWindow.openScenario (self)
Scenario menu SLOT
Definition at line 327 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.arrangeOrientingLayers(), Main.legend.LegendItem.openingScenario, Main.mainwindow.MainWindow.openingScenario, Main.mainwindow.MainWindow.originalScenarioLayers, Main.mainwindow.MainWindow.scenarioDirty, Main.mainwindow.MainWindow.scenarioFileName, Main.mainwindow.MainWindow.scenarioFilePath, Main.mainwindow.MainWindow.scenarioInfo, Main.dlgscenarioedittypes.DlgScenarioEditTypes.scenarioInfo, and Main.mainwindow.MainWindow.setInitialAppState().
    def openScenario(self):
        ''' Scenario menu SLOT '''
        # debugging
        print "Main.mainwindow.openScenario()"
        print "Main.mainwindow.openScenario() self.scenarioDirty begin is " + str(self.scenarioDirty)
        # check for unsaved edits and scenario changes
        if self.appStateChanged("openScenario") == "Cancel":
            # debugging
            print "canceling Main.mainwindow.openScenario()"
            return
        # open file dialog to find scenarios to open
        qd = QtGui.QFileDialog()
        filterString = "CAPS Scenario (*.cap)" # syntax for showing all files \nAll Files(*)")
        # get the path to the directory for the saved file using Python
        directory = os.path.dirname(config.scenariosPath)
        # Convert QStrings to unicode unless they are used immediately in a Qt method.
        # This ensures that we never ask Python to slice a QString, which produces a type error.
        scenarioFilePath = unicode(qd.getOpenFileName(self, QtCore.QString
                                                ("Open Scenario"), directory, filterString))
        # Check for cancel of file dialog
        if len(scenarioFilePath) == 0: return
        # So we are going to open a saved scenario.  Set initial app state to start.
        self.setInitialAppState(False)
        # Remember the file info to use elsewhere, change to unicode in case
        # we need to use Python string operations somewhere (they do not work on QString types)
        self.scenarioFilePath = scenarioFilePath # unicode
        self.scenarioInfo = QtCore.QFileInfo(scenarioFilePath) # an object
        # get the filename without the path
        self.scenarioFileName = unicode(self.scenarioInfo.fileName())
        #debugging
        print "Main.mainwindow.openScenario() " + scenarioFilePath
        # remove old layers from the legend and the canvas layer set
        self.legend.removeAll()
        # remove all layers from the registry
        QgsMapLayerRegistry.instance().removeAllMapLayers()
        # set the originalScenarioLayers to None
        self.originalScenarioLayers = []
        # debugging
        print "Main.mainwindow.openScenario() after remove registry count " + str(QgsMapLayerRegistry.instance().count())
        # Set a flag to indicate a scenario is opening.  This flag is used in
        # Main.legend.LegendItem() class to help set layer visibility
        self.openingScenario = True
        # Create a scenario instance and read the scenario from disk.
        # Note that QgsProject gets the extents, creates map layers and registers them
        scenario = QgsProject.instance()
        scenario.read(self.scenarioInfo)
        # check for error
        if scenario.error():
                QtGui.QMessageBox.warning(self, "File Error", "CAPS cannot read this file.")
                # QgsProject has no "close()" method, so, if error, close the project instance
                scenario = None
                return
        else: # no error so we have newly opened scenario but note that it might have no layers!
            scenario = None # close the instance of QgsProject
            self.openingScenario = False
        # The scenario file (i.e. *.cap) does not save the files in order so:
        self.arrangeOrientingLayers()
        # give the user some file info
        self.setWindowTitle("Conservation Assessment and \
Prioritization System (CAPS) Scenario Builder - " + self.scenarioFileName)
        # debugging
        print "Main.mainwindow.openScenario() after scenario load registry count " + str(QgsMapLayerRegistry.instance().count())
        print "Main.mainwindow.openScenario() scenario filename is " + self.scenarioFileName
        print "Main.mainwindow.openScenario() end dirty? " + str(self.scenarioDirty)
def Main.mainwindow.MainWindow.openVectorAttributeTable (self)
Layer menu SLOT to handle opening the vector attribute table
Definition at line 2365 of file mainwindow.py.
References Main.mainwindow.MainWindow.activeVLayer, Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.attrTable, and Main.mainwindow.MainWindow.dwAttrTable.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.checkEditsState(), Main.mainwindow.MainWindow.deleteFeatures(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), and Main.mainwindow.MainWindow.setPasteModifySuccess().
    def openVectorAttributeTable(self):
        ''' Layer menu SLOT to handle opening the vector attribute table '''
        # debugging
        print "Main.mainwindow.openVectorAttributeTable()"
        # Need this to handle if user tries to addVector while adding a line or polygon
        # check app state and handle user cancel
        if self.appStateChanged("openVectorAttributeTable") == "Cancel":
            return
        if not self.activeVLayer:
            return
        if unicode(self.activeVLayer.name()) == config.slowLoadingLayers[0]:
            reply = QtGui.QMessageBox.question(self, "Vector Attribute Table", "This layer's \
attribute table is very large and can take a few seconds to load.  Do you want to continue?",
                                                    QtGui.QMessageBox.Cancel|QtGui.QMessageBox.Yes)
            if reply == QtGui.QMessageBox.Cancel: return
        names = []
        feat = QgsFeature()
        # get the field names
        fields = self.provider.fields()
        for value in fields.itervalues():
            names.append( unicode(value.name()) )
        # configure the table to the activeVLayer
        self.attrTable = QtGui.QTableWidget()
        self.attrTable.clear()
        self.attrTable.setRowCount(self.activeVLayer.featureCount())
        self.attrTable.setColumnCount(self.provider.fieldCount())
        self.attrTable.setHorizontalHeaderLabels((names))
        self.attrTable.setEditTriggers(QtGui.QTableWidget.NoEditTriggers)
        self.attrTable.setSelectionBehavior(QtGui.QTableWidget.SelectRows)
        self.attrTable.setSelectionMode(QtGui.QTableWidget.SingleSelection)
        # get all the geographic and attribute data
        allAttrs = self.provider.attributeIndexes()
        # the select() method initializes retrieval of data
        self.provider.select(allAttrs)
        # populate the table with attribute data
        # the nextFeature() method operates on a "provider.select()" initialized provider
        setItem = self.attrTable.setItem
        item = QtGui.QTableWidgetItem
        while self.provider.nextFeature(feat):
            # attrs is a dictionary: key = field index, value = QgsFeatureAttribute
            featId = feat.id()
            attrMap = feat.attributeMap()
            for k, attr in attrMap.iteritems():
                setItem(featId, k, item(attr.toString())) # feat.id() = row, key = the column number
        self.attrTable.resizeColumnsToContents()
        self.attrTable.setMinimumSize(QtCore.QSize(400,250))
        #self.attrTable.adjustSize()
        # Show the QDockWidget and make it a separate floating window
        # (Need a dock widget to handle separate window properly)
        # if it is already open don't open another window
        if self.dwAttrTable == None:
            # debugging
            print "Main.mainwindow.openVectorAttributeTable(): dwAttrTable not open"
            self.dwAttrTable = QtGui.QDockWidget("Vector Attribute Table", self)
            self.dwAttrTable.setFloating(True)
            self.dwAttrTable.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
            self.dwAttrTable.setMinimumSize(QtCore.QSize(400,250))
            self.dwAttrTable.show()
            # add the attribute table to the dock widget
        elif self.dwAttrTable.isHidden():
            self.dwAttrTable.setMinimumSize(QtCore.QSize(400,250))
            self.dwAttrTable.show()
        self.dwAttrTable.setWidget(self.attrTable)
        self.dwAttrTable.setMinimumSize(QtCore.QSize(400,250))
        self.dwAttrTable.setSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        #self.dwAttrTable.adjustSize()
        self.dwAttrTable.show()
def Main.mainwindow.MainWindow.openVectorLayer (self, vfilePath)
Open a vector layer
Definition at line 2961 of file mainwindow.py.
References Main.mainwindow.MainWindow.activeVLayer, and Main.mainwindow.MainWindow.checkLayerLoadError().
Referenced by Main.mainwindow.MainWindow.addVectorLayer(), Main.mainwindow.MainWindow.copyScenario(), and Main.mainwindow.MainWindow.openOrientingLayers().
    def openVectorLayer(self, vfilePath):
        ''' Open a vector layer '''
        # debugging
        print "Main.mainwindow.openVectorLayer()"
        print "Main.mainwindow.openVectorLayer(): vfilePath is " + vfilePath
        # create the file info object to get info about the vfile
        info = QtCore.QFileInfo(vfilePath)
        #create the layer
        #QFileInfo.completeBaseName() returns just the filename without the extension
        try:
            vlayer = QgsVectorLayer(vfilePath, info.completeBaseName(), "ogr")
        except (IOError, OSError), e:
            error = unicode(e)
            print error
        # This double checks for loading errors and pops up a message box if the layer doesn't open
        if not self.checkLayerLoadError(vlayer): return False
        # add layer to layer registry and set extent if necessary
        QgsMapLayerRegistry.instance().addMapLayer(vlayer)
        self.activeVLayer = vlayer
        return True
def Main.mainwindow.MainWindow.pan (self, state)
View menu SLOT
Definition at line 2222 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.toolPan.
    def pan(self, state):
        ''' View menu SLOT '''
        # debugging
        print "Main.mainwindow.pan " + str(state)
        if state:
            # Need this to handle if user tries to addVector while adding a line or polygon
            # check app state and handle user cancel
            if self.appStateChanged("pan") == "Cancel":
                return
            self.canvas.setMapTool(self.toolPan)
        else: self.canvas.unsetMapTool(self.toolPan)
def Main.mainwindow.MainWindow.pasteBaseLayerDeletions (self, baseLayerName)
This edit method adds attribute data to pasted base layer deletions
Definition at line 1790 of file mainwindow.py.
References Main.mainwindow.MainWindow.attrTable, Main.mainwindow.MainWindow.canvas, Main.legend.Legend.canvas, Main.mainwindow.MainWindow.copiedFeatCount, Main.mainwindow.MainWindow.copiedFeats, Main.mainwindow.MainWindow.editDirty, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.getEditFields(), Main.mainwindow.MainWindow.getLayerFromName(), Main.mainwindow.MainWindow.openVectorAttributeTable(), Main.mainwindow.MainWindow.scenarioEditType, Main.mainwindow.MainWindow.setBaseLayerActive(), and Main.mainwindow.MainWindow.setPasteModifyDone().
Referenced by Main.mainwindow.MainWindow.deleteFeatures().
    def pasteBaseLayerDeletions(self, baseLayerName):
        ''' This edit method adds attribute data to pasted base layer deletions '''
        # debugging
        print "Main.mainwindow.pasteBaseLayerDeletions()"
        # Check if "edit_scenario(points) is open, and if not then warn.
        editingLayerName = config.editLayersBaseNames[0]
        items = self.legend.findItems(editingLayerName, QtCore.Qt.MatchFixedString, 0)
        print "Main.mainwindow.pasteBaseLayerDeletions(): length of item list is " + str(len(items))
        if len(items) > 0:
            self.legend.setCurrentItem(items[0])
            self.legend.currentItem().setCheckState(0, QtCore.Qt.Checked) # so we made edit_scenario(points).shp the active layer
        else:
            QtGui.QMessageBox.warning(self, "File Error", "The 'edit_scenario(points)' layer \
must be open for you to complete this action.  Please click 'Edit Scenario' twice, select \
the appropriate scenario edit type, and try again.")
            return
        # even though we know the active layer is edit_scenario(points) and self.provider is the correct provider
        # let's set the provider from self.editLayerName just to guard against any bugs.
        editLayer = self.getLayerFromName(self.editLayerName)
        editLayerProvider = editLayer.dataProvider()
        # debugging
        print "Main.mainwindow.pasteBaseLayerDeletions(): featureCount begin = " + str(self.copiedFeatCount)
        # get the list of fields for the current scenario edit type
        for (count, scenarioEditType) in enumerate(config.scenarioEditTypesList):
            if scenarioEditType == self.scenarioEditType:
                inputFieldNames = eval("config.inputFieldNames" + str(count))
                break
        # debugging
        print "Main.mainwindow.pasteBaseLayerDeletions(): inputFieldNames are:"
        print inputFieldNames
        # get a list of all the editing layer attribute fields for the
        # geometry type associated with the deleted features
        geom = editLayer.geometryType()
        editFields = self.getEditFields(geom)
        a = {} # Python dictionary of attributes for the current editing layer
        # Simply add an id value and set the altered field to n and the deleted field to 'y'
        feat = QgsFeature()
        for feat in self.copiedFeats:
            subListCount = 1 # this keeps track of where we are in the inputFieldNames list
            print "Main.mainwindow.pasteBaseLayerDeletions(): feat.id is " + str(feat.id())
            for (count, field) in enumerate(editFields):
                # Fields that are in the editing shapefile but are not used for
                # the current scenario type are set to empty values here.
                if field not in inputFieldNames:
                    a[count] = QtCore.QVariant()
                    print "Main.mainwindow.pasteBaseLayerDeletions(): not in field names count = " + str(count)
                    continue
                # set the id field first
                if subListCount == 1:
                    a[count] = QtCore.QVariant(1)
                    subListCount = 2
                    print "Main.mainwindow.pasteBaseLayerDeletions(): first field (id) count = " + str(count)
                    continue
                # if a point layer, set the altered and deleted fields
                if geom == 0 and subListCount == 2:
                    a[count] = QtCore.QVariant("n")
                    subListCount = 3
                    print "Main.mainwindow.pasteBaseLayerDeletions(): second field (altered) count = " + str(count)
                    continue
                if geom == 0 and subListCount == 3:
                    a[count] = QtCore.QVariant("y")
                    print "Main.mainwindow.pasteBaseLayerDeletions(): third field (deleted) count = " + str(count)
                    subListCount = 4
                    continue
                # set the rest of the input fields to empty for deleted features
                a[count] = QtCore.QVariant()
                print "Main.mainwindow.pasteBaseLayerDeletions(): Set the remaining input field to empty, count = " + str(count)
            feat.setAttributeMap(a)
            try:
                editLayerProvider.addFeatures( [feat] )
            except (IOError, OSError), e:
                error = unicode(e)
                print error
                QtGui.QMessageBox.warning(self, "Failed to paste feature(s)", "Please check if "
                                 + self.editLayerName + " is open in another program and then try again.")
        # reorder the id numbers
        shared.resetIdNumbers(editLayerProvider, geom)
        # Set the editDirty flag so that the user will be prompted to save edits or not.
        # self.originalEditLayerFeats will be called when the edits (i.e. pasted features) are saved, so
        # saved, so we don't need to do that here.
        self.editDirty = True
        self.mpActionSaveEdits.setDisabled(False)
        # the paste action is turned on in copyFeatures
        # it is turned off here or in pasteFeatures
        self.setPasteModifyDone()
        # update Vector Attribute Table if open
        if self.attrTable != None and self.attrTable.isVisible():
            self.openVectorAttributeTable()
        # update the extents and refresh so the features show (this will close and reopen the editing layer)
        shared.updateExtents(self, editLayer, self.canvas)
        # reset the base layer to be the active layer
        self.setBaseLayerActive(baseLayerName)
def Main.mainwindow.MainWindow.pasteEmptyFeatures (self, editLayerProvider)
An edit method that creates empty attributes for the current edit layer geometry,
    associates the empty attributes with the feature geometry and pastes the features.
Definition at line 1893 of file mainwindow.py.
References Main.mainwindow.MainWindow.copiedFeats, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.getEditFields(), and Main.mainwindow.MainWindow.getLayerFromName().
Referenced by Main.mainwindow.MainWindow.pasteFeatures(), and Main.mainwindow.MainWindow.pasteModifiedBaseLayerFeats().
    def pasteEmptyFeatures(self, editLayerProvider):
        ''' An edit method that creates empty attributes for the current edit layer geometry,
            associates the empty attributes with the feature geometry and pastes the features.
        '''
        # debugging
        print "Main.mainwindow.pasteEmptyFeatures()"
        # We can paste features from a user's layer of any geometry type into an editing
        # layer, so get the list of editing shapefile fields for the current scenario edit type.
        geom = self.getLayerFromName(self.editLayerName).geometryType()
        editFields = self.getEditFields(geom)
        # Create an attribute map (a python dictionary) of empty values
        # for the current editing shapefile.
        keys = range(len(editFields))
        values = [QtCore.QVariant()]*len(editFields)
        attributes = dict(zip(keys, values))
        # debugging
        print "Main.mainwindow.pasteEmptyFeatures(): The empty attributes are:"
        print attributes
        # Set the attributes of the features to empty and paste.
        # Pasting features with empty attributes allows us to select each
        # feature on the map canvas when the user inputs data for that feature.
        feat = QgsFeature()
        for feat in self.copiedFeats:
            feat.setAttributeMap(attributes)
            try:
                editLayerProvider.addFeatures( [feat] )
            except (IOError, OSError), e:
                error = unicode(e)
                print error
                QtGui.QMessageBox.warning(self, "Failed to paste feature(s)", "Please check if "
                            + self.editLayerName + " is open in another program and then try again.")
                return False
        else: return True
def Main.mainwindow.MainWindow.pasteFeatures (self)
    Edit menu SLOT. This method handles pasting features from a user's file into an editing shapefile.
    Pasting features can only be done in "Edit Scenario" mode.  Features
    can be copied from any user's file, but can only be pasted into an editing shapefile.
Definition at line 1350 of file mainwindow.py.
References Main.mainwindow.MainWindow.checkPastedFeatureConstraints(), Main.mainwindow.MainWindow.copiedFeatCount, Main.mainwindow.MainWindow.copiedFeatGeom, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.geom, Main.mainwindow.MainWindow.getAttsForPastedOrModifiedFeats(), Main.mainwindow.MainWindow.getGeometryName(), Main.mainwindow.MainWindow.getLayerFromName(), Main.mainwindow.MainWindow.pasteEmptyFeatures(), Main.mainwindow.MainWindow.scenarioEditType, and Main.mainwindow.MainWindow.setPasteModifySuccess().
    def pasteFeatures(self):
        '''
            Edit menu SLOT. This method handles pasting features from a user's file into an editing shapefile.
            Pasting features can only be done in "Edit Scenario" mode.  Features
            can be copied from any user's file, but can only be pasted into an editing shapefile.
        '''
        # debugging
        print "Main.mainwindow.pasteFeatures()"
        print "Main.mainwindow.pasteFeatures(): copied feat count = " + str(self.copiedFeatCount)
        print "Main.mainwindow.pasteFeatures(): copied feat geometry " + str(self.copiedFeatGeom)
        print "Main.mainwindow.pasteFeatures(): self.geom is " + str(self.geom)
        ''' CHECK FOR USER ERROR AND SET INTIAL CONDITIONS '''
        # Check if user has chosen the correct editing shapefile to paste to
        vlayerName = unicode(self.activeVLayer.name())
        # This method checks if the active layer is the baselayer that corresponds to the current scenario edit type.
        # The method warns the user and returns False on error.
        if not shared.checkSelectedLayer(self, self.scenarioEditType, vlayerName):
            return
        # The activeVLayer is the correct editing layer, but for insurance against any bugs, use the name
        # of the current edit Layer set by DlgScenarioEditTypeswhen the scenario edit type was chosen
        editLayerName = self.editLayerName
        editLayer = self.getLayerFromName(editLayerName)
        editLayerProvider = editLayer.dataProvider()
        # Inform user if attempting to paste into incompatible layer type. This can happen if the user
        # copies features from a layer with different geometry than the current scenario edit type.
        copyGeom = self.getGeometryName(self.copiedFeatGeom)
        activeGeom = self.getGeometryName(self.geom) #0 point, 1 line, 2 polygon
        if self.geom != None:
            if self.geom != self.copiedFeatGeom:
                title = "Paste Features"
                text = "You cannot paste " + copyGeom + " into a " + activeGeom + " vector layer."
                QtGui.QMessageBox.information(self, title, text, QtGui.QMessageBox.Ok)
                return
        # If a pasted point(s) or lines, make sure constraints are met.  Method checks point and line features.
        # The method warns user and returns False if constraints are not met
        if not self.checkPastedFeatureConstraints():
            return
        # Now that we have good features and a correct layer to paste to:
        # The user could have added features or made other edits to the editing layer without
        # saving them as of yet, so we cannot use the variable self.originalEditLayerFeats here.
        # Rather, we set tempOriginalFeats (the list of ids of current edit layer features)
        # in case the user wants to cancel the pasting process and discard the pasted features below.
        tempOriginalEditFeats = shared.listOriginalFeatures(self, editLayerName)
        '''
            PASTE THE FEATURES WITH EMPTY ATTRIBUTE DATA SO THEY CAN BE SELECTED ON THE
            MAP CANVAS WHEN THE USER INPUTS NEW ATTRIBUTE DATA FOR EACH FEATURE.
        '''
        # We can paste points, lines or polygons so we get the field names for the scenario edit
        # type, set the attributes of the pasted features to empty and paste into the editing layer.
        # Pasting features with empty attributes allows us to select each
        # feature on the map canvas when the user inputs data for that feature.
        if not self.pasteEmptyFeatures(editLayerProvider):
            return
        # The provider gives the pasted features new id's when they are added
        # to the editing shapefile.  Here we compare the editing layer's feature ids
        # before and after pasting and then return the difference between the two
        # to get the new ids.  pastedFeatureIDS is a python list.
        pastedFeatureIds = shared.getFeatsToDelete(editLayerProvider, tempOriginalEditFeats)
        print "Main.mainwindow.pasteFeatures(): The pasteFeatureIDS[] are:"
        print pastedFeatureIds
        '''
            WE NEED TO ITERATE THROUGH THE PASTED FEATURES, SELECT EACH ONE
            ON THE MAP CANVAS(FOR THE USER'S CONVENIENCE), OPEN THE "ADD ATTRIBUTES" DIALOG
            AND GET THE USER INPUT DATA FOR EACH FEATURE.
        '''
        # This method opens the Add Attributes dialog and a window to provide the user with information about the
        # feature she is pasting.  It warns the user and returns False on error
        if not self.getAttsForPastedOrModifiedFeats(pastedFeatureIds, editLayer, tempOriginalEditFeats, "userlayer", False):
            return
        '''PASTING COMPLETED, SO DO SOME HOUSEKEEPING '''
        self.setPasteModifySuccess()
def Main.mainwindow.MainWindow.pasteModifiedBaseLayerFeats (self)
An edit method to paste modified base layer features
Definition at line 2001 of file mainwindow.py.
References Main.mainwindow.MainWindow.copyLayer, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.getAttsForPastedOrModifiedFeats(), Main.mainwindow.MainWindow.getLayerFromName(), Main.mainwindow.MainWindow.pasteEmptyFeatures(), Main.mainwindow.MainWindow.setBaseLayerActive(), and Main.mainwindow.MainWindow.setPasteModifySuccess().
Referenced by Main.mainwindow.MainWindow.modifyFeatures().
    def pasteModifiedBaseLayerFeats(self):
        ''' An edit method to paste modified base layer features '''
        # debugging
        print "Main.mainwindow.pasteModifiedFeatures()"
        '''
            This method handles the user choosing the "Modify Features" action after selecting
            features from the base layer corresponding to the current scenario edit type.
            Note that this method duplicates some code and commenting in Main.mainwindow.pasteFeatures(),
            but we accept the extra code to reduce confusion and facilitate debugging and future modifications.
        '''
        # debugging
        print "Main.mainwindow.pasteModifiedBaseLayerFeats()"
        # If we are modifying a point, we checked that the base layer matched the scenario edit type
        # and programmatically selected the correct edit layer to paste to in Main.mainwindow.modifyFeatures()
        # self.editLayerName was set by DlgScenarioEditTypeswhen the scenario edit type was chosen.
        editLayerName = self.editLayerName
        editLayer = self.getLayerFromName(editLayerName)
        editLayerProvider = editLayer.dataProvider()
        # Set some variables based on recording the id of the layer features were copied from.
        # The id was recorded in Main.mainwindow.copyFeaturesShared().
        copyLayer = self.copyLayer
        copyLayerName = unicode(copyLayer.name())
        # Set tempOriginalFeats (the list of ids of current edit layer features)
        # in case the user wants to delete the pasted features below.
        tempOriginalEditFeats = shared.listOriginalFeatures(self, editLayerName)
        '''
            PASTE THE FEATURES WITH EMPTY ATTRIBUTE DATA SO THEY CAN BE SELECTED ON THE
            MAP CANVAS WHEN THE USER INPUTS NEW ATTRIBUTE DATA FOR EACH FEATURE.
        '''
        # Set the attributes of the features to empty and paste into the editing layer.
        # Pasting features with empty attributes allows us to select each
        # feature on the map canvas when the user inputs data for that feature.
        if not self.pasteEmptyFeatures(editLayerProvider):
            return
        # The provider gives the pasted features new id's when they are added
        # to the editing shapefile.  Here we compare the editing layer's feature ids
        # before and after pasting and then return the difference between the two
        # to get the new ids.  pastedFeatureIDS is a python list.
        pastedFeatureIds = shared.getFeatsToDelete(editLayerProvider, tempOriginalEditFeats)
        '''
            WE NEED TO ITERATE THROUGH THE PASTED FEATURES, SELECT EACH ONE
            ON THE MAP CANVAS(FOR THE USER'S CONVENIENCE), OPEN THE "ADD ATTRIBUTES" DIALOG
            AND GET THE USER INPUT DATA FOR EACH FEATURE.
        '''
        # This method opens the Add Attributes dialog and a window to provide the user with information
        # about the feature she is pasting.  It warns the user and returns False on error
        if not self.getAttsForPastedOrModifiedFeats(pastedFeatureIds, editLayer, tempOriginalEditFeats, "baselayer", True):
            return
        '''PASTING COMPLETED, SO DO SOME HOUSEKEEPING '''
        # reset the layer we were copying or modifying to be the active layer
        self.setPasteModifySuccess()
        self.setBaseLayerActive(copyLayerName)
def Main.mainwindow.MainWindow.printFeatures (self)
Testing
Definition at line 3349 of file mainwindow.py.
    def printFeatures(self):
        ''' Testing '''
        # debugging
        print "Main.mainwindow.printFields(): Testing"
        provider = self.activeVLayer.dataProvider()
        provider.reloadData()
        feat = QgsFeature()
        #self.featsAdded = 5
        #provider.deleteFeatures( [3, 4] )
        #self.canvas.refresh()
        #check if our feature was really written to the file
        print provider.featureCount()
        # get all the data for the layer (a QgsAttributeList)
        allAttrs = provider.attributeIndexes()
        # the select() method initializes retrieval of data
        provider.select(allAttrs)
        # the nextFeature() method operates on a select initialized provider
        while provider.nextFeature(feat):
            # fetch the feature geometry, which is the feature's spatial coordinates
            fgeom = feat.geometry()
            # This prints the feature's ID and its spatial coordinates
            print "Feature ID %d: %s\n" % (feat.id(), fgeom.exportToWkt())
            print type(feat.id())
            # a QgsAttributeMap is a pointer to a series of QtCore.QVariant objects
            attrs = feat.attributeMap()
            # the map first prints the Qgs feature ID and
            # then it prints the field key (starting with 0 for the first field) and the field's value.
            # note: the QgsAttribute map is a Python dictionary (key = field id : field value)
            for (key, attr) in attrs.iteritems():
                print "%d: %s" % (key, attr.toString())
def Main.mainwindow.MainWindow.printFields (self)
Testing
Definition at line 3328 of file mainwindow.py.
    def printFields(self):
        ''' Testing '''
        # debugging
        print "Main.mainwindow.printFields(): Testing"
        #field = QgsField()
        names = []
        provider = self.activeVLayer.dataProvider()
        provider.reloadData()
        fields = provider.fields()
        print fields
        for value in fields.itervalues():
            print value
            print unicode( value )
            print unicode(value.name())
            print value.name()
            names.append( unicode(value.name()) )
        print names
        print fields.values()
def Main.mainwindow_ui.Ui_MainWindow.retranslateUi (self, MainWindow) [inherited]
Definition at line 307 of file mainwindow_ui.py.
Referenced by Tools.dlgaddattributes_ui.Ui_dlgAddAttributes.setupUi().
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Conservation Assessment and Prioritization System (CAPS) Scenario Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.menuScenario.setTitle(QtGui.QApplication.translate("MainWindow", "Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLayer.setTitle(QtGui.QApplication.translate("MainWindow", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddRasterLayer.setText(QtGui.QApplication.translate("MainWindow", "Add Raster Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionNewScenario.setText(QtGui.QApplication.translate("MainWindow", "New Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionNewScenario.setIconText(QtGui.QApplication.translate("MainWindow", "New Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionNewScenario.setToolTip(QtGui.QApplication.translate("MainWindow", "New Scenario: create a new scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddVectorLayer.setText(QtGui.QApplication.translate("MainWindow", "Add Vector Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddVectorLayer.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Vector Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomIn.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom In: click or draw rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionPan.setText(QtGui.QApplication.translate("MainWindow", "Pan", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomtoMapExtent.setText(QtGui.QApplication.translate("MainWindow", "Zoom to Map Extent", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomtoMapExtent.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom to Map Extent: zooms to the extent of all visible layers", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionOpenScenario.setText(QtGui.QApplication.translate("MainWindow", "Open Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionOpenScenario.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Scenario: open a previously saved scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionSaveScenario.setText(QtGui.QApplication.translate("MainWindow", "Save Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionSaveScenarioAs.setText(QtGui.QApplication.translate("MainWindow", "Save Scenario As ...", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionSaveScenarioAs.setToolTip(QtGui.QApplication.translate("MainWindow", "Save Scenario As ... : copy the open scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionSelectFeatures.setText(QtGui.QApplication.translate("MainWindow", "Select Features", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionDeleteFeatures.setText(QtGui.QApplication.translate("MainWindow", "Delete Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionDeleteFeatures.setToolTip(QtGui.QApplication.translate("MainWindow", "Delete Selected: delete selected features", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionPasteFeatures.setText(QtGui.QApplication.translate("MainWindow", "Paste Features", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionPasteFeatures.setToolTip(QtGui.QApplication.translate("MainWindow", "Paste Selected: paste selected features to another layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionCopyFeatures.setText(QtGui.QApplication.translate("MainWindow", "Copy Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionCopyFeatures.setToolTip(QtGui.QApplication.translate("MainWindow", "Copy Selected: copy selected features", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddPoints.setText(QtGui.QApplication.translate("MainWindow", "Add Points", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddLines.setText(QtGui.QApplication.translate("MainWindow", "Add Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddPolygons.setText(QtGui.QApplication.translate("MainWindow", "Add Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionExportScenario.setText(QtGui.QApplication.translate("MainWindow", "Export Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionExportScenario.setToolTip(QtGui.QApplication.translate("MainWindow", "Export Scenario: make file to send to the CAPS staff", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionOpenRasterCategoryTable.setText(QtGui.QApplication.translate("MainWindow", "Open Raster Category Tables", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionOpenVectorAttributeTable.setText(QtGui.QApplication.translate("MainWindow", "Open Vector Attribute Table", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionEditScenario.setText(QtGui.QApplication.translate("MainWindow", "Edit Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionEditScenario.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit Scenario: open a dialog to choose/change the scenario edit type", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionSaveEdits.setText(QtGui.QApplication.translate("MainWindow", "Save Edits", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionSaveEdits.setToolTip(QtGui.QApplication.translate("MainWindow", "Save Edits: save your scenario changes", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionDeselectFeatures.setText(QtGui.QApplication.translate("MainWindow", "Deselect Features", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAppExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionIdentifyFeatures.setText(QtGui.QApplication.translate("MainWindow", "Identify Features", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionIdentifyFeatures.setToolTip(QtGui.QApplication.translate("MainWindow", "Identify Features: get feature attributes and raster values", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionModifyPoints.setText(QtGui.QApplication.translate("MainWindow", "Modify Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionModifyPoints.setToolTip(QtGui.QApplication.translate("MainWindow", "Modify selected base layer points", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionManageProjects.setText(QtGui.QApplication.translate("MainWindow", "Manage Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionManageProjects.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Projects: Create, modify or discard a project.", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionSftpProperties.setText(QtGui.QApplication.translate("MainWindow", "SFTP Properties", None, QtGui.QApplication.UnicodeUTF8))
def Main.mainwindow.MainWindow.roundGeometryValues (self, vlayer)
Rounds geometry values of editing layers just before converting to csv layers
Definition at line 3238 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def roundGeometryValues(self, vlayer):
        ''' Rounds geometry values of editing layers just before converting to csv layers '''
        # debug
        print "Main.mainwindow.roundGeometryValues()"
        provider = vlayer.dataProvider()
        feat = QgsFeature()
        allAttrs = provider.attributeIndexes()
        provider.select(allAttrs)
        retval = False
        if vlayer.geometryType() == 0: # point
            roundPointGeom = None
            while provider.nextFeature(feat):
                point = feat.geometry().asPoint()
                roundPointGeom = QgsGeometry.fromPoint(QgsPoint(round(point.x(), 2), round(point.y(), 2)))
                retval = provider.changeGeometryValues({feat.id(): roundPointGeom})
        elif vlayer.geometryType() == 1: # line
            while provider.nextFeature(feat):
                roundedLine = []
                line = feat.geometry().asPolyline()
                for point in line:
                    roundedLine.append(QgsPoint(round(point.x(), 2), round(point.y(), 2)))
                retval = provider.changeGeometryValues({feat.id(): QgsGeometry.fromPolyline(roundedLine)})
        elif vlayer.geometryType() == 2: # polygon
            while provider.nextFeature(feat):
                # a list of lists because polygons can have nested polygons
                allPolygons = feat.geometry().asPolygon()
                allPolygonsRounded = []
                for polygon in (allPolygons):
                    roundedPolygon = []
                    for point in polygon:
                        roundedPolygon.append(QgsPoint(round(point.x(), 2), round(point.y(), 2)))
                    allPolygonsRounded.append(roundedPolygon)
                retval = provider.changeGeometryValues({feat.id(): QgsGeometry.fromPolygon(allPolygonsRounded)})
                print allPolygonsRounded
        if retval: return vlayer
        else:
            QtGui.QMessageBox.warning(self, "Export Scenario Error:", "Rounding the coordinate values in the \
CSV export file failed. Please try again.")
            return False
def Main.mainwindow.MainWindow.saveEdits (self)
Edit menu SLOT that manages the save edits action
Definition at line 1534 of file mainwindow.py.
References Main.mainwindow.MainWindow.editDirty, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.originalEditLayerFeats, Main.mainwindow.MainWindow.scenarioDirty, and Main.mainwindow.MainWindow.setScenarioDirty().
Referenced by Main.mainwindow.MainWindow.checkEditsState().
    def saveEdits(self):
        ''' Edit menu SLOT that manages the save edits action'''
        # debugging
        print "Main.mainwindow.saveEdits(): self.scenarioDirty begin is " + str(self.scenarioDirty)
        print "Main.mainwindow.saveEdits(): self.editDirty begin is " + str(self.editDirty)
        # This gives a save message only if the user clicks the Save Edits action
        # and there are no edits to save.
        title = "Save Edits"
        if not self.editDirty:
            text = "You have not made any edits to save!"
            QtGui.QMessageBox.information(self, title, text, QtGui.QMessageBox.Ok)
        # The editing tools save the edits to disk as they are made. So, to delete
        # new features, we list the original features when editing starts and delete
        # any feature not in the list.  To save features, we just run listOriginalFeatures
        # again with the editing layer
        self.originalEditLayerFeats = shared.listOriginalFeatures(self, self.editLayerName)
        # Set "Save Edits" action to disabled to let user know edits are saved.
        # Clean up
        self.mpActionSaveEdits.setDisabled(True)
        self.setScenarioDirty()
        self.editDirty = False
def Main.mainwindow.MainWindow.saveScenario (self)
Scenario menu SLOT
Definition at line 405 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.makeScenarioDirectory(), Main.mainwindow.MainWindow.saveScenarioAs(), Main.mainwindow.MainWindow.scenarioDirty, Main.mainwindow.MainWindow.scenarioFilePath, Main.mainwindow.MainWindow.scenarioInfo, Main.dlgscenarioedittypes.DlgScenarioEditTypes.scenarioInfo, and Main.mainwindow.MainWindow.setScenarioSaved().
Referenced by Main.mainwindow.MainWindow.checkScenarioState(), and Main.mainwindow.MainWindow.saveScenarioAs().
    def saveScenario(self):
        ''' Scenario menu SLOT '''
        # debugging
        print "Main.mainwindow.saveScenario() start dirty? " + str(self.scenarioDirty)
        # check for unsaved edits
        if self.appStateChanged("saveScenario") == "Cancel":
            # debugging
            print "canceling Main.mainwindow.openScenario()"
            return
        # if there is an open project to save
        if self.scenarioFilePath:
            # check if there is a scenario directory
            scenarioDirectoryName = self.scenarioInfo.completeBaseName() # returns a QString
            # PyQt handles concatenating a Python string and a QString
            if not QtCore.QDir(config.scenariosPath + scenarioDirectoryName).exists():
                self.makeScenarioDirectory()
            # start a project instance
            scenario = QgsProject.instance()
            # try to write (save) the file
            scenario.write(self.scenarioInfo)
            # check for error
            if scenario.error():
                QtGui.QMessageBox.warning(self, "Failed to save:", "Please check if this \
scenario file is open in another program.")
                # QgsProject has no "close()" method, so, if error, close the project instance
                scenario = None
                return # return on error
            else: # no error so we have saved the scenario
                scenario = None
                self.setScenarioSaved()
                print "Main.mainwindow.saveScenario() end dirty? " + str(self.scenarioDirty)
        else: self.saveScenarioAs() # no open project so call saveScenarioAs()
def Main.mainwindow.MainWindow.saveScenarioAs (self)
    Scenario menu SLOT to save an unsaved scenario with a new name; overwrite an existing scenario
    with a different scenario; or save an existing scenario with a new name (i.e. copy).
    This method includes making a copy of the scenario's '.cap' file,
    the scenario's associated directory, any editing shapefiles in the scenario's
    directory, and any existing 'Scenario Export' files.  In other words, this makes
    a "deep" copy of all the important scenario files.
Definition at line 441 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.checkScenarioDirectoryPath(), Main.mainwindow.MainWindow.copyScenario(), Main.mainwindow.MainWindow.makeScenarioDirectory(), Main.mainwindow.MainWindow.saveScenario(), Main.mainwindow.MainWindow.scenarioDirty, Main.mainwindow.MainWindow.scenarioFilePath, Main.mainwindow.MainWindow.scenarioInfo, Main.dlgscenarioedittypes.DlgScenarioEditTypes.scenarioInfo, and Main.mainwindow.MainWindow.setScenarioSaved().
Referenced by Main.mainwindow.MainWindow.checkScenarioState(), and Main.mainwindow.MainWindow.saveScenario().
    def saveScenarioAs(self):
        '''
            Scenario menu SLOT to save an unsaved scenario with a new name; overwrite an existing scenario
            with a different scenario; or save an existing scenario with a new name (i.e. copy).
            This method includes making a copy of the scenario's '.cap' file,
            the scenario's associated directory, any editing shapefiles in the scenario's
            directory, and any existing 'Scenario Export' files.  In other words, this makes
            a "deep" copy of all the important scenario files.
        '''
        # debugging
        print "Main.mainwindow.saveScenarioAs()"
        print "Main.mainwindow.saveScenarioAs() start dirty? " + str(self.scenarioDirty)
        # check for unsaved edits and a dirty scenario
        if self.appStateChanged("saveScenarioAs") == "Cancel":
            # debugging
            print "canceling Main.mainwindow.saveScenarioAs()"
            return
        ''' GET THE FILE PATH THE USER CHOOSES '''
        qd = QtGui.QFileDialog()
        qd.setDefaultSuffix(".cap")
        filterString = "CAPS Scenario (*.cap)" #\nAll Files(*)")
        # get the path to the default scenario's directory
        defaultDir = config.scenariosPath
        # Get the new file path and change the QString to unicode so that Python
        # can slice it for the directory name.
        scenarioFilePath = unicode(qd.getSaveFileName(self, QtCore.QString
                                    ("Save scenario as ..."), defaultDir, filterString))
        # debugging
        print "scenarioFilePath is: " + scenarioFilePath
        print "defaultDir is " + defaultDir
        # Check for cancel of the file dialog
        if len(scenarioFilePath) == 0: return "Cancel"
        # The user can browse to anywhere and try to save the scenario with
        # any extension, so check for an incorrect directory or file extension
        if not self.checkScenarioDirectoryPath(defaultDir, scenarioFilePath): return
        # We have a new valid file path. We start by storing the old path (if one exists) for use
        # below and storing the new file path for use in saveScenario()
        oldScenarioFilePath = self.scenarioFilePath # unicode
        oldScenarioInfo = self.scenarioInfo # an object
        self.scenarioFilePath = scenarioFilePath # unicode
        self.scenarioInfo = QtCore.QFileInfo(scenarioFilePath)
        scenarioDirectoryName = unicode(self.scenarioInfo.completeBaseName())
        ''' CHECK FOR CONDITIONS THAT ELIMINATE THE NEED TO COPY THE SCENARIO DIRECTORY CONTENTS '''
        # This is the case where the user clicks "Save Scenario As..." to save an open scenario
        # Check if the new path is the same as the old path, and if it is, just call save
        # scenario to overwrite the scenario file. No need to do anything about editing files
        if self.scenarioFilePath == oldScenarioFilePath:
            self.saveScenario()
            print "Main.mainwindow.saveScenarioAs(): overwriting existing file"
            return
        # We are saving to a new path, so find out if there are any editing files open.
        editLayerLegendItems = []
        for editLayer in config.editLayersBaseNames:
            # This method returns a list of matches
            items = self.legend.findItems(editLayer, QtCore.Qt.MatchFixedString, 0)
            if len(items) > 0: editLayerLegendItems.append(items[0]) # a list of QTreeWidgetItems
        # If there are no editing layers open, we can just write the new editing file
        # directory, call saveScenario, and set the variables for a successfully saved
        # scenario and return. Any previously existing 'Export Scenario' file would have
        # been deleted when the editing shapefile was removed.
        # Note that this could be a case where we are saving the scenario
        # for the first time, or saving an existing scenario with a new
        # name, or overwriting an existing scenario after opening the app or after clicking
        # "New Scenario.  In each case the needed actions are the same.
        if len(editLayerLegendItems) == 0:
            self.makeScenarioDirectory()
            self.saveScenario()
            self.setScenarioSaved()
            return
        '''
            WE NEED TO COPY THE SCENARIO DIRECTORY'S CONTENTS (I.E. EDITING SHAPEFILES)
            AND ANY EXISTING EXPORT SCENARIO FILE
        '''
        self.copyScenario(oldScenarioInfo, scenarioDirectoryName, editLayerLegendItems)
        ''' NOW DO SOME HOUSEKEEPING '''
        self.setScenarioSaved()
        # debugging
        print "Main.mainwindow.saveScenarioAs(): end dirty? " + str(self.scenarioDirty)
def Main.mainwindow.MainWindow.selectFeatures (self, state)
Edit menu SLOT
Definition at line 1140 of file mainwindow.py.
References Main.mainwindow.MainWindow.activeVLayer, Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.disableSelectActions(), Main.mainwindow.MainWindow.enableSelectSubActions(), and Main.mainwindow.MainWindow.toolSelect.
    def selectFeatures(self, state):
        ''' Edit menu SLOT '''
        # debugging
        print "Main.mainwindow.selectFeatures() " + str(state)
        if state: # for action selected state = True
            # debugging
            print "Main.mainwindow.selectFeatures() state is True"
            # Need this to stop user from taking this action if making line or polygon edits
            if self.appStateChanged("selectFeatures") == "Cancel":
                return
            # select action is selected so enable these tools
            self.canvas.setMapTool(self.toolSelect)
            self.enableSelectSubActions()
        else: # action deselected (state = False)
            # debugging
            print "Main.mainwindow.selectFeatures() state is False"
            # select action is not selected so disable the select sub actions if no selections have been made
            if self.activeVLayer and len(self.activeVLayer.selectedFeatures()) == 0:
                self.disableSelectActions()
def Main.mainwindow.MainWindow.setBaseLayerActive (self, copyLayerName)
Edit method to activate the base layer containing features that were modified
Definition at line 1659 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), and Main.mainwindow.MainWindow.pasteModifiedBaseLayerFeats().
    def setBaseLayerActive(self, copyLayerName):
        ''' Edit method to activate the base layer containing features that were modified '''
        # debugging
        print "Main.mainwindow.setBaseLayerActive()"
        items = self.legend.findItems(copyLayerName, QtCore.Qt.MatchFixedString, 0)
        print "Main.mainwindow.setBaseLayerActive(): copyLayerName is: " + copyLayerName
        if len(items) > 0:
            self.legend.setCurrentItem(items[0])
            self.legend.currentItem().setCheckState(0, QtCore.Qt.Checked)
def Main.mainwindow.MainWindow.setExtents (self)
Empty editing shapefiles do not have extents. We need to set extents often.
Definition at line 3141 of file mainwindow.py.
References Main.mainwindow.MainWindow.rectExtentMA.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged().
    def setExtents(self):
        ''' Empty editing shapefiles do not have extents. We need to set extents often. '''
        # debugging
        print "Main.mainwindow.setExtents()"
        rect = self.canvas.extent()
        rectExtentMA = self.rectExtentMA
        smallRectExtentMA = QgsRectangle(27000, 780050, 336500, 964950)
        print "Main.mainwindow.setExtents(): The canvas extents on loading are:"
        print ("(" + str(rect.xMinimum()) + ", " + str(rect.yMinimum()) + ", " +
                     str(rect.xMaximum()) + ", " + str(rect.yMaximum()) + ")")
        print "Main.mainwindow.setExtents(): rectExtentMA is "
        print ("(" + str(rectExtentMA.xMinimum()) + ", " + str(rectExtentMA.yMinimum()) + ", " +
                     str(rectExtentMA.xMaximum()) + ", " + str(rectExtentMA.yMaximum()) + ")")
        # set extents no bigger than MA state extents
        if rect.contains(rectExtentMA) or not rect.intersects(rectExtentMA):
            print "Main.mainwindow.setExtents(): canvas extent contains or does not intersect MA"
            # set the canvas extents to be a little smaller than the MA Extent
            self.canvas.setExtent(smallRectExtentMA)
            self.canvas.updateFullExtent()
            self.canvas.refresh()
            print "Main.mainwindow.setExtents(): SET CANVAS TO MA EXTENT"
        else: print "Main.mainwindow.setExtents(): THE EXTENTS WERE NOT CHANGED"
        # debugging
        rect = self.canvas.extent()
        print "Main.mainwindow.setExtents(): The canvas extents after loading are:"
        print ("(" + str(rect.xMinimum()) + ", " + str(rect.yMinimum()) + ", " +
                     str(rect.xMaximum()) + ", " + str(rect.yMaximum()) + ")")
        print "Main.mainwindow.setExtents(): The scaled rectangle is "
        print ("(" + str(smallRectExtentMA.xMinimum()) + ", " + str(smallRectExtentMA.yMinimum()) + ", " +
                     str(smallRectExtentMA.xMaximum()) + ", " + str(smallRectExtentMA.yMaximum()) + ")")
def Main.mainwindow.MainWindow.setInitialAppState (self, newScenario = True)
Set the app state to be its first opened state
Definition at line 2838 of file mainwindow.py.
References Main.mainwindow.MainWindow.activeRLayer, Main.mainwindow.MainWindow.activeVLayer, Main.mainwindow.MainWindow.attrTable, Main.mainwindow.MainWindow.coloredLayers, Main.mainwindow.MainWindow.copiedFeats, Main.mainwindow.MainWindow.copyFlag, Main.mainwindow.MainWindow.currentLayers, Main.mainwindow.MainWindow.currentLayersCount, Main.mainwindow.MainWindow.dlgDisplayIdentify, Main.mainwindow.MainWindow.dlgScenarioEditTypes, Main.mainwindow.MainWindow.dwAttrTable, Main.mainwindow.MainWindow.dwRasterTable, Main.mainwindow.MainWindow.editDirty, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.editMode, Main.mainwindow.MainWindow.editTypeLabel, Main.mainwindow.MainWindow.geom, Main.mainwindow.MainWindow.layerColor, Main.mainwindow.MainWindow.layerType, Main.mainwindow.MainWindow.openingOrientingLayers, Main.legend.LegendItem.openingScenario, Main.mainwindow.MainWindow.openingScenario, Main.mainwindow.MainWindow.openOrientingLayers(), Main.mainwindow.MainWindow.originalEditLayerFeats, Main.mainwindow.MainWindow.originalScenarioLayers, Main.mainwindow.MainWindow.originalScenarioLayersNames, Main.mainwindow.MainWindow.origScenarioLyrsLoaded, Main.mainwindow.MainWindow.provider, Main.mainwindow.MainWindow.scenarioDirty, Main.mainwindow.MainWindow.scenarioEditType, Main.mainwindow.MainWindow.scenarioFileName, Main.mainwindow.MainWindow.scenarioFilePath, Main.mainwindow.MainWindow.scenarioInfo, Main.dlgscenarioedittypes.DlgScenarioEditTypes.scenarioInfo, Main.mainwindow.MainWindow.toolAddLinesPolygons, Main.mainwindow.MainWindow.toolAddPoints, Main.mainwindow.MainWindow.toolIdentify, Main.mainwindow.MainWindow.toolSelect, and Main.mainwindow.MainWindow.windModifyInfo.
Referenced by Main.mainwindow.MainWindow.newScenario(), and Main.mainwindow.MainWindow.openScenario().
    def setInitialAppState(self, newScenario=True):
        ''' Set the app state to be its first opened state '''
        # debugging
        print "Main.mainwindow.setInitialAppState()"
        if self.dwAttrTable: self.dwAttrTable.close()
        if self.dwRasterTable: self.dwRasterTable.close()
        if self.toolAddLinesPolygons: self.canvas.unsetMapTool(self.toolAddLinesPolygons)
        if self.toolAddPoints: self.canvas.unsetMapTool(self.toolAddPoints)
        if self.toolIdentify: self.canvas.unsetMapTool(self.toolIdentify)
        if self.toolSelect: self.canvas.unsetMapTool(self.toolSelect)
        self.activeRLayer = None
        self.activeVLayer = None
        self.attrTable = None
        self.coloredLayers = {}
        self.copiedFeats = []
        self.copyFlag = False
        self.currentLayers = []
        self.currentLayersCount = None
        self.dlgDisplayIdentify = None
        self.dlgScenarioEditTypes = None
        self.dwAttrTable = None
        self.dwRasterTable = None
        self.editDirty = False
        self.editLayerName = None
        self.editMode = False
        self.statusBar.removeWidget(self.editTypeLabel)
        self.editTypeLabel = None
        self.geom = None
        self.layerColor = None
        self.layerType = None
        self.mapToolGroup.setDisabled(True)
        self.mpActionIdentifyFeatures.setChecked(False)
        self.mpActionEditScenario.setChecked(False)
        self.mpActionEditScenario.setDisabled(False)
        self.mpActionExportScenario.setDisabled(True)
        self.mpActionOpenVectorAttributeTable.setDisabled(True)
        self.mpActionSaveEdits.setDisabled(True)
        self.mpActionSaveScenario.setDisabled(False)
        self.openingOrientingLayers = False
        self.openingScenario = False
        self.originalEditLayerFeats = []
        self.originalScenarioLayers = []
        self.originalScenarioLayersNames = []
        self.origScenarioLyrsLoaded = False
        self.provider = None
        self.scenarioDirty = False
        self.scenarioEditType = None
        self.scenarioFileName = None
        self.scenarioFilePath = None
        self.scenarioInfo = None
        self.setWindowTitle("Conservation Assessment and Prioritization System (CAPS) Scenario Builder")
        self.statusBar.removeWidget(self.editTypeLabel)
        self.windModifyInfo = None
        # This must be last so app sets variables when layers opened
        if newScenario:
            self.openOrientingLayers()
def Main.mainwindow.MainWindow.setPasteModifyDone (self)
Edit method to clean up after pasting or modifying
Definition at line 1670 of file mainwindow.py.
References Main.mainwindow.MainWindow.copiedFeatGeom, Main.mainwindow.MainWindow.copiedFeats, and Main.mainwindow.MainWindow.copyFlag.
Referenced by Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), and Main.mainwindow.MainWindow.setPasteModifySuccess().
    def setPasteModifyDone(self):
        ''' Edit method to clean up after pasting or modifying '''
        # debugging
        print "Main.mainwindow.setPasteMofifyDone()"
        self.copiedFeats = None
        self.copiedFeatGeom = None
        self.copyFlag = False
        # the paste action is turned on in copyFeatures and it is turned off here.
        self.mpActionPasteFeatures.setDisabled(True)
def Main.mainwindow.MainWindow.setPasteModifySuccess (self, modifyEdit = False)
Edit method to clean up after a successful paste or modify operation
Definition at line 1681 of file mainwindow.py.
References Main.mainwindow.MainWindow.attrTable, Main.mainwindow.MainWindow.canvas, Main.legend.Legend.canvas, Main.mainwindow.MainWindow.editDirty, Main.mainwindow.MainWindow.editLayerName, Main.mainwindow.MainWindow.getLayerFromName(), Main.mainwindow.MainWindow.openVectorAttributeTable(), and Main.mainwindow.MainWindow.setPasteModifyDone().
Referenced by Main.mainwindow.MainWindow.modifyEditLayerFeatures(), Main.mainwindow.MainWindow.pasteFeatures(), and Main.mainwindow.MainWindow.pasteModifiedBaseLayerFeats().
    def setPasteModifySuccess(self, modifyEdit=False):
        ''' Edit method to clean up after a successful paste or modify operation '''
        # debugging
        print "Main.mainwindow.setPasteModifySuccess()"
        # Note that when features are deleted, the id numbers can become inconsistent.
        # So, reset the id values.
        editLayer = self.getLayerFromName(self.editLayerName)
        editLayerProvider = editLayer.dataProvider()
        geometry = editLayer.geometryType()
        shared.resetIdNumbers(editLayerProvider, geometry)
        # Set the editDirty flag to True on pasting base layer modifications or user's
        # features. Leave it (should be false) if modifying editing layer features.
        # Note that shared.listOriginalFeatures() will be called when the edits
        # (i.e. pasted features) are saved, so we don't need to do that here.
        if not modifyEdit:
            self.editDirty = True
        # enable the save edits button for all cases but modifying edits
        if not modifyEdit:
            self.mpActionSaveEdits.setDisabled(False)
        # clean up copy variables and paste action
        self.setPasteModifyDone()
        # update Vector Attribute Table if open
        if self.attrTable != None and self.attrTable.isVisible():
            self.openVectorAttributeTable()
        # update all the extents and refresh to show features for all cases but modifying edits
        # since we do not add or remove any features when modifying edits, extents have not changed
        if not modifyEdit:
            shared.updateExtents(self, editLayer, self.canvas)
def Main.mainwindow.MainWindow.setPastingExtent (self)
    An edit method that ensures that the extents for pasted features are large enough to
    allow the user to locate the feature on an orienting map.
Definition at line 1931 of file mainwindow.py.
    def setPastingExtent(self):
        '''
            An edit method that ensures that the extents for pasted features are large enough to
            allow the user to locate the feature on an orienting map.
        '''
        # debugging
        print "Main.mainwindow.setPastingExtent()"
        # make the extents a minimum of 500 meters across
        rect = self.canvas.extent()
        print "Main.mainwindow.setPastingExtent(): The original paste extents are:"
        print ("(" + str(rect.xMinimum()) + ", " + str(rect.yMinimum()) + ", " +
                 str(rect.xMaximum()) + ", " + str(rect.yMaximum()) + ")")
        if rect.width() < 500 or rect.height() < 500:
            centerPointX = rect.center().x()
            rect.setXMinimum(centerPointX - 250)
            rect.setXMaximum(centerPointX + 250)
            print "Main.mainwindow.setPastingExtent(): The adjusted paste extents are:"
            print ("(" + str(rect.xMinimum()) + ", " + str(rect.yMinimum()) + ", " +
                 str(rect.xMaximum()) + ", " + str(rect.yMaximum()) + ")")
            self.canvas.setExtent(rect)
            self.canvas.refresh()
def Main.mainwindow.MainWindow.setScenarioDirty (self)
A scenario method to set the scenarioDirty flag
Definition at line 842 of file mainwindow.py.
References Main.mainwindow.MainWindow.currentLayersCount, Main.mainwindow.MainWindow.getCurrentLayersCount(), Main.mainwindow.MainWindow.getCurrentLayersNames(), prepareforsetupexe.name, Main.mainwindow.MainWindow.openingOrientingLayers, Main.mainwindow.MainWindow.originalScenarioLayers, Main.mainwindow.MainWindow.originalScenarioLayersNames, Main.mainwindow.MainWindow.origScenarioLyrsLoaded, Main.mainwindow.MainWindow.scenarioDirty, and Main.mainwindow.MainWindow.scenarioFileName.
Referenced by Main.mainwindow.MainWindow.saveEdits().
    def setScenarioDirty(self):
        ''' A scenario method to set the scenarioDirty flag '''
        # debugging
        print "Main.mainwindow.setScenarioDirty()"
        print "Main.mainwindow.setScenarioDirty(): self.origScenarioLyrsLoaded is " + str(self.origScenarioLyrsLoaded)
        print "Main.mainwindow.setScenarioDirty(): self.setScenarioDirty() begin is " + str(self.scenarioDirty)
        print "Main.mainwindow.setScenarioDirty(): self.scenarioFileName is " + str(self.scenarioFileName)
        print "Main.mainwindow.setScenarioDirty(): self.openingOrientingLayers is " + str(self.openingOrientingLayers)
        # The line below fails because it returns false if the layer order changes
        # self.originalScenarioLayers == self.currentLayers.values()
        self.getCurrentLayersCount()
        print "Main.mainwindow.setScenarioDirty(): self.currentLayersCount is " + str(self.currentLayersCount)
        # if in the process of opening the orienting layers, just return
        if self.openingOrientingLayers:
            self.scenarioDirty = False
            print "Main.mainwindow.setScenarioDirty(): self.setScenarioDirty() end 862 is " + str(self.scenarioDirty)
            return
        # If no scenario is open and the loaded layers are the orienting baselayers,
        # The user is probably either opening the app or has chosen "New Scenario."
        # We don't want the scenario to be dirty because the user will get prompted
        # to save the current scenario if she wants to open a scenario or if she closes the app.
        # Under these conditions, the user will only be prompted to save the scenario when the
        # "Edit Scenario" function is checked.
        if self.currentLayersCount == len(config.allOrientingLayers) and self.scenarioFileName == None:
            print "Main.mainwindow.setScenarioDirty(): Entered length = allOrientingLayers loop"
            orientingLayerNames = []
            for fileName in config.allOrientingLayers:
                info = QtCore.QFileInfo(fileName)
                name = unicode(info.completeBaseName())
                orientingLayerNames.append(name)
            legendLayerNames = []
            # legendLayers are QgsMapCanvasLayers
            legendLayers = self.legend.getLayerSet()
            for layer in legendLayers: legendLayerNames.append(unicode(layer.layer().name()))
            print "Main.mainwindow.setScenarioDirty(): orientingLayerNames are"
            for name in orientingLayerNames: print name
            print "Main.mainwindow.setScenarioDirty(): legendLayerNames are "
            for name in legendLayerNames: print name
            difference = [name for name in orientingLayerNames if name not in legendLayerNames]
            print "Main.mainwindow.setScenarioDirty(): difference is"
            print difference
            if difference == []:
                self.scenarioDirty = False
                print "Main.mainwindow.setScenarioDirty(): setScenarioDirty() difference == []"
                print "Main.mainwindow.setScenarioDirty(): self.setScenarioDirty() end 892 is " + str(self.scenarioDirty)
                return
        # If the above is not true and if the layer count is > 0 and there is no scenario open
        # then the scenario is dirty. This would and should be true even
        # if the user removed all the intially loaded layers and then loaded an orienting
        # baselayer, because that might be a scenario they want to save for some reason.
        if self.currentLayersCount > 0 and self.scenarioFileName == None:
            self.scenarioDirty = True
            # enable the 'Save Scenario' action whent the scenario is dirty
            self.mpActionSaveScenario.setDisabled(False)
            print "Main.mainwindow.setScenarioDirty(): layer count > 0 if statement"
            print "Main.mainwindow.setScenarioDirty(): self.setScenarioDirty() end 904 is " + str(self.scenarioDirty)
            return
        # Now we handle if a scenario is open
        # Check the flag to see if all scenario layers are loaded
        if self.origScenarioLyrsLoaded:
            # compare the length of the list for the original and current layers
            if len(self.originalScenarioLayers) != self.currentLayersCount:
                # if they are not the same length, the scenario is dirty
                self.scenarioDirty = True
                # enable the 'Save Scenario' action whent the scenario is dirty
                self.mpActionSaveScenario.setDisabled(False)
                print "Main.mainwindow.setScenarioDirty(): self.setScenarioDirty() end 916 is " + str(self.scenarioDirty)
                return
            # the layers are the same length but do they have the same members?
            differences = []
            # this is what Python calls a "list comprehension"
            differences = [name for name in self.getCurrentLayersNames() if name not in
                                                            self.originalScenarioLayersNames]
            if differences:
                self.scenarioDirty = True # if there are differences
                # enable the 'Save Scenario' action whent the scenario is dirty
                self.mpActionSaveScenario.setDisabled(False)
            else:
                self.scenarioDirty = False
                # disable the 'Save Scenario' action whent the scenario is not dirty
                self.mpActionSaveScenario.setDisabled(True)
            # debugging
            print "Main.mainwindow.setScenarioDirty(): currentLayersNames are"
            for name in self.getCurrentLayersNames(): print name
            print "Main.mainwindow.setScenarioDirty(): self.originalScenarioLayersNames are"
            for name in self.originalScenarioLayersNames: print name
            print "Main.mainwindow.setScenarioDirty(): differences are "
            for name in differences: print name
            return
        # Set the 'Save Edits' button if not set above.  This happens when opening a scenario.
        if self.scenarioDirty: self.mpActionSaveScenario.setDisabled(False)
        else: self.mpActionSaveScenario.setDisabled(True)
        # debugging
        print "Main.mainwindow.setScenarioDirty(): self.scenarioDirty() end 942 is " + str(self.scenarioDirty)
def Main.mainwindow.MainWindow.setScenarioSaved (self)
Scenario method to do the housekeeping for a successfully saved scenario
Definition at line 946 of file mainwindow.py.
References Main.mainwindow.MainWindow.getCurrentLayers(), Main.mainwindow.MainWindow.getOriginalScenarioLayersNames(), Main.mainwindow.MainWindow.originalScenarioLayers, Main.mainwindow.MainWindow.origScenarioLyrsLoaded, Main.mainwindow.MainWindow.scenarioDirty, and Main.mainwindow.MainWindow.scenarioFileName.
Referenced by Main.mainwindow.MainWindow.saveScenario(), and Main.mainwindow.MainWindow.saveScenarioAs().
    def setScenarioSaved(self):
        ''' Scenario method to do the housekeeping for a successfully saved scenario '''
        # debugging
        print "Main.mainwindow.setScenarioSaved()"
        # no errors so scenario saved and not dirty
        self.scenarioDirty = False
        # all scenario layers are loaded so set flag
        self.origScenarioLyrsLoaded = True
        # Reset the original scenario layers so we can delete editing layers
        # that have not been saved when closing a scenario or the app.
        # We also use this to check if the scenario is dirty.
        self.originalScenarioLayers = self.getCurrentLayers().values()
        # sets the instance variable self.originalScenarioLayersNames
        self.getOriginalScenarioLayersNames()
        # get the complete filename without the path
        self.scenarioFileName = unicode(self.scenarioInfo.fileName())
        # give the user some info
        self.setWindowTitle("Conservation Assessment and \
Prioritization System (CAPS) Scenario Builder - " + self.scenarioFileName)
        # gray out the 'Save Scenario' button after the scenario is saved
        self.mpActionSaveScenario.setDisabled(True)
def Main.mainwindow.MainWindow.setSelectionColor (self)
Definition at line 3229 of file mainwindow.py.
References prepareforsetupexe.name.
    def setSelectionColor(self):
        # debugging
        print 'Main.mainwindow.setSelectionColor()'
        renderer = QgsSingleSymbolRenderer(QGis.Point)
        color = QtGui.QColor("yellow")
        renderer.setSelectionColor(color)
        print "Main.mainwindow.setSelectionColor(): The renderer name is: " + renderer.name()
        print "Main.mainwindow.setSelectionColor(): The renderer.selectionColor() is: " + renderer.selectionColor().name()
def Main.mainwindow_ui.Ui_MainWindow.setupUi (self, MainWindow) [inherited]
Definition at line 18 of file mainwindow_ui.py.
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 700)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/CAPS_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridlayout = QtGui.QGridLayout(self.centralwidget)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuScenario = QtGui.QMenu(self.menubar)
        self.menuScenario.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.menuScenario.setObjectName(_fromUtf8("menuScenario"))
        self.menuLayer = QtGui.QMenu(self.menubar)
        self.menuLayer.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.menuLayer.setObjectName(_fromUtf8("menuLayer"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setToolTip(_fromUtf8(""))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.statusBar.setToolTip(_fromUtf8(""))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.mpActionAddRasterLayer = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionAddRasterLayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddRasterLayer.setIcon(icon1)
        self.mpActionAddRasterLayer.setObjectName(_fromUtf8("mpActionAddRasterLayer"))
        self.mpActionNewScenario = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionFileNew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionNewScenario.setIcon(icon2)
        self.mpActionNewScenario.setObjectName(_fromUtf8("mpActionNewScenario"))
        self.mpActionAddVectorLayer = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionAddOgrLayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddVectorLayer.setIcon(icon3)
        self.mpActionAddVectorLayer.setObjectName(_fromUtf8("mpActionAddVectorLayer"))
        self.mpActionZoomIn = QtGui.QAction(MainWindow)
        self.mpActionZoomIn.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionZoomIn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionZoomIn.setIcon(icon4)
        self.mpActionZoomIn.setObjectName(_fromUtf8("mpActionZoomIn"))
        self.mpActionZoomOut = QtGui.QAction(MainWindow)
        self.mpActionZoomOut.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionZoomOut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionZoomOut.setIcon(icon5)
        self.mpActionZoomOut.setObjectName(_fromUtf8("mpActionZoomOut"))
        self.mpActionPan = QtGui.QAction(MainWindow)
        self.mpActionPan.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionPan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionPan.setIcon(icon6)
        self.mpActionPan.setObjectName(_fromUtf8("mpActionPan"))
        self.mpActionZoomtoMapExtent = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionZoomFullExtent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionZoomtoMapExtent.setIcon(icon7)
        self.mpActionZoomtoMapExtent.setObjectName(_fromUtf8("mpActionZoomtoMapExtent"))
        self.mpActionOpenScenario = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionFileOpen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionOpenScenario.setIcon(icon8)
        self.mpActionOpenScenario.setObjectName(_fromUtf8("mpActionOpenScenario"))
        self.mpActionSaveScenario = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionFileSave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionSaveScenario.setIcon(icon9)
        self.mpActionSaveScenario.setObjectName(_fromUtf8("mpActionSaveScenario"))
        self.mpActionSaveScenarioAs = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionFileSaveAs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionSaveScenarioAs.setIcon(icon10)
        self.mpActionSaveScenarioAs.setObjectName(_fromUtf8("mpActionSaveScenarioAs"))
        self.mpActionSelectFeatures = QtGui.QAction(MainWindow)
        self.mpActionSelectFeatures.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionSelect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionSelectFeatures.setIcon(icon11)
        self.mpActionSelectFeatures.setObjectName(_fromUtf8("mpActionSelectFeatures"))
        self.mpActionDeleteFeatures = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionDeleteSelected.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionDeleteFeatures.setIcon(icon12)
        self.mpActionDeleteFeatures.setObjectName(_fromUtf8("mpActionDeleteFeatures"))
        self.mpActionPasteFeatures = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionEditPaste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionPasteFeatures.setIcon(icon13)
        self.mpActionPasteFeatures.setObjectName(_fromUtf8("mpActionPasteFeatures"))
        self.mpActionCopyFeatures = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionCopySelected.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionCopyFeatures.setIcon(icon14)
        self.mpActionCopyFeatures.setObjectName(_fromUtf8("mpActionCopyFeatures"))
        self.mpActionAddPoints = QtGui.QAction(MainWindow)
        self.mpActionAddPoints.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionCapturePoint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddPoints.setIcon(icon15)
        self.mpActionAddPoints.setObjectName(_fromUtf8("mpActionAddPoints"))
        self.mpActionAddLines = QtGui.QAction(MainWindow)
        self.mpActionAddLines.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionCaptureLine.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddLines.setIcon(icon16)
        self.mpActionAddLines.setObjectName(_fromUtf8("mpActionAddLines"))
        self.mpActionAddPolygons = QtGui.QAction(MainWindow)
        self.mpActionAddPolygons.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionCapturePolygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddPolygons.setIcon(icon17)
        self.mpActionAddPolygons.setObjectName(_fromUtf8("mpActionAddPolygons"))
        self.mpActionExportScenario = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/scenario_export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionExportScenario.setIcon(icon18)
        self.mpActionExportScenario.setObjectName(_fromUtf8("mpActionExportScenario"))
        self.mpActionOpenRasterCategoryTable = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mIconTableLayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionOpenRasterCategoryTable.setIcon(icon19)
        self.mpActionOpenRasterCategoryTable.setObjectName(_fromUtf8("mpActionOpenRasterCategoryTable"))
        self.mpActionOpenVectorAttributeTable = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/attributes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionOpenVectorAttributeTable.setIcon(icon20)
        self.mpActionOpenVectorAttributeTable.setObjectName(_fromUtf8("mpActionOpenVectorAttributeTable"))
        self.mpActionEditScenario = QtGui.QAction(MainWindow)
        self.mpActionEditScenario.setCheckable(True)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionToggleEditing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionEditScenario.setIcon(icon21)
        self.mpActionEditScenario.setObjectName(_fromUtf8("mpActionEditScenario"))
        self.mpActionSaveEdits = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionSaveEdits.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionSaveEdits.setIcon(icon22)
        self.mpActionSaveEdits.setObjectName(_fromUtf8("mpActionSaveEdits"))
        self.mpActionDeselectFeatures = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionDeselectAll.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionDeselectFeatures.setIcon(icon23)
        self.mpActionDeselectFeatures.setObjectName(_fromUtf8("mpActionDeselectFeatures"))
        self.mpActionAppExit = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionAppExit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAppExit.setIcon(icon24)
        self.mpActionAppExit.setObjectName(_fromUtf8("mpActionAppExit"))
        self.mpActionIdentifyFeatures = QtGui.QAction(MainWindow)
        self.mpActionIdentifyFeatures.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionIdentify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionIdentifyFeatures.setIcon(icon25)
        self.mpActionIdentifyFeatures.setObjectName(_fromUtf8("mpActionIdentifyFeatures"))
        self.mpActionModifyPoints = QtGui.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionModifyPoints.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionModifyPoints.setIcon(icon26)
        self.mpActionModifyPoints.setObjectName(_fromUtf8("mpActionModifyPoints"))
        self.mpActionManageProjects = QtGui.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionManageProjects.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionManageProjects.setIcon(icon27)
        self.mpActionManageProjects.setObjectName(_fromUtf8("mpActionManageProjects"))
        self.mpActionSftpProperties = QtGui.QAction(MainWindow)
        self.mpActionSftpProperties.setObjectName(_fromUtf8("mpActionSftpProperties"))
        self.menuScenario.addAction(self.mpActionNewScenario)
        self.menuScenario.addAction(self.mpActionOpenScenario)
        self.menuScenario.addAction(self.mpActionSaveScenario)
        self.menuScenario.addAction(self.mpActionSaveScenarioAs)
        self.menuScenario.addAction(self.mpActionExportScenario)
        self.menuScenario.addAction(self.mpActionAppExit)
        self.menuLayer.addAction(self.mpActionAddVectorLayer)
        self.menuLayer.addAction(self.mpActionAddRasterLayer)
        self.menuLayer.addAction(self.mpActionOpenVectorAttributeTable)
        self.menuLayer.addAction(self.mpActionOpenRasterCategoryTable)
        self.menuLayer.addSeparator()
        self.menuEdit.addAction(self.mpActionSelectFeatures)
        self.menuEdit.addAction(self.mpActionDeselectFeatures)
        self.menuEdit.addAction(self.mpActionModifyPoints)
        self.menuEdit.addAction(self.mpActionDeleteFeatures)
        self.menuEdit.addAction(self.mpActionCopyFeatures)
        self.menuEdit.addAction(self.mpActionPasteFeatures)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.mpActionEditScenario)
        self.menuEdit.addAction(self.mpActionAddPoints)
        self.menuEdit.addAction(self.mpActionAddLines)
        self.menuEdit.addAction(self.mpActionAddPolygons)
        self.menuEdit.addAction(self.mpActionSaveEdits)
        self.menuEdit.addSeparator()
        self.menuEdit.addSeparator()
        self.menuView.addAction(self.mpActionZoomIn)
        self.menuView.addAction(self.mpActionZoomOut)
        self.menuView.addAction(self.mpActionPan)
        self.menuView.addAction(self.mpActionZoomtoMapExtent)
        self.menuView.addAction(self.mpActionIdentifyFeatures)
        self.menuProject.addAction(self.mpActionManageProjects)
        self.menuProject.addAction(self.mpActionSftpProperties)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuScenario.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuLayer.menuAction())
        self.toolBar.addAction(self.mpActionManageProjects)
        self.toolBar.addAction(self.mpActionNewScenario)
        self.toolBar.addAction(self.mpActionOpenScenario)
        self.toolBar.addAction(self.mpActionSaveScenario)
        self.toolBar.addAction(self.mpActionSaveScenarioAs)
        self.toolBar.addAction(self.mpActionExportScenario)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.mpActionSelectFeatures)
        self.toolBar.addAction(self.mpActionDeselectFeatures)
        self.toolBar.addAction(self.mpActionModifyPoints)
        self.toolBar.addAction(self.mpActionDeleteFeatures)
        self.toolBar.addAction(self.mpActionCopyFeatures)
        self.toolBar.addAction(self.mpActionPasteFeatures)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.mpActionEditScenario)
        self.toolBar.addAction(self.mpActionAddPoints)
        self.toolBar.addAction(self.mpActionAddLines)
        self.toolBar.addAction(self.mpActionAddPolygons)
        self.toolBar.addAction(self.mpActionSaveEdits)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.mpActionIdentifyFeatures)
        self.toolBar.addAction(self.mpActionPan)
        self.toolBar.addAction(self.mpActionZoomIn)
        self.toolBar.addAction(self.mpActionZoomOut)
        self.toolBar.addAction(self.mpActionZoomtoMapExtent)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.mpActionAddVectorLayer)
        self.toolBar.addAction(self.mpActionAddRasterLayer)
        self.toolBar.addAction(self.mpActionOpenVectorAttributeTable)
        self.toolBar.addAction(self.mpActionOpenRasterCategoryTable)
        self.toolBar.addSeparator()
        self.retranslateUi(MainWindow)
        '''QtCore.QObject.connect(self.mpActionNewScenario, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.newScenario)
        QtCore.QObject.connect(self.mpActionSaveScenario, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.saveScenario)
        QtCore.QObject.connect(self.mpActionOpenScenario, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openScenario)
        QtCore.QObject.connect(self.mpActionSaveScenarioAs, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.saveScenarioAs)
        QtCore.QObject.connect(self.mpActionExportScenario, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.exportScenario)
        QtCore.QObject.connect(self.mpActionSelectFeatures, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.selectFeatures)
        QtCore.QObject.connect(self.mpActionDeselectFeatures, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.deselectFeatures)
        QtCore.QObject.connect(self.mpActionCopyFeatures, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.copyFeatures)
        QtCore.QObject.connect(self.mpActionDeleteFeatures, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.deleteFeatures)
        QtCore.QObject.connect(self.mpActionPasteFeatures, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.pasteFeatures)
        QtCore.QObject.connect(self.mpActionAddPoints, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.addPoints)
        QtCore.QObject.connect(self.mpActionAddLines, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.addLines)
        QtCore.QObject.connect(self.mpActionAddPolygons, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.addPolygons)
        QtCore.QObject.connect(self.mpActionZoomIn, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.zoomIn)
        QtCore.QObject.connect(self.mpActionZoomOut, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.zoomOut)
        QtCore.QObject.connect(self.mpActionZoomtoMapExtent, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.zoomToMapExtent)
        QtCore.QObject.connect(self.mpActionAddVectorLayer, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.addVectorLayer)
        QtCore.QObject.connect(self.mpActionAddRasterLayer, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.addRasterLayer)
        QtCore.QObject.connect(self.mpActionOpenRasterCategoryTable, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openRasterCategoryTable)
        QtCore.QObject.connect(self.mpActionOpenVectorAttributeTable, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openVectorAttributeTable)
        QtCore.QObject.connect(self.mpActionEditScenario, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.editScenario)
        QtCore.QObject.connect(self.mpActionSaveEdits, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.saveEdits)
        QtCore.QObject.connect(self.mpActionPan, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.pan)
        QtCore.QObject.connect(self.mpActionAppExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.mpActionIdentifyFeatures, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.identifyFeatures)
        QtCore.QObject.connect(self.mpActionModifyPoints, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.ModifyPoints)
        QtCore.QObject.connect(self.mpActionManageProjects, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.manageProjects)
        QtCore.QObject.connect(self.mpActionSftpProperties, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.sftpProperties)'''
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
def Main.mainwindow.MainWindow.sftpProperties (self)
Project menu SLOT
Definition at line 292 of file mainwindow.py.
References Main.mainwindow.MainWindow.dlgSftpProperties.
    def sftpProperties(self):
        ''' Project menu SLOT '''
        # debugging
        print "Main.mainwindow.sftpProperties()"
        self.dlgSftpProperties = DlgSftpProperties(self)
        self.dlgSftpProperties.exec_()
def Main.mainwindow.MainWindow.writeCsvExportFile (self, exportPath, csvPath, exportFileName)
Scenario method to write the CSV export file
Definition at line 747 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def writeCsvExportFile(self, exportPath, csvPath, exportFileName):
        ''' Scenario method to write the CSV export file '''
        # debugging
        print "Main.mainwindow.writeCsvEportFile"
        error = None
        try:
            csvExportScenario = open(exportPath, 'a')
            csvEditingShapefile = open(csvPath, 'r')
            csvText = csvEditingShapefile.read()
            csvEditingShapefile.close()
            csvExportScenario.write(csvText)
            csvExportScenario.close()
        except (IOError, OSError), e:
            error = unicode(e)
        if error:
            print e
            QtGui.QMessageBox.warning(self, 'Export Scenario Error:', 'The export file, ' \
+ exportFileName + ' could not be written.  Please try again.')
            return False
        return True
def Main.mainwindow.MainWindow.writeCsvShapefile (self, vlayer, csvPath, csvFileName)
Scenario method to write the CSV shapefile
Definition at line 725 of file mainwindow.py.
References Main.mainwindow.MainWindow.crs.
Referenced by Main.mainwindow.MainWindow.exportScenario().
    def writeCsvShapefile(self, vlayer, csvPath, csvFileName):
        ''' Scenario method to write the CSV shapefile '''
        # debugging
        print "Main.mainwindow.writeCSVShapefile()"
        # Create an empty datasource and errorMessage option for the
        # QgsVectorFileWriter parameters list
        datasourceOptions = QtCore.QStringList(QtCore.QString())
        errorMessage = QtCore.QString()
        # Need to include the creationOptions or the geometry will not be written.
        creationOptions = QtCore.QStringList("GEOMETRY=AS_WKT")
        # write csv file in MA State Plane coordinates and check for error
        error = QgsVectorFileWriter.writeAsVectorFormat(vlayer, csvPath, "utf-8",
                    self.crs, "CSV", False, errorMessage, datasourceOptions, creationOptions)
        if error: # != QgsVectorFileWriter.NoError:
            QtGui.QMessageBox.warning(self, "Export Scenario Error:", "The file " + csvFileName + " \
was not written.  Please check that a file with the same name is not open in another program.")
            return False
        else:
            print "Main.mainwindow.writeCSVShapefile(): The csv file " + csvPath + " was successfully written."
            return True
def Main.mainwindow.MainWindow.zoomIn (self, state)
View menu SLOT
Definition at line 2197 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.toolZoomIn.
    def zoomIn(self, state):
        ''' View menu SLOT '''
        print "Main.mainwindow.zoomIn() " + str(state)
        if state:
            # Need this to handle if user tries to addVector while adding a line or polygon
            # check app state and handle user cancel
            if self.appStateChanged("zoomIn") == "Cancel":
                return
            self.canvas.setMapTool(self.toolZoomIn)
        else: self.canvas.unsetMapTool(self.toolZoomIn)
def Main.mainwindow.MainWindow.zoomOut (self, state)
View menu SLOT
Definition at line 2209 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.toolZoomOut.
    def zoomOut(self, state):
        ''' View menu SLOT '''
        # debugging
        print "Main.mainwindow.zoomOut() "  + str(state)
        if state:
            # Need this to handle if user tries to addVector while adding a line or polygon
            # check app state and handle user cancel
            if self.appStateChanged("zoomOut") == "Cancel":
                return
            self.canvas.setMapTool(self.toolZoomOut)
        else: self.canvas.unsetMapTool(self.toolZoomOut)
def Main.mainwindow.MainWindow.zoomToMapExtent (self)
View menu SLOT to set zoom to full extent of visible layers
Definition at line 2235 of file mainwindow.py.
References Main.mainwindow.MainWindow.appStateChanged().
    def zoomToMapExtent(self):
        ''' View menu SLOT to set zoom to full extent of visible layers '''
        # debugging
        print "Main.mainwindow.zoomToMapExtent()"
        # Need this to handle if user tries to addVector while adding a line or polygon
        # check app state and handle user cancel
        if self.appStateChanged("zoomToMapExtent") == "Cancel":
            return
        extent = self.canvas.fullExtent()
        # without this some of the layer is off the canvas
        extent.scale(1.05)
        self.canvas.setExtent(extent)
        self.canvas.refresh()
Member Data Documentation
Main::mainwindow.MainWindow::activeRLayer
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::activeVLayer
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.deleteFeatures(), Main.mainwindow.MainWindow.editScenario(), Main.mainwindow.MainWindow.openVectorAttributeTable(), Main.mainwindow.MainWindow.openVectorLayer(), Main.mainwindow.MainWindow.selectFeatures(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::attrTable
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.checkEditsState(), Main.mainwindow.MainWindow.deleteFeatures(), Main.mainwindow.MainWindow.openVectorAttributeTable(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), Main.mainwindow.MainWindow.setInitialAppState(), and Main.mainwindow.MainWindow.setPasteModifySuccess().
Main::mainwindow.MainWindow::browserRaster
Definition at line 2324 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.openRasterCategoryTable().
Main::mainwindow.MainWindow::canvas
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.deleteFeatures(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), and Main.mainwindow.MainWindow.setPasteModifySuccess().
Main::mainwindow_ui.Ui_MainWindow::centralwidget [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow.MainWindow::coloredLayers
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::copiedFeatCount
Definition at line 1181 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.copyFeatures(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), and Main.mainwindow.MainWindow.pasteFeatures().
Main::mainwindow.MainWindow::copiedFeatGeom
Definition at line 1569 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.pasteFeatures(), and Main.mainwindow.MainWindow.setPasteModifyDone().
Main::mainwindow.MainWindow::copiedFeats
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.checkPastedFeatureConstraints(), Main.mainwindow.MainWindow.displayCopiedFeatInfo(), Main.mainwindow.MainWindow.modifyEditLayerFeatures(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), Main.mainwindow.MainWindow.pasteEmptyFeatures(), Main.mainwindow.MainWindow.setInitialAppState(), and Main.mainwindow.MainWindow.setPasteModifyDone().
Main::mainwindow.MainWindow::copyFlag
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.checkPastedFeatureConstraints(), Main.mainwindow.MainWindow.copyFeatures(), Main.mainwindow.MainWindow.editScenario(), Main.mainwindow.MainWindow.setInitialAppState(), and Main.mainwindow.MainWindow.setPasteModifyDone().
Main::mainwindow.MainWindow::copyLayer
Definition at line 1771 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow::pasteModifiedBaseLayerFeats().
Main::mainwindow.MainWindow::crs
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.copyScenario(), and Main.mainwindow.MainWindow.writeCsvShapefile().
Main::mainwindow.MainWindow::currentLayers
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.getCurrentLayers(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::currentLayersCount
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.getCurrentLayersCount(), Main.mainwindow.MainWindow.setInitialAppState(), and Main.mainwindow.MainWindow.setScenarioDirty().
Main::mainwindow.MainWindow::defaultColors
Definition at line 64 of file mainwindow.py.
Main::mainwindow.MainWindow::dlgAddAtts
Definition at line 1569 of file mainwindow.py.
Main::mainwindow.MainWindow::dlgDisplayIdentify
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::dlgManageProjects
Definition at line 278 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow::manageProjects().
Main::mainwindow.MainWindow::dlgScenarioEditTypes
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.copyScenario(), Main.mainwindow.MainWindow.editScenario(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::dlgSftpProperties
Definition at line 292 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow::sftpProperties().
Main::mainwindow.MainWindow::dwAttrTable
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.openVectorAttributeTable(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::dwRasterTable
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.openRasterCategoryTable(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::editDirty
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.deleteFeatures(), Main.mainwindow.MainWindow.editScenario(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), Main.mainwindow.MainWindow.saveEdits(), Main.mainwindow.MainWindow.setInitialAppState(), and Main.mainwindow.MainWindow.setPasteModifySuccess().
Main::mainwindow.MainWindow::editLayerName
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.checkEditsState(), Main.mainwindow.MainWindow.editScenario(), Main.mainwindow.MainWindow.modifyEditLayerFeatures(), Main.mainwindow.MainWindow.modifyFeatures(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), Main.mainwindow.MainWindow.pasteEmptyFeatures(), Main.mainwindow.MainWindow.pasteFeatures(), Main.mainwindow.MainWindow.pasteModifiedBaseLayerFeats(), Main.mainwindow.MainWindow.saveEdits(), Main.mainwindow.MainWindow.setInitialAppState(), and Main.mainwindow.MainWindow.setPasteModifySuccess().
Main::mainwindow.MainWindow::editMode
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.checkEditsState(), Main.mainwindow.MainWindow.editScenario(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::editTypeLabel
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.editScenario(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::geom
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.checkPastedFeatureConstraints(), Main.mainwindow.MainWindow.deleteFeatures(), Main.mainwindow.MainWindow.enablePointsOrLinesOrPolygons(), Tools.addlinespolygons.AddLinesPolygons.getNewAttributes(), Main.mainwindow.MainWindow.pasteFeatures(), Tools.addlinespolygons.AddLinesPolygons.resetDraw(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow_ui.Ui_MainWindow::gridlayout [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow.MainWindow::layerColor
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::layerType
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::legend
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.arrangeOrientingLayers(), and Main.mainwindow.MainWindow.copyScenario().
Main::mainwindow.MainWindow::legendDock
Definition at line 64 of file mainwindow.py.
Main::mainwindow.MainWindow::mapcoords
Definition at line 70 of file mainwindow.py.
Main::mainwindow.MainWindow::mapRenderer
Definition at line 64 of file mainwindow.py.
Main::mainwindow.MainWindow::mapToolGroup
Definition at line 64 of file mainwindow.py.
Main::mainwindow_ui.Ui_MainWindow::menubar [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::menuEdit [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::menuLayer [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::menuProject [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::menuScenario [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::menuView [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow.MainWindow::modifyFlag
Definition at line 1569 of file mainwindow.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionAddLines [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionAddPoints [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionAddPolygons [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionAddRasterLayer [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionAddVectorLayer [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionAppExit [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionCopyFeatures [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionDeleteFeatures [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionDeselectFeatures [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionEditScenario [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionExportScenario [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionIdentifyFeatures [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionManageProjects [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionModifyPoints [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionNewScenario [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionOpenRasterCategoryTable [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionOpenScenario [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionOpenVectorAttributeTable [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionPan [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionPasteFeatures [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionSaveEdits [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionSaveScenario [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionSaveScenarioAs [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionSelectFeatures [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionSftpProperties [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionZoomIn [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionZoomOut [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow_ui.Ui_MainWindow::mpActionZoomtoMapExtent [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow.MainWindow::msgFlag
Definition at line 1569 of file mainwindow.py.
Main::mainwindow.MainWindow::openingOrientingLayers
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.openOrientingLayers(), Main.mainwindow.MainWindow.setInitialAppState(), and Main.mainwindow.MainWindow.setScenarioDirty().
Main::mainwindow.MainWindow::openingScenario
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.openScenario(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::originalEditLayerFeats
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.checkEditsState(), Main.mainwindow.MainWindow.modifyEditLayerFeatures(), Main.mainwindow.MainWindow.saveEdits(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::originalScenarioLayers
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.copyScenario(), Main.mainwindow.MainWindow.getOriginalScenarioLayers(), Main.mainwindow.MainWindow.getOriginalScenarioLayersNames(), Main.mainwindow.MainWindow.openScenario(), Main.mainwindow.MainWindow.setInitialAppState(), Main.mainwindow.MainWindow.setScenarioDirty(), and Main.mainwindow.MainWindow.setScenarioSaved().
Main::mainwindow.MainWindow::originalScenarioLayersNames
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.arrangeOrientingLayers(), Main.mainwindow.MainWindow.checkScenarioState(), Main.mainwindow.MainWindow.getOriginalScenarioLayersNames(), Main.mainwindow.MainWindow.setInitialAppState(), and Main.mainwindow.MainWindow.setScenarioDirty().
Main::mainwindow.MainWindow::origScenarioLyrsLoaded
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.getOriginalScenarioLayers(), Main.mainwindow.MainWindow.setInitialAppState(), Main.mainwindow.MainWindow.setScenarioDirty(), and Main.mainwindow.MainWindow.setScenarioSaved().
Main::mainwindow.MainWindow::provider
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.deleteFeatures(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::rectExtentMA
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.setExtents().
Main::mainwindow.MainWindow::reply
Definition at line 1569 of file mainwindow.py.
Main::mainwindow.MainWindow::scenarioDirty
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.newScenario(), Main.mainwindow.MainWindow.openScenario(), Main.mainwindow.MainWindow.saveEdits(), Main.mainwindow.MainWindow.saveScenario(), Main.mainwindow.MainWindow.saveScenarioAs(), Main.mainwindow.MainWindow.setInitialAppState(), Main.mainwindow.MainWindow.setScenarioDirty(), and Main.mainwindow.MainWindow.setScenarioSaved().
Main::mainwindow.MainWindow::scenarioEditType
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.checkBaseLayerMatch(), Main.mainwindow.MainWindow.checkFieldNameMatch(), Main.mainwindow.MainWindow.checkPastedFeatureConstraints(), Main.mainwindow.MainWindow.editScenario(), Main.mainwindow.MainWindow.modifyFeatures(), Main.mainwindow.MainWindow.pasteBaseLayerDeletions(), Main.mainwindow.MainWindow.pasteFeatures(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::scenarioFileName
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.editScenario(), Main.mainwindow.MainWindow.openScenario(), Main.mainwindow.MainWindow.setInitialAppState(), Main.mainwindow.MainWindow.setScenarioDirty(), and Main.mainwindow.MainWindow.setScenarioSaved().
Main::mainwindow.MainWindow::scenarioFilePath
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged(), Main.mainwindow.MainWindow.appStateChanged(), Main.mainwindow.MainWindow.checkScenarioState(), Main.mainwindow.MainWindow.openScenario(), Main.mainwindow.MainWindow.saveScenario(), Main.mainwindow.MainWindow.saveScenarioAs(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::scenarioInfo
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.copyScenario(), Main.mainwindow.MainWindow.openScenario(), Main.mainwindow.MainWindow.saveScenario(), Main.mainwindow.MainWindow.saveScenarioAs(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::sftpHost
Definition at line 64 of file mainwindow.py.
Main::mainwindow.MainWindow::sftpPassword
Definition at line 64 of file mainwindow.py.
Main::mainwindow.MainWindow::sftpPath
Definition at line 64 of file mainwindow.py.
Main::mainwindow.MainWindow::sftpUser
Definition at line 64 of file mainwindow.py.
Main::mainwindow.MainWindow::splash
Definition at line 64 of file mainwindow.py.
Main::mainwindow_ui.Ui_MainWindow::statusBar [inherited]
Definition at line 18 of file mainwindow_ui.py.
Referenced by Main.mainwindow.MainWindow.editScenario().
Main::mainwindow.MainWindow::tempOriginalEditFeats
Definition at line 1569 of file mainwindow.py.
Main::mainwindow.MainWindow::textBrowserModifyInfo
Definition at line 1984 of file mainwindow.py.
Main::mainwindow.MainWindow::toolAddLinesPolygons
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.addLines(), Main.mainwindow.MainWindow.appStateChanged(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::toolAddPoints
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.addPoints(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow_ui.Ui_MainWindow::toolBar [inherited]
Definition at line 18 of file mainwindow_ui.py.
Main::mainwindow.MainWindow::toolIdentify
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.identifyFeatures(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::toolPan
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.pan().
Main::mainwindow.MainWindow::toolSelect
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.disableSelectActions(), Main.mainwindow.MainWindow.selectFeatures(), and Main.mainwindow.MainWindow.setInitialAppState().
Main::mainwindow.MainWindow::toolZoomIn
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.zoomIn().
Main::mainwindow.MainWindow::toolZoomOut
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.zoomOut().
Main::mainwindow.MainWindow::windModifyInfo
Definition at line 64 of file mainwindow.py.
Referenced by Main.mainwindow.MainWindow.setInitialAppState().
The documentation for this class was generated from the following file:
C:/egit_repositories/CAPS-Scenario-Builder/CAPS_Scenario_Builder/src/Main/mainwindow.py