Caps Scenario Builder: snippets Namespace Reference
snippets Namespace Reference
Functions
def moveEditLayer
def moveBaseLayer
def moveConstraintLayer
def _get_group_sid
def _set_file_attributes
def set_file_readonly
def oldarrangeOrientingLayers
def openEditLayer
def openOrientingBaseLayers
def find_process
def clear
def updateStatusBar
def markPoint
def __getIdFeaturesIntersect
Variables
string self = "some class"
string parent = "some widget's parent"
tuple capture_string = self.activeRLayer.source()
tuple vfilePath = activeVLayer.source()
tuple name = activeVLayer.name()
tuple layerId = activeVLayer.id()
tuple brush = QtGui.QBrush()
tuple editItems = mainwindow.legend.findItems(name, QtCore.Qt.MatchFixedString, 0)
tuple renderer = QgsSingleSymbolRenderer(QGis.Polygon)
tuple symbol = renderer.symbols()
tuple vfileID = self.activeVLayer.getLayerID()
string EVERYONE_GROUP = 'Everyone'
string ADMINISTRATORS_GROUP = 'Administrators'
tuple prj = QgsProject.instance()
tuple r = prj.readNumEntry("Gui", "/SelectionColorRedPart", 255)
tuple g = prj.readNumEntry("Gui", "/SelectionColorGreenPart", 255)
tuple b = prj.readNumEntry("Gui", "/SelectionColorBluePart", 0)
tuple a = prj.readNumEntry("Gui", "/SelectionColorAlphaPart", 255)
tuple clr = QColor(r,g,b,a)
tuple editFile = QtCore.QFile(editFilePath)
tuple error = unicode(e)
tuple extent = self.canvas.extent()
tuple dir = os.path.dirname(self.rfilename)
list groups = [0]
string processname = 'aterm'
tuple fields = line.split()
list pid = fields[0]
list process = fields[4]
tuple lock = LockFile(vfile)
tuple f = open(vfile, 'rb')
string lockFile = ".lckchk"
scenario = None
tuple qd = QtGui.QFileDialog()
tuple filter_str = QtCore.QString("CAPS Scenario*.cap *.cap)\nAll Files(*)")
tuple scenarioFileName
tuple directoryName = self.info.completeBaseName()
tuple provider = self.vlayer.dataProvider()
tuple feat = QgsFeature()
tuple text = QtCore.QString("(%1,%2)")
tuple indexMaker = QtGui.QStandardItemModel.index()
tuple topLeft = indexMaker.createIndex(0,0)
tuple selection = QtGui.QItemSelection(topLeft, oldSelection)
tuple crs = self.provider.crs()
tuple writer = QgsVectorFileWriter("test_points.shp", "UTF-8", fields, QGis.WKBPoint, crs)
string layer = "some layer"
tuple layerExtent = layer.extent()
tuple title = QtCore.QString("Error")
tuple txt
qgspoint
center
rb
Detailed Description
Created on Jun 2, 2011
@author: urbanec
Function Documentation
def snippets.__getIdFeaturesIntersect (self, rect, lyr) [private]
Definition at line 753 of file snippets.py.
def __getIdFeaturesIntersect(self, rect, lyr):
    prov = lyr.dataProvider()
    allAttrs = prov.attributeIndexes()
    prov.select(allAttrs, core.QgsRectangle())
    idInSpatialIndex = self.__createIndex(prov).intersects(rect)
    prov.rewind()
    ids = []
    feat = core.QgsFeature()
    for id in idInSpatialIndex:
      prov.featureAtId(int(id), feat, True)
      if feat.geometry().intersects(rect):
        ids.append(int(id))
    return ids
''' cursor '''
self.canvas.setCursor(cursor)
self.canvas.unsetCursor(cursor)
'''make circle ??'''
self.center = self.toMapCoordinates(e.pos())
self.rb=QgsRubberBand(self.canvas,True)
rbcircle(self.rb,self.center,self.center,40)
'''both of these worked in selectfeatures.py
 when mainwindow had a variable self.test'''
def snippets._get_group_sid (group_name) [private]
Return the SID for a group with the given name.
Definition at line 264 of file snippets.py.
Referenced by _set_file_attributes().
def _get_group_sid(group_name):
    """Return the SID for a group with the given name."""
    return LookupAccountName('', group_name)[0]
def snippets._set_file_attributes (path, groups) [private]
Set file attributes using the wind32api.
Definition at line 269 of file snippets.py.
References _get_group_sid().
Referenced by set_file_readonly().
def _set_file_attributes(path, groups):
    """Set file attributes using the wind32api."""
    security_descriptor = GetFileSecurity(path, DACL_SECURITY_INFORMATION)
    dacl = ACL()
    for group_name in groups:
        # set the attributes of the group only if not null
        if groups[group_name]:
            group_sid = _get_group_sid(group_name)
            dacl.AddAccessAllowedAce(ACL_REVISION, groups[group_name],
                group_sid)
    # the dacl has all the info of the dff groups passed in the parameters
    security_descriptor.SetSecurityDescriptorDacl(1, dacl, 0)
    SetFileSecurity(path, DACL_SECURITY_INFORMATION, security_descriptor)
def snippets.clear ()
Definition at line 528 of file snippets.py.
def clear():
    if os.name == 'posix':
        os.system('clear')
    elif os.name == ('ce', 'nt', 'dos'):
        os.system('cls')
clear()
# using the lockfile module
def snippets.find_process (name)
Definition at line 514 of file snippets.py.
def find_process(name):
    objWMIService = win32com.client.Dispatch("WbemScripting.SWbemLocator")
    objSWbemServices = objWMIService.ConnectServer(".", "root\cimv2")
    colItems = objSWbemServices.ExecQuery(
         "Select * from Win32_Process where Caption = '{0}'".format(name))
    return len(colItems)
def snippets.markPoint (self, point)
Definition at line 744 of file snippets.py.
def markPoint(self, point):
        # display the clicked point on the screen
        marker = QgsVertexMarker(self.canvas)
        transform = self.canvas.getCoordinateTransform()
        self.qgspoint = transform.toMapCoordinates(point.x(), point.y())
        marker.setPenWidth(2)
        marker.setCenter(self.qgspoint)
'''example of intersects'''
def snippets.moveBaseLayer (self, legend)
Move the needed baseLayer to second the layer panel,
    check and make visible.
Definition at line 48 of file snippets.py.
    def moveBaseLayer(self, legend):
        ''' Move the needed baseLayer to second the layer panel,
            check and make visible.
        '''
        items = legend.findItems(self.baseLayerBaseName, QtCore.Qt.MatchFixedString, 0)
        itemToMove = items[0]
        # debugging
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveBaseLayer()"
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveBaseLayer(): length of item list is " + str(len(items))
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveBaseLayer(): is this a legendLayer? " + str(legend.isLegendLayer(itemToMove))
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveBaseLayer(): item to move is " + itemToMove.text(0)
        # just moving base layer, no need for signals
        legend.blockSignals(True)
        itemToMove.storeAppearanceSettings() # Store settings
        legend.takeTopLevelItem(legend.indexOfTopLevelItem(itemToMove))
        legend.insertTopLevelItem(1, itemToMove)
        itemToMove.restoreAppearanceSettings()
        legend.blockSignals(False)
        itemToMove.setCheckState(0, QtCore.Qt.Checked)
def snippets.moveConstraintLayer (self, legend)
Move the needed constraint layer to third in the layer panel,
    check and make visible.
Definition at line 70 of file snippets.py.
    def moveConstraintLayer(self, legend):
        ''' Move the needed constraint layer to third in the layer panel,
            check and make visible.
        '''
        items = legend.findItems(self.constraintLayerBaseName, QtCore.Qt.MatchFixedString, 0)
        itemToMove = items[0]
        # debugging
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveBaseLayer()"
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveBaseLayer(): length of item list is " + str(len(items))
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveBaseLayer(): is this a legendLayer? " + str(legend.isLegendLayer(itemToMove))
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveBaseLayer(): item to move is " + itemToMove.text(0)
        # just moving base layer, no need for signals
        legend.blockSignals(True)
        itemToMove.storeAppearanceSettings() # Store settings
        legend.takeTopLevelItem(legend.indexOfTopLevelItem(itemToMove))
        legend.insertTopLevelItem(2, itemToMove)
        itemToMove.restoreAppearanceSettings()
        legend.blockSignals(False)
        itemToMove.setCheckState(0, QtCore.Qt.Checked)
''' OLD CODE THAT WORKED TO UPDATE EXTENTS ON MAP CANVAS
    ELIMINATED WHEN I FIGURED OUT HOW TO USE mainwindow.canvas.map().render()
'''
def snippets.moveEditLayer (self, legend)
Move the needed editLayer to the top of the layer panel
    and select, check and make visible.
Definition at line 25 of file snippets.py.
    def moveEditLayer(self, legend):
        ''' Move the needed editLayer to the top of the layer panel
            and select, check and make visible.
        '''
        items = legend.findItems(self.editLayerBaseName, QtCore.Qt.MatchFixedString, 0)
        itemToMove = items[0]
        # debugging
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveEditLayer()"
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveEditLayer(): length of item list is " + str(len(items))
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveEditLayer(): is this a legendLayer? " + str(legend.isLegendLayer(itemToMove))
        print "Main.dlgscenarioedittypes.DlgScenarioEditTypes.moveEditLayer(): item to move is " + itemToMove.text(0)
        # just moving edit layer, no need for signals
        legend.blockSignals(True)
        itemToMove.storeAppearanceSettings() # Store settings
        legend.takeTopLevelItem(legend.indexOfTopLevelItem(itemToMove))
        legend.insertTopLevelItem(0, itemToMove)
        itemToMove.restoreAppearanceSettings()
        legend.blockSignals(False)
        legend.setCurrentItem(itemToMove)
        itemToMove.setCheckState(0, QtCore.Qt.Checked)
def snippets.oldarrangeOrientingLayers (self)
Definition at line 326 of file snippets.py.
References name.
def oldarrangeOrientingLayers(self):
        # debugging
        print "arrangeOrientingLayers()"
        legend = self.legend
        legendLayers = legend.getLayerSet()
        numLegendLayers = len(legendLayers)
        oRLayers = self.orientingRasterLayers
        oVLayers = self.orientingVectorLayers
        rcount = 0
        vcount = 0
        print "numLegendLayers is " + str(numLegendLayers)
        for (counter, legendLayer) in enumerate(legendLayers):
            legendLayerName = legendLayer.layer().name()
            print "legendLayerName is " + legendLayerName
            print "r counter is " + str(counter)
            for orientingLayer in oRLayers:
                info = QtCore.QFileInfo(orientingLayer)
                orientingLayerName = info.completeBaseName()
                print "orientingLayerName is " + orientingLayerName
                if legendLayerName == orientingLayerName:
                    print "orientingLayerName inside is " + orientingLayerName
                    itemToMove = legend.topLevelItem(counter)
                    print "itemToMove is " + itemToMove.canvasLayer.layer().name()
                    position = numLegendLayers - oRLayers.index(orientingLayer) # itemToMove is the base layer
                    print "r position is " + str(position)
                    print type(position), position
                    itemToMove.storeAppearanceSettings() # Store settings
                    self.legend.takeTopLevelItem(counter)
                    legend.insertTopLevelItem(1, itemToMove)
                    rcount += 1
                    print "ending rcount is " + str(rcount)
                    if rcount == len(oRLayers):
                        break
                    else: continue
        # debugging
        print "rcount is " + str(rcount)
        for (counter, legendLayer) in enumerate(legendLayers):
            legendLayerName = legendLayer.layer().name()
            print "legendLayerName is " + legendLayerName
            print "r counter is " + str(counter)
            for orientingLayer in oVLayers:
                info = QtCore.QFileInfo(orientingLayer)
                orientingLayerName = info.completeBaseName()
                print "orientingLayerName is " + orientingLayerName
                if legendLayerName == orientingLayerName:
                    itemToMove = legend.topLevelItem(counter)
                    print "itemToMove is " + itemToMove.canvasLayer.layer().name()
                    position = numLegendLayers - (oVLayers.index(orientingLayer) + (rcount)) # itemToMove is the base layer
                    print "v position is " + str(position)
                    print type(position), position
                    itemToMove.storeAppearanceSettings() # Store settings
                    self.legend.takeTopLevelItem(counter)
                    legend.insertTopLevelItem(0, itemToMove)
                    vcount += 1
                    print "ending vcount is " + str(vcount)
                    if vcount == len(oVLayers):
                        break
                    else: continue
# Martin Dobias reading project properties
'''The QgsProject class offers a similar interface to QSettings for
access to properties. The example is mostly self-explanatory except
for the "[0]" at the end of the readNumEntry lines. This function in
python returns a tuple: first value is the number, second value is a
boolean whether the conversion to number went fine - for simplicity we
ignore that flag here.'''
def snippets.openEditLayer (self)
Definition at line 409 of file snippets.py.
def openEditLayer(self):
            # edit file directory has same name as the scenario file (*.caps)
            info = self.mainwindow.info
            directoryName = info.completeBaseName()
            editFilePath = unicode(info.path() + "/" + directoryName + "/" + self.editLayer + ".shp")
            # debugging
            print "the directory name is " + directoryName
            print "the editFilePath is " + editFilePath
            # if the file exists, open it (automatically goes to the top of the layer panel)
            editFile = QtCore.QFile(editFilePath)
            if editFile.exists():
                self.mainwindow.openVectorLayer(editFilePath)
# unneeded orienting layer code
def snippets.openOrientingBaseLayers (self, layers)
Open needed orienting layers and arrange
Definition at line 427 of file snippets.py.
References name.
def openOrientingBaseLayers(self, layers):
        ''' Open needed orienting layers and arrange '''
        legendLayers = layers
        orientingVlayers = self.mainwindow.orientingVectorLayers
        orientingRlayers = self.mainwindow.orientingRasterLayers
        path = self.mainwindow.baseLayerPath
        # Check for open and open if not
        for legendLayer in legendLayers:
            legendLayerName = layer.layer().name()
            for orientingLayer in orientingVlayers:
                info = QFileInfo(orientingLayer)
                orientingLayerName = info.completeBaseName()
                if legendLayerName == orientingLayerName:
                    orientingVlayers.remove(orientingLayer)
                    continue
            for orientingLayer in orientingRlayers:
                info = QFileInfo(orientingLayer)
                orientingLayerName = info.completeBaseName()
                if legendLayerName == orientingLayerName:
                    orientingVlayers.remove(orientingLayer)
                    continue
#open a file with QFile
def snippets.set_file_readonly (path)
Change path permissions to readonly in a file.
Definition at line 283 of file snippets.py.
References _set_file_attributes().
def set_file_readonly(path):
    """Change path permissions to readonly in a file."""
    # we use the win32 api because chmod just sets the readonly flag and
    # we want to have imore control over the permissions
    groups = {}
    groups[EVERYONE_GROUP] = FILE_GENERIC_READ
    groups[ADMINISTRATORS_GROUP] = FILE_GENERIC_READ
    groups[GetUserName()] = FILE_GENERIC_READ
    # the above equals more or less to 0444
    _set_file_attributes(path, groups)
'''Martin Dobias raster transparency
This way you can access current list of transparency values:
>>> rt=l.rasterTransparency()
>>> lst = rt.transparentSingleValuePixelList()
>>> for item in lst: print item.pixelValue, item.percentTransparent
...
-9999.0 100.0
0.0 50.0
To set a list with just one value:
>>> x = QgsRasterTransparency.TransparentSingleValuePixel()
>>> x.pixelValue = 123
>>> x.transparencyPercent = 50
>>> rt.setTransparentSingleValuePixelList([ x ])
The above examples suppose that you use single band raster. In case of RGB
image the steps are similar, just instead of "SingleValue" methods you would
use "ThreeValue" methods and instead of "pixelValue" attribute there are
"red", "green", "blue" attributes.'''
# obsolete code.  Use legend.findItems().  much easier
def snippets.updateStatusBar (self)
Definition at line 601 of file snippets.py.
    def updateStatusBar(self):
        capture_string = QtCore.QString(self.scenarioFileName)
        self.statusBar.showMessage(capture_string, 8000)
''' save as dialog code '''
Variable Documentation
tuple snippets::a = prj.readNumEntry("Gui", "/SelectionColorAlphaPart", 255)
Definition at line 403 of file snippets.py.
string snippets::ADMINISTRATORS_GROUP = 'Administrators'
Definition at line 262 of file snippets.py.
tuple snippets::b = prj.readNumEntry("Gui", "/SelectionColorBluePart", 0)
Definition at line 402 of file snippets.py.
tuple snippets::brush = QtGui.QBrush()
Definition at line 112 of file snippets.py.
tuple snippets::capture_string = self.activeRLayer.source()
Definition at line 17 of file snippets.py.
snippets::center
Definition at line 755 of file snippets.py.
tuple snippets::clr = QColor(r,g,b,a)
Definition at line 404 of file snippets.py.
tuple snippets::crs = self.provider.crs()
Definition at line 736 of file snippets.py.
tuple snippets::dir = os.path.dirname(self.rfilename)
Definition at line 472 of file snippets.py.
tuple snippets::directoryName = self.info.completeBaseName()
Definition at line 626 of file snippets.py.
tuple snippets::editFile = QtCore.QFile(editFilePath)
Definition at line 454 of file snippets.py.
tuple snippets::editItems = mainwindow.legend.findItems(name, QtCore.Qt.MatchFixedString, 0)
Definition at line 114 of file snippets.py.
tuple snippets::error = unicode(e)
Definition at line 459 of file snippets.py.
string snippets::EVERYONE_GROUP = 'Everyone'
Definition at line 261 of file snippets.py.
tuple snippets::extent = self.canvas.extent()
Definition at line 467 of file snippets.py.
Referenced by Main.legend.Legend.zoomToLegendLayer().
tuple snippets::f = open(vfile, 'rb')
Definition at line 572 of file snippets.py.
tuple snippets::feat = QgsFeature()
Definition at line 700 of file snippets.py.
tuple snippets::fields = line.split()
Definition at line 494 of file snippets.py.
tuple snippets::filter_str = QtCore.QString("CAPS Scenario*.cap *.cap)\nAll Files(*)")
Definition at line 606 of file snippets.py.
tuple snippets::g = prj.readNumEntry("Gui", "/SelectionColorGreenPart", 255)
Definition at line 401 of file snippets.py.
list snippets::groups = [0]
Definition at line 476 of file snippets.py.
tuple snippets::indexMaker = QtGui.QStandardItemModel.index()
Definition at line 717 of file snippets.py.
string snippets::layer = "some layer"
Definition at line 793 of file snippets.py.
Referenced by Main.mainwindow.MainWindow.activeLayerChanged().
tuple snippets::layerExtent = layer.extent()
Definition at line 794 of file snippets.py.
tuple snippets::layerId = activeVLayer.id()
Definition at line 101 of file snippets.py.
tuple snippets::lock = LockFile(vfile)
Definition at line 539 of file snippets.py.
string snippets::lockFile = ".lckchk"
Definition at line 577 of file snippets.py.
tuple snippets::name = activeVLayer.name()
Definition at line 99 of file snippets.py.
Referenced by oldarrangeOrientingLayers(), and openOrientingBaseLayers().
string snippets::parent = "some widget's parent"
Definition at line 12 of file snippets.py.
Referenced by Main.legend.Legend.activeLayer().
list snippets::pid = fields[0]
Definition at line 495 of file snippets.py.
tuple snippets::prj = QgsProject.instance()
Definition at line 399 of file snippets.py.
list snippets::process = fields[4]
Definition at line 496 of file snippets.py.
string snippets::processname = 'aterm'
Definition at line 491 of file snippets.py.
tuple snippets::provider = self.vlayer.dataProvider()
Definition at line 699 of file snippets.py.
tuple snippets::qd = QtGui.QFileDialog()
Definition at line 605 of file snippets.py.
snippets::qgspoint
Definition at line 744 of file snippets.py.
tuple snippets::r = prj.readNumEntry("Gui", "/SelectionColorRedPart", 255)
Definition at line 400 of file snippets.py.
snippets::rb
Definition at line 755 of file snippets.py.
tuple snippets::renderer = QgsSingleSymbolRenderer(QGis.Polygon)
Definition at line 126 of file snippets.py.
snippets::scenario = None
Definition at line 597 of file snippets.py.
tuple snippets::scenarioFileName
Initial value:
unicode(qd.getSaveFileName(self, QtCore.QString("New Scenario"),
                                            dir, filter_str))
Definition at line 610 of file snippets.py.
tuple snippets::selection = QtGui.QItemSelection(topLeft, oldSelection)
Definition at line 719 of file snippets.py.
string snippets::self = "some class"
Definition at line 11 of file snippets.py.
tuple snippets::symbol = renderer.symbols()
Definition at line 127 of file snippets.py.
tuple snippets::text = QtCore.QString("(%1,%2)")
Definition at line 714 of file snippets.py.
Referenced by Main.dlgmanageprojects.DlgManageProjects.addScenarioToProject(), Main.dlgscenarioedittypes.DlgScenarioEditTypes.colorEditBaseConstraintLayers(), Main.dlgmanageprojects.DlgManageProjects.getScenariosInProject(), Main.dlgmanageprojects.DlgManageProjects.isProjectDirty(), Main.dlgmanageprojects.DlgManageProjects.removeScenarioFromProject(), Main.dlgmanageprojects.DlgManageProjects.validateSendData(), and Main.dlgmanageprojects.DlgManageProjects.writeProjectFile().
tuple snippets::title = QtCore.QString("Error")
Definition at line 802 of file snippets.py.
tuple snippets::topLeft = indexMaker.createIndex(0,0)
Definition at line 718 of file snippets.py.
tuple snippets::txt
Initial value:
QtCore.QString("You can only select features from a vector layer.\
Please select a vector layer in the layer panel and click 'Select Features' again.")
Definition at line 804 of file snippets.py.
tuple snippets::vfileID = self.activeVLayer.getLayerID()
Definition at line 190 of file snippets.py.
tuple snippets::vfilePath = activeVLayer.source()
Definition at line 96 of file snippets.py.
tuple snippets::writer = QgsVectorFileWriter("test_points.shp", "UTF-8", fields, QGis.WKBPoint, crs)
Definition at line 738 of file snippets.py.